const G = { bgColor: '#F5EFE6', accentColor: '#C8A882', textColor: '#2B1F16' };
const B = { bgColor: '#F0F8FF', accentColor: '#7A9EE0', textColor: '#0E1A3A' };
const A = { bgColor: '#FFF7EC', accentColor: '#E0A040', textColor: '#2A1800' };
const S = { bgColor: '#F8F0FF', accentColor: '#9060D0', textColor: '#180028' };

export const MILESTONE_FRAMES = [
  // ── GRAVIDITET ──
  { id: 'preg-test',    category: 'Graviditet', label: 'Positiv test',              emoji: '🤍', ...G, headline: 'Positiv test',                    subline: 'En ny rejse begynder' },
  { id: 'preg-12scan',  category: 'Graviditet', label: '12 ugers scanning',         emoji: '🌱', ...G, headline: 'Hej baby!',                        subline: '12 ugers scanning' },
  { id: 'preg-20scan',  category: 'Graviditet', label: '20 ugers scanning',         emoji: '🫶', ...G, headline: 'Hej igen baby!',                   subline: '20 ugers scanning' },
  { id: 'preg-kicks',   category: 'Graviditet', label: 'Første spark',              emoji: '💛', ...G, headline: 'I dag mærkede jeg dig',             subline: 'For første gang' },
  { id: 'preg-4',       category: 'Graviditet', label: '4 uger i maven',            emoji: '🌿', ...G, headline: '4 uger i maven',                   subline: '' },
  { id: 'preg-8',       category: 'Graviditet', label: '8 uger i maven',            emoji: '🌿', ...G, headline: '8 uger i maven',                   subline: '' },
  { id: 'preg-12',      category: 'Graviditet', label: '12 uger i maven',           emoji: '🌿', ...G, headline: '12 uger i maven',                  subline: '' },
  { id: 'preg-16',      category: 'Graviditet', label: '16 uger i maven',           emoji: '🌿', ...G, headline: '16 uger i maven',                  subline: '' },
  { id: 'preg-20',      category: 'Graviditet', label: '20 uger i maven',           emoji: '🌿', ...G, headline: '20 uger i maven',                  subline: 'Halvvejs! 🌟' },
  { id: 'preg-24',      category: 'Graviditet', label: '24 uger i maven',           emoji: '🌿', ...G, headline: '24 uger i maven',                  subline: '' },
  { id: 'preg-28',      category: 'Graviditet', label: '28 uger i maven',           emoji: '🌿', ...G, headline: '28 uger i maven',                  subline: '3. trimester starter' },
  { id: 'preg-32',      category: 'Graviditet', label: '32 uger i maven',           emoji: '🌿', ...G, headline: '32 uger i maven',                  subline: '' },
  { id: 'preg-36',      category: 'Graviditet', label: '36 uger i maven',           emoji: '🌿', ...G, headline: '36 uger i maven',                  subline: 'Snart fuldbåren!' },
  { id: 'preg-40',      category: 'Graviditet', label: '40 uger i maven',           emoji: '🎉', ...G, headline: '40 uger i maven',                  subline: 'Terminen er her!' },
  { id: 'preg-41',      category: 'Graviditet', label: '41 uger i maven',           emoji: '🧸', ...G, headline: '41 uger i maven',                  subline: '' },
  { id: 'preg-42',      category: 'Graviditet', label: '42 uger i maven',           emoji: '🧸', ...G, headline: '42 uger i maven',                  subline: '' },

  // ── BABY ──
  { id: 'baby-born',    category: 'Baby', label: 'Kom til verden',                  emoji: '🍼', ...B, headline: 'I dag kom jeg til verden',          subline: 'Velkommen, lille en 🤍' },
  { id: 'baby-smile',   category: 'Baby', label: 'Første smil',                     emoji: '😊', ...B, headline: 'I dag smilede jeg',                 subline: 'For første gang' },
  { id: 'baby-laugh',   category: 'Baby', label: 'Første grin',                     emoji: '😄', ...B, headline: 'I dag grinte jeg',                  subline: 'For første gang' },
  { id: 'baby-roll1',   category: 'Baby', label: 'Rullede mave→ryg',                emoji: '🔄', ...B, headline: 'I dag rullede jeg',                 subline: 'Fra mave til ryg' },
  { id: 'baby-roll2',   category: 'Baby', label: 'Rullede ryg→mave',                emoji: '🔄', ...B, headline: 'I dag rullede jeg',                 subline: 'Fra ryg til mave' },
  { id: 'baby-sit',     category: 'Baby', label: 'Sad selv',                        emoji: '🧘', ...B, headline: 'I dag sad jeg selv',                subline: 'For første gang' },
  { id: 'baby-feet',    category: 'Baby', label: 'Opdagede fødderne',               emoji: '🦶', ...B, headline: 'I dag opdagede jeg',                subline: 'Mine fødder' },
  { id: 'baby-crawl',   category: 'Baby', label: 'Første kravl',                    emoji: '🐣', ...B, headline: 'I dag lærte jeg at kravle',         subline: '' },
  { id: 'baby-food',    category: 'Baby', label: 'Første mad',                      emoji: '🥄', ...B, headline: 'I dag smagte jeg',                  subline: 'Min første mad' },
  { id: 'baby-cup',     category: 'Baby', label: 'Drak af kop',                     emoji: '🥤', ...B, headline: 'I dag drak jeg selv af kop',        subline: '' },
  { id: 'baby-tooth',   category: 'Baby', label: 'Første tand',                     emoji: '🦷', ...B, headline: 'Jeg har fået min første tand',      subline: 'Lille perletand!' },
  { id: 'baby-word',    category: 'Baby', label: 'Første ord',                      emoji: '💬', ...B, headline: 'I dag sagde jeg mit første ord',    subline: '' },
  { id: 'baby-mor',     category: 'Baby', label: 'Sagde "mor"',                     emoji: '💗', ...B, headline: 'I dag sagde jeg "mor"',             subline: 'For første gang' },
  { id: 'baby-far',     category: 'Baby', label: 'Sagde "far"',                     emoji: '💙', ...B, headline: 'I dag sagde jeg "far"',             subline: 'For første gang' },
  { id: 'baby-steps',   category: 'Baby', label: 'Første skridt',                   emoji: '👣', ...B, headline: 'I dag gik jeg mine første skridt',  subline: 'Nu er der ingen vej tilbage!' },
  { id: 'baby-vugg',    category: 'Baby', label: 'Startede i vuggestue',            emoji: '🏠', ...B, headline: 'I dag startede jeg i vuggestue',    subline: '' },
  { id: 'baby-bhave',   category: 'Baby', label: 'Startede i børnehave',            emoji: '🎒', ...B, headline: 'I dag startede jeg i børnehave',    subline: '' },
  { id: 'baby-ferie',   category: 'Baby', label: 'Første ferie',                    emoji: '✈️', ...S, headline: 'Min første ferie',                  subline: '' },
  { id: 'baby-jul',     category: 'Baby', label: 'Første jul',                      emoji: '🎄', ...S, headline: 'Min første jul',                    subline: '' },
  { id: 'baby-nytaar',  category: 'Baby', label: 'Første nytår',                    emoji: '🎆', ...S, headline: 'Mit første nytår',                  subline: '' },

  // ── ALDER ──
  { id: 'age-1w',   category: 'Alder', label: '1 uge',            emoji: '🤍', ...A, headline: '1 uge',             subline: '' },
  { id: 'age-2w',   category: 'Alder', label: '2 uger',           emoji: '🤍', ...A, headline: '2 uger',            subline: '' },
  { id: 'age-3w',   category: 'Alder', label: '3 uger',           emoji: '🤍', ...A, headline: '3 uger',            subline: '' },
  { id: 'age-1m',   category: 'Alder', label: '1 måned',          emoji: '🌙', ...A, headline: '1 måned gammel',    subline: '' },
  { id: 'age-2m',   category: 'Alder', label: '2 måneder',        emoji: '🌙', ...A, headline: '2 måneder gammel',  subline: '' },
  { id: 'age-3m',   category: 'Alder', label: '3 måneder',        emoji: '🌙', ...A, headline: '3 måneder gammel',  subline: '' },
  { id: 'age-4m',   category: 'Alder', label: '4 måneder',        emoji: '🌙', ...A, headline: '4 måneder gammel',  subline: '' },
  { id: 'age-5m',   category: 'Alder', label: '5 måneder',        emoji: '🌙', ...A, headline: '5 måneder gammel',  subline: '' },
  { id: 'age-6m',   category: 'Alder', label: '6 måneder',        emoji: '🌙', ...A, headline: '6 måneder gammel',  subline: 'Halvt et år! 🌟' },
  { id: 'age-7m',   category: 'Alder', label: '7 måneder',        emoji: '🌙', ...A, headline: '7 måneder gammel',  subline: '' },
  { id: 'age-8m',   category: 'Alder', label: '8 måneder',        emoji: '🌙', ...A, headline: '8 måneder gammel',  subline: '' },
  { id: 'age-9m',   category: 'Alder', label: '9 måneder',        emoji: '🌙', ...A, headline: '9 måneder gammel',  subline: '' },
  { id: 'age-10m',  category: 'Alder', label: '10 måneder',       emoji: '🌙', ...A, headline: '10 måneder gammel', subline: '' },
  { id: 'age-11m',  category: 'Alder', label: '11 måneder',       emoji: '🌙', ...A, headline: '11 måneder gammel', subline: '' },
  { id: 'age-12m',  category: 'Alder', label: '12 måneder',       emoji: '🌙', ...A, headline: '12 måneder gammel', subline: '' },
  { id: 'age-13m',  category: 'Alder', label: '13 måneder',       emoji: '🌙', ...A, headline: '13 måneder gammel', subline: '' },
  { id: 'age-14m',  category: 'Alder', label: '14 måneder',       emoji: '🌙', ...A, headline: '14 måneder gammel', subline: '' },
  { id: 'age-15m',  category: 'Alder', label: '15 måneder',       emoji: '🌙', ...A, headline: '15 måneder gammel', subline: '' },
  { id: 'age-16m',  category: 'Alder', label: '16 måneder',       emoji: '🌙', ...A, headline: '16 måneder gammel', subline: '' },
  { id: 'age-17m',  category: 'Alder', label: '17 måneder',       emoji: '🌙', ...A, headline: '17 måneder gammel', subline: '' },
  { id: 'age-18m',  category: 'Alder', label: '18 måneder',       emoji: '🌙', ...A, headline: '18 måneder gammel', subline: '' },
  { id: 'age-19m',  category: 'Alder', label: '19 måneder',       emoji: '🌙', ...A, headline: '19 måneder gammel', subline: '' },
  { id: 'age-20m',  category: 'Alder', label: '20 måneder',       emoji: '🌙', ...A, headline: '20 måneder gammel', subline: '' },
  { id: 'age-21m',  category: 'Alder', label: '21 måneder',       emoji: '🌙', ...A, headline: '21 måneder gammel', subline: '' },
  { id: 'age-22m',  category: 'Alder', label: '22 måneder',       emoji: '🌙', ...A, headline: '22 måneder gammel', subline: '' },
  { id: 'age-23m',  category: 'Alder', label: '23 måneder',       emoji: '🌙', ...A, headline: '23 måneder gammel', subline: '' },
  { id: 'age-24m',  category: 'Alder', label: '24 måneder',       emoji: '🌙', ...A, headline: '24 måneder gammel', subline: '' },
  { id: 'age-1y',   category: 'Alder', label: '1 års fødselsdag', emoji: '🎂', ...A, headline: '1 års fødselsdag',  subline: 'Tillykke! 🎉' },
  { id: 'age-2y',   category: 'Alder', label: '2 års fødselsdag', emoji: '🎂', ...A, headline: '2 års fødselsdag',  subline: 'Tillykke! 🎉' },
  { id: 'age-3y',   category: 'Alder', label: '3 års fødselsdag', emoji: '🎂', ...A, headline: '3 års fødselsdag',  subline: 'Tillykke! 🎉' },
];

export const CATEGORIES = ['Alle', 'Graviditet', 'Baby', 'Alder'];