export const MILESTONE_FRAMES = [
  // ── GRAVIDITET ──
  {
    id: 'preg-12',
    category: 'Graviditet',
    label: 'Uge 12',
    emoji: '🌱',
    bgColor: '#F5EFE6',
    accentColor: '#C8A882',
    textColor: '#2B1F16',
    headline: 'Uge 12',
    subline: 'Vi venter en lille en 🤍',
  },
  {
    id: 'preg-20',
    category: 'Graviditet',
    label: 'Uge 20',
    emoji: '🫶',
    bgColor: '#EFF5F0',
    accentColor: '#7BAE8A',
    textColor: '#1A3020',
    headline: 'Uge 20',
    subline: 'Halvvejs! 🌿',
  },
  {
    id: 'preg-28',
    category: 'Graviditet',
    label: 'Uge 28',
    emoji: '💛',
    bgColor: '#FDF6E3',
    accentColor: '#D4A72C',
    textColor: '#3A2800',
    headline: 'Uge 28',
    subline: '3. trimester starter 🌟',
  },
  {
    id: 'preg-33',
    category: 'Graviditet',
    label: 'Uge 33',
    emoji: '🤱',
    bgColor: '#F9EEF5',
    accentColor: '#C27AB8',
    textColor: '#2E0E2A',
    headline: 'Uge 33',
    subline: 'Snart, snart, snart... 🌸',
  },
  {
    id: 'preg-36',
    category: 'Graviditet',
    label: 'Uge 36',
    emoji: '🧸',
    bgColor: '#F0F4FA',
    accentColor: '#5A82C2',
    textColor: '#0E1E3A',
    headline: 'Uge 36',
    subline: 'Fuldbåren om lidt 💙',
  },
  {
    id: 'preg-40',
    category: 'Graviditet',
    label: 'Uge 40',
    emoji: '🎉',
    bgColor: '#FFF0F0',
    accentColor: '#E07070',
    textColor: '#3A0000',
    headline: 'Uge 40',
    subline: 'Terminen er her! ❤️',
  },

  // ── BABY ──
  {
    id: 'baby-1w',
    category: 'Baby',
    label: '1 uge',
    emoji: '🍼',
    bgColor: '#FDF9F0',
    accentColor: '#C8A882',
    textColor: '#2B1F16',
    headline: '1 uge gammel',
    subline: 'Velkommen til verden 🤍',
  },
  {
    id: 'baby-1m',
    category: 'Baby',
    label: '1 måned',
    emoji: '🌙',
    bgColor: '#F0F4FF',
    accentColor: '#7A9EE0',
    textColor: '#0E1A3A',
    headline: '1 måned',
    subline: 'En hel måned 💙',
  },
  {
    id: 'baby-3m',
    category: 'Baby',
    label: '3 måneder',
    emoji: '😊',
    bgColor: '#F0FBF4',
    accentColor: '#5AAA7A',
    textColor: '#0A2A18',
    headline: '3 måneder',
    subline: 'Smilende og nysgerrig 🌿',
  },
  {
    id: 'baby-6m',
    category: 'Baby',
    label: '6 måneder',
    emoji: '🥄',
    bgColor: '#FFF7EC',
    accentColor: '#E0A040',
    textColor: '#2A1800',
    headline: '6 måneder',
    subline: 'Halvt et år! 🌟',
  },
  {
    id: 'baby-9m',
    category: 'Baby',
    label: '9 måneder',
    emoji: '🐣',
    bgColor: '#FDF0F8',
    accentColor: '#D070B0',
    textColor: '#2A0020',
    headline: '9 måneder',
    subline: 'Kravler og udforsker 💜',
  },
  {
    id: 'baby-1y',
    category: 'Baby',
    label: '1 år',
    emoji: '🎂',
    bgColor: '#FFF0E8',
    accentColor: '#E07040',
    textColor: '#3A0E00',
    headline: '1 år 🎉',
    subline: 'Tillykke med fødselsdagen!',
  },
  {
    id: 'baby-2y',
    category: 'Baby',
    label: '2 år',
    emoji: '🎈',
    bgColor: '#F0F8FF',
    accentColor: '#40A0D0',
    textColor: '#001828',
    headline: '2 år 🎈',
    subline: 'Et lille menneske!',
  },

  // ── SÆRLIGE ØJEBLIKKE ──
  {
    id: 'moment-smile',
    category: 'Øjeblikke',
    label: 'Første smil',
    emoji: '😄',
    bgColor: '#FFFBEC',
    accentColor: '#F0C040',
    textColor: '#2A1E00',
    headline: 'Mit første smil 😄',
    subline: 'Det smukkeste øjeblik',
  },
  {
    id: 'moment-tooth',
    category: 'Øjeblikke',
    label: 'Første tand',
    emoji: '🦷',
    bgColor: '#F0FAFA',
    accentColor: '#40C0C0',
    textColor: '#002828',
    headline: 'Min første tand 🦷',
    subline: 'Lille perletand!',
  },
  {
    id: 'moment-steps',
    category: 'Øjeblikke',
    label: 'Første skridt',
    emoji: '👣',
    bgColor: '#F8F0FF',
    accentColor: '#9060D0',
    textColor: '#180028',
    headline: 'Mine første skridt 👣',
    subline: 'Nu er der ingen vej tilbage!',
  },
  {
    id: 'moment-word',
    category: 'Øjeblikke',
    label: 'Første ord',
    emoji: '💬',
    bgColor: '#F0FFF4',
    accentColor: '#30B060',
    textColor: '#002818',
    headline: 'Mit første ord 💬',
    subline: 'En stemme er fundet',
  },
];

export const CATEGORIES = ['Alle', 'Graviditet', 'Baby', 'Øjeblikke'];