import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  da: {
    // Nav
    home: 'Hjem',
    menu: 'Menu',
    shop: 'Shop',
    blog: 'Søg og find svar',
    sleepLog: 'Søvnlog',
    knowledge: 'Viden',
    community: 'Community',
    calendar: 'Kalender',
    profile: 'Profil',
    natteensomhed: 'Et lys i mørket',

    // Home
    goodDay: 'God dag, mor 🤍',
    dailyWord: 'Dagens ord til dig',
    fromBlog: 'Fra bloggen',
    seeAll: 'Se alle →',
    affirmations: [
      "Du er en vidunderlig mor — selv på dage hvor det ikke føles sådan. 🤍",
      "Det er okay at kaffen er kold. Du er varm og til stede, og det er nok.",
      "Du behøver ikke at gøre alt perfekt. Du behøver bare at gøre dit bedste — og det gør du.",
      "Søvnmangel er hårdt. At du holder ved er bevis på din utrolige styrke.",
      "Dit barn ved ikke hvad 'perfekt' betyder. De ved bare at de elsker dig.",
      "De der siger at moderskab er nemt, har aldrig prøvet det. Du klarer dette!",
      "Ethvert lille smil fra dit barn er bevis på at du gør det rigtigt.",
      "Du er ikke alene. Tusinder af mødre sidder lige nu og føler præcis det samme.",
      "Det er okay at have brug for hjælp. At bede om den er faktisk modig.",
      "I dag er du nok. I morgen er du nok. Altid er du nok.",
      "Dine tårer er ikke svaghed — de er kærlighed der er overløbet.",
      "Ingen håndbok kan forberede dig på den kærlighed du føler. Du er stærk.",
      "Du har gjort noget utroligt. Du har skabt et menneske. Husk det.",
      "Nogle dage er det nok at alle lever og er relativt mætte. 🙌",
      "Du er dit babys yndlingsperson i hele verden. Altid.",
      "Selvom du er træt, er du stadig der. Det er kærlighed i sin reneste form.",
      "Ingen mor er perfekt. Men du er den perfekte mor for dit barn.",
      "En god mor er ikke en der aldrig fejler — men en der altid prøver igen.",
      "Tillykke fordi du overlevede endnu en nat. Du fortjener en medalje (og mere kaffe).",
      "Din kærlighed er det varmeste sted dit barn kender. 🧡",
      "Selv de svære dage formes jer begge til noget stærkere.",
      "Du er meget mere end 'bare en mor'. Du er en hverdagshelt.",
      "Det du giver dit barn i dag, bærer de med sig hele deres liv.",
      "En dag hvor du næppe klarer det, er stadig en dag fuld af kærlighed.",
      "Du håndterer mere end du ved. Det er det smukkeste ved dig.",
      "Ethvert kram, hver amning, hvert søvnforsøg — det tæller.",
      "Moderskab er ikke en præstation. Det er et forhold. Og dit er smukt.",
      "Du har ikke fejlet. Du er midt i det.",
      "I morgen er en ny chance. Og du er allerede klar til det.",
      "Du bærer så meget. Men du bærer det med kærlighed.",
    ],

    // Profile
    profileTitle: 'Profil',
    edit: 'Rediger',
    editProfile: 'Rediger profil',
    username: 'Brugernavn',
    displayName: 'Visningsnavn',
    city: 'By',
    childBirthdate: 'Barnets fødselsdag',
    wonderWeekInfo: 'Bruges til beregning af tigerspring 🐯',
    saveChanges: 'Gem ændringer',
    saving: 'Gemmer…',
    profileUpdated: 'Profil opdateret',
    favorites: 'Favoritter',
    notifications: 'Notifikationer',
    questions: 'Spørgsmål',
    settings: 'Indstillinger',
    help: 'Hjælp',
    shareLocation: 'Del lokation',
    showAsVisible: 'Vis mig som synlig',
    logOut: 'Log ud',
    language: 'Sprog',
    chooseLanguage: 'Vælg sprog',

    // Settings
    settingsTitle: 'Indstillinger',
    password: 'Adgangskode',
    privacy: 'Privatliv',
    theme: 'Tema',
    chooseTheme: 'Vælg dit foretrukne look',
    light: 'Lys',
    dark: 'Mørk',
    faq: 'Ofte stillede spørgsmål',
    contactSupport: 'Kontakt support',
    deleteAccount: 'Slet konto',
    blogAndArticles: 'Blog & Artikler',
    changePassword: 'Skift adgangskode',
    currentPassword: 'Nuværende adgangskode',
    newPassword: 'Ny adgangskode',
    confirmPassword: 'Bekræft ny adgangskode',
    updatePassword: 'Opdater adgangskode',
    passwordMismatch: 'Adgangskoderne matcher ikke',
    passwordUpdated: 'Adgangskode opdateret',
    deleteWarning: 'Er du sikker? Denne handling kan ikke fortrydes — al din data slettes permanent.',
    typeToConfirmDelete: 'Skriv SLET for at bekræfte',
    deleteConfirmWord: 'SLET',
    deletePermanently: 'Slet min konto permanent',
    faqQ1: 'Hvordan ændrer jeg min profil?',
    faqA1: 'Gå til din profil og tryk på "Rediger".',
    faqQ2: 'Hvordan finder jeg en behandler?',
    faqA2: 'Find en behandler under Community-fanen.',

    // Knowledge
    knowledgeTitle: 'Viden & Svar',
    searchPlaceholder: 'Søg i viden...',
    articles: 'Artikler',
    noResults: 'Ingen resultater for',
    noFaq: 'Ingen FAQ endnu',
    noQuestions: 'Ingen spørgsmål endnu',
    askQuestion: 'Stil et spørgsmål',
    answered: 'Besvaret',
    open: 'Åben',
    by: 'af',
    answers: 'svar',

    // Shop
    shopTitle: 'Shop',
    searchProducts: 'Søg produkter...',
    noProducts: 'Ingen produkter fundet',
    sortBy: 'Sorter efter',
    newest: 'Nyeste',
    priceLow: 'Pris: Lav til høj',
    priceHigh: 'Pris: Høj til lav',
    filtersTitle: 'Filtre & Sortering',
    outOfStock: 'Udsolgt',
    catAll: 'Alle',
    catCare: 'Pleje',
    catAccessories: 'Tilbehør',
    catEquipment: 'Udstyr',
    catBooks: 'Bøger',

    // Blog
    blogTitle: 'Søg og find svar',
    searchBlog: 'Søg indlæg...',
    noPosts: 'Ingen indlæg fundet',
    allCategories: 'Alle',

    // Community
    nearMe: 'Nær mig',
    chats: 'Chats',
    practitioners: 'Behandlere',
    aboutUs: 'Om os',
    onlyForMoms: 'Kun for mødre',
    onlyForMomsDesc: 'Natteensomhed-funktionen er forbeholdt mor-profiler. Vores mission er at bekæmpe natteensomhed blandt mødre — et trygt rum kun for dem.',
    switchToMomProfile: 'Opret profil for at få adgang.',
    location: 'Lokation',
    findNearby: 'Find folk i nærheden',
    locationActive: 'Aktiv',
    enableLocation: 'Aktiver',
    showMeVisible: 'Vis mig som synlig for andre',
    activeMomsInDenmark: 'Vågne mødre nær dig',
    activeNow: 'aktive nu',
    visible: 'Synlig',
    hidden: 'Skjult',
    you: 'Dig',
    othersActive: 'Andre aktive',
    enableLocationToSee: 'Aktiver lokation for at se hvem der er i nærheden',
    noUsersNearby: 'Ingen brugere i nærheden (20 km)',
    personWithin: 'person indenfor 20 km',
    personsWithin: 'personer indenfor 20 km',
    noConversations: 'Ingen samtaler endnu',
    startChatNearby: 'Start en chat med nogen i nærheden',
    unknown: 'Ukendt',
    findPractitioner: 'Find behandler',
    showingInArea: 'Viser eksperter i dit område',
    showingRecommended: 'Viser anbefalede behandlere',
    all: 'Alle',
    searchInMyArea: 'Søg i mit område',
    noExpertsInArea: 'Ingen eksperter fundet i dit område',
    noExpertsAvailable: 'Ingen eksperter tilgængelige',
    showAllExperts: 'Vis alle eksperter',
    recommendedPractitioners: 'Anbefalede behandlere',
    locationConsentTitle: 'Brug af lokation',
    locationConsentDesc: 'Aktiver lokation for at opdage mødre i nærheden, der også er vågne. Din præcise lokation deles aldrig med andre brugere — kun en omtrentlig afstand vises (fx "2 km væk").',
    locationConsentNote: 'Lokation bruges udelukkende til at finde brugere i nærheden. Du kan til enhver tid deaktivere det igen under indstillinger.',
    noThanks: 'Nej tak',
    activateLocation: 'Aktiver lokation',
    locationActivated: 'Lokation aktiveret',
    locationError: 'Kunne ikke hente lokation',
    browserNoLocation: 'Din browser understøtter ikke lokation',

    // SleepLog
    sleepLogTitle: 'Søvnlog',
    historyBtn: 'Historik',
    logTodayBtn: 'Log i dag',
    todayLog: 'Dagens log',
    nightSleep: 'Natsøvn',
    nightWakings: 'Natlige opvågninger',
    naps: 'Lure',
    nap: 'Lur',
    howDidBabyFallAsleep: 'Hvordan faldt barnet i søvn?',
    moodBeforeBed: 'Humør før sengetid',
    notes: 'Noter',
    notesPlaceholder: 'Hvad skete der i dag? Urolig aften? Ny tand?',
    addWaking: 'Tilføj opvågning',
    addNap: 'Tilføj lur',
    bedtime: 'Sengetid',
    fellAsleep: 'Faldt i søvn',
    wokeUp: 'Vågnede',
    date: 'Dato',
    ageMonths: 'Alder (måneder)',
    agePlaceholder: 'f.eks. 8',
    saveSleepLog: 'Gem søvnlog',
    saving: 'Gemmer...',
    sleepLogSaved: 'Søvnlog gemt ✓',
    getAiAdvice: 'Få AI-råd til søvnen',
    updateAiAdvice: 'Opdater AI-råd',
    updateAnalysis: 'Opdater analyse',
    aiAnalyzing: 'AI-eksperten analyserer jeres søvndata…',
    aiErrorMsg: 'Kunne ikke hente analyse lige nu. Prøv igen om lidt — du gør det godt!',
    aiErrorTitle: '💛 En kærlig hilsen',
    noLogsYet: 'Ingen logs endnu',
    bedAt: 'Seng',
    wakings: 'opvågning',
    wakingsPlural: 'opvågninger',
    felAsleepIn: 'Puttetid:',
    nightSleepDuration: 'Nattesøvn:',
    nightNap: 'natsøvn',
    napTotal: 'lure',
    sleepMethodSelf: 'Selv',
    sleepMethodNursing: 'Amning',
    sleepMethodBottle: 'Flaske',
    sleepMethodRocking: 'Vugning',
    sleepMethodPram: 'Barnevogn',
    sleepMethodParent: 'Med forælder',
    moodFresh: 'Frisk',
    moodLittleTired: 'Lidt træt',
    moodVeryTired: 'Meget træt',
    moodOvertired: 'Overtræt',
    wakingMethodNursing: 'Amning',
    wakingMethodBottle: 'Flaske',
    wakingMethodRocking: 'Vugning',
    wakingMethodSing: 'Sig i søvn',
    wakingMethodPram: 'Barnevogn',
    wakingMethodSelf: 'Sov selv',

    // AIChat
    aiChatTitle: 'Baby & Søvn Ekspert',
    aiOnline: 'AI-assistent · Online',
    aiGreeting: 'Hej! Jeg er her for dig 🤍',
    aiSubtitle: 'Ekspert i babysøvn, amning og barnets udvikling. Spørg mig om alt!',
    aiSuggestion1: 'Hvordan hjælper jeg min baby til at sove bedre?',
    aiSuggestion2: 'Hvad er søvnregression?',
    aiSuggestion3: 'Min baby sover kun 20 min ad gangen — hjælp!',
    aiPlaceholder: 'Skriv dit spørgsmål…',
    aiDisclaimer: 'AI-assistenten kan lave fejl og erstatter ikke lægefaglig rådgivning.',
    backLabel: 'Gå tilbage',
    sendLabel: 'Send besked',

    // Community / shared
    version: 'Version 1.0.0',
    v1: 'v1.0',

    // Profile extra
    momProfileLabel: 'Mor-profil · Adgang til community',
    dadProfileLabel: 'Far-profil · Søvnlog',
    genderLabel: 'Køn',
    female: 'Kvinde',
    male: 'Mand',
    genderLocked: 'Køn kan ikke ændres efter valg',
    myDataPrivacy: 'Mine data & privatliv',
    helpAndContact: 'Hjælp & kontakt',
    aboutApp: 'Om appen',
    writeToUs: 'Skriv til os',
    callUs: 'Ring til os',

    // Settings extra
    loading: 'Indlæser...',
    noFaqAvailable: 'Ingen FAQ tilgængelig endnu.',
    noSupportInfo: 'Ingen supportinfo tilgængelig endnu.',
    noPrivacyPolicy: 'Ingen privatlivspolitik tilgængelig endnu.',

    // Shop extra
    categoryLabel: 'Kategori',
    productsLabel: 'produkter',
    categoriesTitle: 'Kategorier',
    filtersAndSorting: 'Filtre & Sortering',

    // Onboarding
    whoAreYou: 'Hvem er du?',
    chooseRoleSubtitle: 'Vælg din rolle i familien',
    welcomeTitle: 'Velkommen til LALATOTO',
    welcomeSubtitle: 'Opret din profil og acceptér betingelserne',
    whereDoYouLive: 'Hvor bor du?',
    findNearbyMoms: 'Find mødre i nærheden af dig',
    aboutYourChild: 'Om dit barn',
    calculateWonderWeeksSubtitle: 'Så kan vi beregne tigerspring for dig',
    lalatotoBuiltForFamily: 'LALATOTO er bygget til hele familien. Vælg din rolle, så vi kan tilpasse oplevelsen til dig.',
    mom: 'Mor',
    dad: 'Far',
    momDesc: 'Community, søvnlog & mere',
    dadDesc: 'Søvnlog & viden',
    nightLonelinessTitle: '🌙 Natteensomhed',
    nightLonelinessDesc: 'Natteensomhed-rummet er et trygt rum kun for mødre — for dem der er vågne om natten og har brug for at vide, at de ikke er alene.',
    yourName: 'Dit navn',
    namePlaceholder: 'Navn...',
    usernameLabel: 'Brugernavn',
    usernameHint: 'Kun bogstaver, tal og underscore',
    uploadingLabel: 'Uploader...',
    addProfilePic: 'Tilføj profilbillede (valgfrit)',
    iAcceptTerms: 'Jeg accepterer',
    termsLinkLabel: 'handelsbetingelserne',
    privacyLinkLabel: 'privatlivspolitikken',
    termsTitle: 'Handelsbetingelser',
    privacyTitle: 'Privatlivspolitik',
    yourCity: 'Din by',
    cityDesc: 'Vi bruger din by til at vise dig andre mødre i nærheden — helt frivilligt.',
    cityPlaceholder: 'fx København, Aarhus...',
    childBirthdateLabel: 'Barnets fødselsdato',
    orLabel: 'eller',
    dueDateLabel: 'Terminsdato (hvis ikke født endnu)',
    skip: 'Spring over',
    back: 'Tilbage',
    getStarted: 'Kom i gang 🎉',
    next: 'Næste',
    errorChooseRole: 'Vælg om du er mor eller far',
    errorEnterName: 'Indtast dit navn',
    errorChooseUsername: 'Vælg et brugernavn',
    errorUsernameMin: 'Mindst 3 tegn',
    errorAcceptTerms: 'Du skal acceptere handelsbetingelserne',
    errorAcceptPrivacy: 'Du skal acceptere privatlivspolitikken',
    usernameOnlyChars: 'Kun bogstaver, tal og underscore',

    // ChildDevelopmentCard
    dueIn: 'Termin om',
    yourChildIs: 'Dit barn er',
    old: 'gammel',
    untilDue: 'til termin',
    weekSingular: 'uge',
    weekPlural: 'uger',
    daySingular: 'dag',
    dayPlural: 'dage',
    monthsShort: 'mdr',
    hoursShort: 't',
    minutesShort: 'm',

    // SleepSummaryCard
    sleepLastNight: 'Søvn i nat',
    wakingSingular: 'opvågning',
    wakingPlural: 'opvågninger',
    logSleepCta: 'Log søvn →',

    // UpcomingEventCard
    nextAppointment: 'Næste aftale',
    today: 'I dag',
    tomorrow: 'I morgen',
    addAppointmentCta: 'Tilføj aftale →',

    // SleepAdviceCard
    sleepAdviceTitle: 'Søvnråd fra eksperten',
    seeSleepLog: 'Se søvnlog →',
    basedOnLogs: 'Baseret på dine seneste',
    logsLabel: 'logs',

    // AIRelevantPosts
    relevantForYou: 'Relevant for dig',
    seeAll: 'Se alle →',

    // WonderWeekCard
    wonderWeekActiveLabel: 'TIGERSPRING',
    wonderWeekActiveNow: 'AKTIV NU',
    nextLeapIn: 'Næste spring om',
    progress: 'Fremgang',
    weeksLeft: 'uge(r) tilbage',
    almostOver: 'Næsten forbi',
    approx: 'ca.',
    hideDetails: 'Skjul detaljer',
    seeSigns: 'Se tegn & tips',
    typicalSigns: 'Typiske tegn',
    tipsForYou: 'Tips til dig',
    readMoreWonderWeeks: 'Læs mere om tigerspring',
    getReadyLeap: 'Bliv klar – dit barn er snart klar til sit næste store spring 🌱',

    // Calendar
    calendarTitle: 'Kalender',
    eventCreated: 'Aftale oprettet',
    eventDeleted: 'Aftale slettet',
    fillTitleAndTime: 'Udfyld titel og starttidspunkt',
    noEventsToday: 'Ingen aftaler denne dag',
    addEvent: 'Tilføj',
    newEvent: 'Ny aftale',
    eventTitle: 'Titel *',
    eventStart: 'Start *',
    eventEnd: 'Slut (valgfrit)',
    eventDescription: 'Beskrivelse (valgfrit)',
    saveEvent: 'Gem aftale',
    calendarReminderNote: '📲 Du får besked dagen før og 30 min før aftalen',
    eventTitlePlaceholder: 'Fx lægebesøg, vaccination...',
    eventDescPlaceholder: 'Evt. adresse eller noter...',
    weekdaysShort: ['Man', 'Tir', 'Ons', 'Tor', 'Fre', 'Lør', 'Søn'],

    // Landing
    landingOpenApp: 'Åbn app →',
    landingLogIn: 'Log ind',
    landingBecomeMember: 'Bliv medlem',
    landingHero1Title1: 'Til dig, der er vågen,',
    landingHero1Title2: 'når resten af verden sover.',
    landingHero1P1: 'Der findes en hel særlig form for ensomhed i moderskabet. En ensomhed som kommer snigende om natten, når baby igen er vågen og resten af verden er stille;',
    landingHero1P1Bold: 'Natteensomhed.',
    landingHero1P2Bold: 'CLUB NO SLEEP',
    landingHero1P2: 'er en dansk app skabt til netop disse øjeblikke. For ingen skal føle sig alene i moderskabet.',
    landingAppStoreLabel: 'App Store',
    landingDownloadNow: 'Download now',
    landingIWantToLook: 'Jeg vil kigge →',
    landingFullAccess: 'FULD ADGANG',
    landingMembership: 'Medlemskab',
    landingPerMonth: '/ md.',
    landingFeature1: 'AI søvnrådgivning',
    landingFeature2: 'Tigerspring & udviklingsguide',
    landingFeature3: 'Chat med andre forældre',
    landingFeature4: 'Ekspert booking',
    landingFeature5: '100+ vidensartikler',
    landingFeature6: 'Fælles kalender med partner',
    landingFeature7: 'Notifikationer & milestene',
    landingGetStarted: 'Kom i Gang ✨',
    landingKlubTitle: 'Kom med i klubben',
    landingKlubP1: 'Vi har været der.',
    landingKlubP1b: 'Der hvor nætterne er svære, dagene er lange og ingen helt forstår, hvad du står i. Hvor far sover på sofaen og mor sover siddende. Hvor frygten for natten allerede starter i løbet af eftermiddagen.',
    landingKlubP1c: 'CLUB NO SLEEP er skabt til dig, som savner et sted at blive spejlet og finde andre, der er vågen sammen med dig.',
    landingKlubP2: 'Kom med i klubben. For din egen skyld, og for alle de mødre som føler sig alene netop nu. Sammen kan vi mindske ensomhed i moderskabet.',
    landingKlubSig: 'Kærligst og kram fra Sara & Nicolaj',
    landingFeaturesTitle: 'Dette finder du i appen',
    landingPartnerTitle1: 'Du skal ikke stå',
    landingPartnerTitle2: 'med det hele alene',
    landingPartnerP: 'Én konto inkluderer altid en gratis bruger mere, så du kan vælge at dele alt fra søvnlog, kalender og tigerspring med din partner. Sammen bliver det ofte lettere.',
    landingSharePartner: 'Del med partner',
    landingYou: '(dig)',
    landingPartner: '(partner)',
    landingManage: 'Administrer',
    landingActive: 'Aktiv',
    landingInvitePartner: 'Invitér partner',
    landingSharedCalendar: 'Fælles kalender',
    landingOsteopathEvent: 'Osteopat kl. 10:00',
    landingCafeEvent: 'Barselscafé kl. 14:00',
    landingFooterTagline: 'Din trygge havn som ny forælder — søvn, fællesskab og viden samlet ét sted.',
    landingLegal: 'Juridisk',
    landingTerms: 'Handelsbetingelser',
    landingPrivacy: 'Privatlivspolitik',
    landingGetTheApp: 'Hent appen',
    landingCopyright: '© 2025 Club No Sleep · Alle rettigheder forbeholdes',
    landingPreviewPaymentAlert: 'Betaling virker kun fra den publicerede app, ikke fra forhåndsvisningen.',

    // FeaturesList
    featPregnancyTitle: 'Graviditeten uge for uge',
    featPregnancyDesc: 'Modtag ugentlige opdateringer om baby, kroppen og alt hvad der ellers følger med graviditeten inklusiv et lille skriv til din partner samt kærlige forslag til "det lille næste skridt".',
    featMilestonesTitle: 'Milepæle',
    featMilestonesDesc: 'Bliv mindet om din babys milepæle og forevig de store øjeblikke med fine stickers og datoer, lige til at hente ned på din telefon.',
    featWonderWeeksTitle: 'Tigerspring',
    featWonderWeeksDesc: 'Få besked når din baby nærmer sig et udviklingsspring. Bliv klogere på dit barns udvikling og læs hvordan du bedst muligt hjælper dit barn, når verden bliver større.',
    featNightLightTitle: 'Et lys i mørket',
    featNightLightDesc: 'Se hvor mange andre mødre som er vågne om natten, præcis ligesom dig. Så føles stilheden lidt mindre ensom.',
    featCafesTitle: 'Babyvenlige caféer',
    featCafesDesc: 'Find hyggelige kaffesteder anbefalet af andre mødre, hvor der er plads til barnevogn, babylyde og krummer på gulvet.',
    featCalendarTitle: 'Kalender',
    featCalendarDesc: 'Hold styr på jordemodertider, lægebesøg, aktiviteter og andre vigtige datoer, og del kalenderen (og ansvaret) med en partner.',
    featSleepLogTitle: 'Søvnlog',
    featSleepLogDesc: 'Registrér babys nattesøvn, dagslure og opvågninger og modtag feedback fra AI søvnvejleder.',
    featCommunityTitle: 'Fællesskab',
    featCommunityDesc: 'Ræk ud til en mor, der sidder vågen, præcis ligesom dig. Måske begynder et venskab netop der, hvor natten ellers føles mest stille.',
    featChoicesTitle: 'Din app dine valg',
    featChoicesDesc: 'Tilpas din hjemmeskærm, vælg selv om du ønsker at invitere en partner (gratis), del kun det, du ønsker, og vælg det farvetema, der føles bedst for dig.',

    // AboutUs
    aboutUsSaved: 'Gemt',
    aboutUsEditLabel: 'Rediger',
    aboutUsSaveBtn: 'Gem',
    aboutUsCancel: 'Annuller',
    aboutUsFunFacts: 'fun facts om mig',
    aboutUsTitle: 'Mød familien',
    aboutUsClickToEdit: 'Rediger ved at klikke',
    aboutUsContactUs: 'Kontakt os',
    aboutUsWriteToUs: 'Skriv til os',
    aboutUsLoginToMessage: 'Log ind for at sende en besked til os.',

    // FamilyInvite
    familyInviteFar: 'Far',
    familyInviteFarmor: 'Farmor',
    familyInviteFarfar: 'Farfar',
    familyInviteMormor: 'Mormor',
    familyInviteMorfar: 'Morfar',
    familyInviteSoster: 'Søster',
    familyInviteBror: 'Bror',
    familyInviteVeninde: 'Veninde',
    familyInviteVen: 'Ven',
    familyInviteKnowledgeArticles: 'Viden & artikler',
    familyInviteNotifyWonderWeeks: 'Notifikationer om tigerspring',
    familyInviteNotifySleep: 'Notifikationer om søvnlog',
    familyInviteNotifyCalendar: 'Notifikationer om aftaler',
    familyInviteWonderWeeks: 'Tigerspring',
    familyInviteFillEmailAndTitle: 'Udfyld email og vælg en titel',
    familyInviteValidEmail: 'Indtast en gyldig email',
    familyInviteSentTo: 'Invitation sendt til',
    familyInviteSomethingWrong: 'Noget gik galt. Prøv igen.',
    familyInviteDeleted: 'Invitation slettet',
    familyInviteAccepted: 'Accepteret',
    familyInviteDeclined: 'Afvist',
    familyInvitePending: 'Afventer',
    familyInviteTitle: 'Deling & adgang',
    familyInviteIntro: 'Invitér et familiemedlem til at følge med — de får adgang til præcis det, du vælger, og kan modtage notifikationer om barnets milepæle.',
    familyInviteInviteMember: 'Invitér familiemedlem',
    familyInviteSentInvites: 'Sendte invitationer',
    familyInviteNoInvites: 'Ingen invitationer endnu',
    familyInviteEmailLabel: 'Email på familiemedlem',
    familyInviteEmailPlaceholder: 'fx farmor@gmail.com',
    familyInviteTitleLabel: 'Titel',
    familyInviteTitlePlaceholder: 'fx Farmor, Bedste, Tante Lise...',
    familyInviteWhatToShare: 'Hvad skal deles?',
    familyInviteSending: 'Sender…',
    familyInviteSendInvite: 'Send invitation',

    // MyData
    myDataPdfUploadedFor: 'PDF uploadet for',
    myDataTermsLower: 'handelsbetingelser',
    myDataPrivacyLower: 'privatlivspolitik',
    myDataExported: 'Data eksporteret',
    myDataAccountDeleted: 'Konto og data slettet',
    myDataChatDeleted: 'Chathistorik slettet',
    myDataLocationDeleted: 'Lokationsdata slettet',
    myDataExportTitle: 'Eksporter mine data',
    myDataExportDesc: 'Download alt data vi har gemt om dig',
    myDataExporting: 'Eksporterer...',
    myDataDownloadJson: 'Download data (JSON)',
    myDataDeleteChatTitle: 'Slet chathistorik',
    myDataDeleteChatDesc: 'Sletter alle dine sendte beskeder',
    myDataDeleting: 'Sletter...',
    myDataDeleteChatBtn: 'Slet chathistorik',
    myDataDeleteLocationTitle: 'Slet lokationsdata',
    myDataDeleteLocationDesc: 'Fjerner din gemt lokation og deaktiverer nærheds-funktionen',
    myDataDeleteLocationBtn: 'Slet lokationsdata',
    myDataDeleteAccountTitle: 'Slet min konto',
    myDataDeleteAccountDesc: 'Sletter al din data permanent — kan ikke fortrydes',
    myDataDeleteAccountBtn: 'Slet konto og al data',
    myDataGdprNote: 'I henhold til GDPR har du ret til at tilgå, rette og slette dine personoplysninger.',
    myDataLegalDocsAdmin: 'Juridiske dokumenter (Admin)',
    myDataUploadPdfDesc: 'Upload PDF for handelsbetingelser og privatlivspolitik',
    myDataViewCurrentPdf: 'Se nuværende PDF',
    myDataReplacePdf: 'Udskift PDF',
    myDataUploadPdf: 'Upload PDF',
    myDataAreYouSure: 'Er du sikker?',
    myDataConfirmDeleteAccount: 'Dette sletter din konto og al tilknyttet data permanent. Handlingen kan ikke fortrydes.',
    myDataConfirmDeleteChat: 'Dette sletter alle dine sendte beskeder permanent.',
    myDataConfirmDeleteLocation: 'Dette fjerner din gemte lokation og deaktiverer nærheds-funktionen.',
    myDataYesDelete: 'Ja, slet',

    // ExpertDetail
    expertDetailNotFound: 'Ekspert ikke fundet',
    expertDetailProfile: 'Ekspert profil',
    expertDetailSpecialties: 'Specialer',
    expertDetailAbout: 'Om',
    expertDetailAvailability: 'Tilgængelighed',
    expertDetailNoTimes: 'Ingen tider sat op',
    expertDetailConsultation: 'Konsultation',
    expertDetailPerHour: '/ time',
    expertDetailBookConsultation: 'Book konsultation',

    // Booking
    bookingConfirmedToast: 'Booking bekræftet!',
    bookingCreateError: 'Kunne ikke oprette booking',
    bookingStepOf: 'Trin',
    bookingOf3: 'af 3',
    bookingSelectDate: 'Vælg dato',
    bookingContinue: 'Fortsæt',
    bookingSelectTime: 'Vælg tidspunkt',
    bookingNoSlotsToday: 'Ingen ledige tider denne dag',
    bookingConfirmTitle: 'Bekræft booking',
    bookingNotesLabel: 'Noter til eksperten (valgfrit)',
    bookingNotesPlaceholder: 'Beskriv hvad du gerne vil tale om...',
    bookingTotal: 'Total',
    bookingConfirmBtn: 'Bekræft booking',

    // AskQuestion
    askQuestionCategoryGeneral: 'Generelt',
    askQuestionCategoryCare: 'Pleje',
    askQuestionCategoryEquipment: 'Udstyr',
    askQuestionCategoryHealth: 'Sundhed',
    askQuestionCategoryTraining: 'Træning',
    askQuestionCategoryOther: 'Andet',
    askQuestionCreated: 'Spørgsmål oprettet',
    askQuestionCreateError: 'Kunne ikke oprette spørgsmål',
    askQuestionFillAllFields: 'Udfyld venligst alle felter',
    askQuestionTitle: 'Stil et spørgsmål',
    askQuestionCategoryLabel: 'Kategori',
    askQuestionChooseCategory: 'Vælg kategori',
    askQuestionTitleLabel: 'Titel',
    askQuestionTitlePlaceholder: 'Hvad vil du gerne vide?',
    askQuestionContentLabel: 'Uddyb dit spørgsmål',
    askQuestionContentPlaceholder: 'Beskriv dit spørgsmål i detaljer...',
    askQuestionAiDisclaimerBold: 'Du chatter med en AI-assistent.',
    askQuestionAiDisclaimerRest: 'Den kan generere forkerte oplysninger og erstatter ikke professionel rådgivning fra læge eller sundhedspersonale.',
    askQuestionSendBtn: 'Send spørgsmål',

    // Chat
    chatYesterday: 'I går',
    chatNoAccess: 'Ingen adgang til denne samtale.',
    chatBack: 'Tilbage',
    chatReport: 'Indberetning',
    chatNoMessages: 'Ingen beskeder endnu',
    chatSayHi: 'Sig hej!',
    chatInputPlaceholder: 'Skriv en besked...',

    // SleepAdviceFeedback
    sleepAdviceFeedbackHelpful: 'Det hjalp mig!',
    sleepAdviceFeedbackHelpfulDesc: 'Godt råd, vil prøve det',
    sleepAdviceFeedbackAlreadyTried: 'Har allerede prøvet',
    sleepAdviceFeedbackAlreadyTriedDesc: 'Kender rådet, virker ikke for os',
    sleepAdviceFeedbackNotRelevant: 'Ikke relevant for mig',
    sleepAdviceFeedbackNotRelevantDesc: 'Passer ikke til vores situation',
    sleepAdviceFeedbackNotHelpful: 'Hjalp ikke',
    sleepAdviceFeedbackNotHelpfulDesc: 'Prøvede det, ingen effekt',
    sleepAdviceFeedbackThanks: 'Tak for din feedback!',
    sleepAdviceFeedbackError: 'Noget gik galt, prøv igen',
    sleepAdviceFeedbackNotFound: 'Forslaget blev ikke fundet.',
    sleepAdviceFeedbackGoToLog: 'Gå til søvnlog',
    sleepAdviceFeedbackYourAdvice: 'Dit søvnråd',
    sleepAdviceFeedbackBasedOn: 'Baseret på',
    sleepAdviceFeedbackThanksDesc: 'Din tilbagemelding hjælper os med at give bedre og mere personlige råd næste gang.',
    sleepAdviceFeedbackBackToLog: 'Tilbage til søvnlog',
    sleepAdviceFeedbackDidThisHelp: 'Hjalp dette råd dig?',
    sleepAdviceFeedbackNotePlaceholder: 'Valgfrit: skriv gerne mere om hvad der virker eller ikke virker for jer...',
    sleepAdviceFeedbackSendBtn: 'Send feedback',
  },

  en: {
    // Nav
    home: 'Home',
    menu: 'Menu',
    shop: 'Shop',
    blog: 'Blog',
    sleepLog: 'Sleep log',
    knowledge: 'Knowledge',
    community: 'Community',
    calendar: 'Calendar',
    profile: 'Profile',

    // Home
    goodDay: 'Good day, mom 🤍',
    dailyWord: "Today's word for you",
    fromBlog: 'From the blog',
    seeAll: 'See all →',
    affirmations: [
      "You are a wonderful mom — even on the days it doesn't feel that way. 🤍",
      "It's okay that the coffee is cold. You are warm and present, and that is enough.",
      "You don't need to do everything perfectly. You just need to do your best — and you are.",
      "Sleep deprivation is hard. The fact that you keep going is proof of your incredible strength.",
      "Your baby doesn't know what 'perfect' is. They only know they love you.",
      "Those who say motherhood is easy have never tried it. You've got this!",
      "Every little smile from your child is proof that you're doing it right.",
      "You are not alone. Thousands of moms are sitting right now feeling exactly the same.",
      "It's okay to need help. Asking for it is actually brave.",
      "Today you are enough. Tomorrow you are enough. Always you are enough.",
      "Your tears are not weakness — they are love that has overflowed.",
      "No handbook can prepare you for the love you feel. You are strong.",
      "You have done something incredible. You have created a human being. Remember that.",
      "Some days it's enough that everyone is alive and reasonably fed. 🙌",
      "You are your baby's favourite person in the whole world. Always.",
      "Even though you're tired, you are still there. That is love in its purest form.",
      "No mother is perfect. But you are the perfect mother for your child.",
      "A good mother is not one who never fails — but one who always tries again.",
      "Congratulations on surviving another night. You deserve a medal (and more coffee).",
      "Your love is the warmest place your child knows. 🧡",
      "Even the hard days shape you both into something stronger.",
      "You are more than 'just a mom'. You are an everyday hero.",
      "What you give your child today, they carry with them all their life.",
      "A barely-making-it day is still a day full of love.",
      "You handle more than you know. That is the most beautiful thing about you.",
      "Every hug, every feed, every sleep attempt — it counts.",
      "Motherhood is not a performance. It's a relationship. And yours is beautiful.",
      "You have not failed. You are in the middle of it.",
      "Tomorrow is a new chance. And you are already ready for it.",
      "You carry so much. But you carry it with love.",
    ],

    // Profile
    profileTitle: 'Profile',
    edit: 'Edit',
    editProfile: 'Edit profile',
    username: 'Username',
    displayName: 'Display name',
    city: 'City',
    childBirthdate: "Child's birthday",
    wonderWeekInfo: 'Used to calculate wonder weeks 🐯',
    saveChanges: 'Save changes',
    saving: 'Saving…',
    profileUpdated: 'Profile updated',
    favorites: 'Favorites',
    notifications: 'Notifications',
    questions: 'Questions',
    settings: 'Settings',
    help: 'Help',
    shareLocation: 'Share location',
    showAsVisible: 'Show me as visible',
    logOut: 'Log out',
    language: 'Language',
    chooseLanguage: 'Choose language',

    // Settings
    settingsTitle: 'Settings',
    password: 'Password',
    privacy: 'Privacy',
    theme: 'Theme',
    chooseTheme: 'Choose your preferred look',
    light: 'Light',
    dark: 'Dark',
    faq: 'Frequently asked questions',
    contactSupport: 'Contact support',
    deleteAccount: 'Delete account',
    blogAndArticles: 'Blog & Articles',
    changePassword: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    updatePassword: 'Update password',
    passwordMismatch: 'Passwords do not match',
    passwordUpdated: 'Password updated',
    deleteWarning: 'Are you sure? This action cannot be undone — all your data will be permanently deleted.',
    typeToConfirmDelete: 'Type DELETE to confirm',
    deleteConfirmWord: 'DELETE',
    deletePermanently: 'Delete my account permanently',
    faqQ1: 'How do I edit my profile?',
    faqA1: 'Go to your profile and tap "Edit".',
    faqQ2: 'How do I find a practitioner?',
    faqA2: 'Find a practitioner under the Community tab.',

    // Knowledge
    knowledgeTitle: 'Knowledge & Answers',
    searchPlaceholder: 'Search knowledge...',
    articles: 'Articles',
    noResults: 'No results for',
    noFaq: 'No FAQ yet',
    noQuestions: 'No questions yet',
    askQuestion: 'Ask a question',
    answered: 'Answered',
    open: 'Open',
    by: 'by',
    answers: 'answers',

    // Shop
    shopTitle: 'Shop',
    searchProducts: 'Search products...',
    noProducts: 'No products found',
    sortBy: 'Sort by',
    newest: 'Newest',
    priceLow: 'Price: Low to high',
    priceHigh: 'Price: High to low',
    filtersTitle: 'Filters & Sorting',
    outOfStock: 'Out of stock',
    catAll: 'All',
    catCare: 'Care',
    catAccessories: 'Accessories',
    catEquipment: 'Equipment',
    catBooks: 'Books',

    // Blog
    blogTitle: 'Search and find answers',
    searchBlog: 'Search posts...',
    noPosts: 'No posts found',
    allCategories: 'All',

    // Community
    nearMe: 'Near me',
    chats: 'Chats',
    practitioners: 'Practitioners',
    aboutUs: 'About us',
    onlyForMoms: 'Moms only',
    onlyForMomsDesc: 'The community feature is reserved for mom profiles. Our mission is to fight night loneliness among moms — a safe space just for them.',
    switchToMomProfile: 'Create a profile to get access.',
    location: 'Location',
    findNearby: 'Find people nearby',
    locationActive: 'Active',
    enableLocation: 'Enable',
    showMeVisible: 'Show me as visible to others',
    activeMomsInDenmark: 'Awake moms near you',
    activeNow: 'active now',
    visible: 'Visible',
    hidden: 'Hidden',
    you: 'You',
    othersActive: 'Others active',
    enableLocationToSee: 'Enable location to see who is nearby',
    noUsersNearby: 'No users nearby (20 km)',
    personWithin: 'person within 20 km',
    personsWithin: 'people within 20 km',
    noConversations: 'No conversations yet',
    startChatNearby: 'Start a chat with someone nearby',
    unknown: 'Unknown',
    findPractitioner: 'Find practitioner',
    showingInArea: 'Showing experts in your area',
    showingRecommended: 'Showing recommended practitioners',
    all: 'All',
    searchInMyArea: 'Search my area',
    noExpertsInArea: 'No experts found in your area',
    noExpertsAvailable: 'No experts available',
    showAllExperts: 'Show all experts',
    recommendedPractitioners: 'Recommended practitioners',
    locationConsentTitle: 'Location usage',
    locationConsentDesc: 'Enable location to discover nearby moms who are also awake. Your exact location is never shared with other users — only an approximate distance is shown (e.g. "2 km away").',
    locationConsentNote: 'Location is used solely to find nearby users. You can disable it at any time in settings.',
    noThanks: 'No thanks',
    activateLocation: 'Enable location',
    locationActivated: 'Location enabled',
    locationError: 'Could not get location',
    browserNoLocation: 'Your browser does not support location',

    // SleepLog
    sleepLogTitle: 'Sleep log',
    historyBtn: 'History',
    logTodayBtn: 'Log today',
    todayLog: "Today's log",
    nightSleep: 'Night sleep',
    nightWakings: 'Night wakings',
    naps: 'Naps',
    nap: 'Nap',
    howDidBabyFallAsleep: 'How did the baby fall asleep?',
    moodBeforeBed: 'Mood before bedtime',
    notes: 'Notes',
    notesPlaceholder: 'What happened today? Restless evening? New tooth?',
    addWaking: 'Add waking',
    addNap: 'Add nap',
    bedtime: 'Bedtime',
    fellAsleep: 'Fell asleep',
    wokeUp: 'Woke up',
    date: 'Date',
    ageMonths: 'Age (months)',
    agePlaceholder: 'e.g. 8',
    saveSleepLog: 'Save sleep log',
    saving: 'Saving...',
    sleepLogSaved: 'Sleep log saved ✓',
    getAiAdvice: 'Get AI sleep advice',
    updateAiAdvice: 'Update AI advice',
    updateAnalysis: 'Update analysis',
    aiAnalyzing: 'The AI expert is analysing your sleep data…',
    aiErrorMsg: "Couldn't fetch analysis right now. Try again in a moment — you're doing great!",
    aiErrorTitle: '💛 A loving note',
    noLogsYet: 'No logs yet',
    bedAt: 'Bed',
    wakings: 'waking',
    wakingsPlural: 'wakings',
    felAsleepIn: 'Settling time:',
    nightSleepDuration: 'Night sleep:',
    nightNap: 'night sleep',
    napTotal: 'naps',
    sleepMethodSelf: 'Self',
    sleepMethodNursing: 'Nursing',
    sleepMethodBottle: 'Bottle',
    sleepMethodRocking: 'Rocking',
    sleepMethodPram: 'Pram',
    sleepMethodParent: 'With parent',
    moodFresh: 'Fresh',
    moodLittleTired: 'A little tired',
    moodVeryTired: 'Very tired',
    moodOvertired: 'Overtired',
    wakingMethodNursing: 'Nursing',
    wakingMethodBottle: 'Bottle',
    wakingMethodRocking: 'Rocking',
    wakingMethodSing: 'Sung to sleep',
    wakingMethodPram: 'Pram',
    wakingMethodSelf: 'Self-settled',

    // AIChat
    aiChatTitle: 'Baby & Sleep Expert',
    aiOnline: 'AI assistant · Online',
    aiGreeting: 'Hi! I am here for you 🤍',
    aiSubtitle: 'Expert in baby sleep, breastfeeding and child development. Ask me anything!',
    aiSuggestion1: 'How do I help my baby sleep better?',
    aiSuggestion2: 'What is sleep regression?',
    aiSuggestion3: 'My baby only sleeps 20 min at a time — help!',
    aiPlaceholder: 'Write your question…',
    aiDisclaimer: 'The AI assistant can make mistakes and does not replace medical advice.',
    backLabel: 'Go back',
    sendLabel: 'Send message',

    // Community / shared
    version: 'Version 1.0.0',
    v1: 'v1.0',

    // Profile extra
    momProfileLabel: 'Mom profile · Community access',
    dadProfileLabel: 'Dad profile · Sleep log',
    genderLabel: 'Gender',
    female: 'Female',
    male: 'Male',
    genderLocked: 'Gender cannot be changed after selection',
    myDataPrivacy: 'My data & privacy',
    helpAndContact: 'Help & contact',
    aboutApp: 'About the app',
    writeToUs: 'Contact us',
    callUs: 'Call us',

    // Settings extra
    loading: 'Loading...',
    noFaqAvailable: 'No FAQ available yet.',
    noSupportInfo: 'No support info available yet.',
    noPrivacyPolicy: 'No privacy policy available yet.',

    // Shop extra
    categoryLabel: 'Category',
    productsLabel: 'products',
    categoriesTitle: 'Categories',
    filtersAndSorting: 'Filters & Sorting',

    // Onboarding
    whoAreYou: 'Who are you?',
    chooseRoleSubtitle: 'Choose your role in the family',
    welcomeTitle: 'Welcome to LALATOTO',
    welcomeSubtitle: 'Create your profile and accept the terms',
    whereDoYouLive: 'Where do you live?',
    findNearbyMoms: 'Find moms near you',
    aboutYourChild: 'About your child',
    calculateWonderWeeksSubtitle: 'So we can calculate wonder weeks for you',
    lalatotoBuiltForFamily: 'LALATOTO is built for the whole family. Choose your role so we can tailor the experience for you.',
    mom: 'Mom',
    dad: 'Dad',
    momDesc: 'Community, sleep log & more',
    dadDesc: 'Sleep log & knowledge',
    nightLonelinessTitle: '🌙 Night loneliness',
    nightLonelinessDesc: 'Our night loneliness space is a safe space exclusively for moms — for those awake at night who need to know they are not alone.',
    yourName: 'Your name',
    namePlaceholder: 'Name...',
    usernameLabel: 'Username',
    usernameHint: 'Only letters, numbers and underscores',
    uploadingLabel: 'Uploading...',
    addProfilePic: 'Add profile picture (optional)',
    iAcceptTerms: 'I accept the',
    termsLinkLabel: 'terms of service',
    privacyLinkLabel: 'privacy policy',
    termsTitle: 'Terms of service',
    privacyTitle: 'Privacy policy',
    yourCity: 'Your city',
    cityDesc: 'We use your city to show you other moms nearby — completely optional.',
    cityPlaceholder: 'e.g. Copenhagen, Aarhus...',
    childBirthdateLabel: "Child's birth date",
    orLabel: 'or',
    dueDateLabel: 'Due date (if not born yet)',
    skip: 'Skip',
    back: 'Back',
    getStarted: 'Get started 🎉',
    next: 'Next',
    errorChooseRole: 'Choose whether you are a mom or dad',
    errorEnterName: 'Enter your name',
    errorChooseUsername: 'Choose a username',
    errorUsernameMin: 'At least 3 characters',
    errorAcceptTerms: 'You must accept the terms of service',
    errorAcceptPrivacy: 'You must accept the privacy policy',
    usernameOnlyChars: 'Only letters, numbers and underscores',

    // ChildDevelopmentCard
    dueIn: 'Due in',
    yourChildIs: 'Your child is',
    old: 'old',
    untilDue: 'until due date',
    weekSingular: 'week',
    weekPlural: 'weeks',
    daySingular: 'day',
    dayPlural: 'days',
    monthsShort: 'mo',
    hoursShort: 'h',
    minutesShort: 'm',

    // SleepSummaryCard
    sleepLastNight: 'Sleep last night',
    wakingSingular: 'waking',
    wakingPlural: 'wakings',
    logSleepCta: 'Log sleep →',

    // UpcomingEventCard
    nextAppointment: 'Next appointment',
    today: 'Today',
    tomorrow: 'Tomorrow',
    addAppointmentCta: 'Add appointment →',

    // SleepAdviceCard
    sleepAdviceTitle: 'Sleep advice from the expert',
    seeSleepLog: 'See sleep log →',
    basedOnLogs: 'Based on your last',
    logsLabel: 'logs',

    // AIRelevantPosts
    relevantForYou: 'Relevant for you',
    seeAll: 'See all →',

    // WonderWeekCard
    wonderWeekActiveLabel: 'WONDER WEEK',
    wonderWeekActiveNow: 'ACTIVE NOW',
    nextLeapIn: 'Next leap in',
    progress: 'Progress',
    weeksLeft: 'week(s) left',
    almostOver: 'Almost over',
    approx: 'approx.',
    hideDetails: 'Hide details',
    seeSigns: 'See signs & tips',
    typicalSigns: 'Typical signs',
    tipsForYou: 'Tips for you',
    readMoreWonderWeeks: 'Read more about wonder weeks',
    getReadyLeap: 'Get ready – your child is almost ready for their next big leap 🌱',

    // Calendar
    calendarTitle: 'Calendar',
    eventCreated: 'Appointment created',
    eventDeleted: 'Appointment deleted',
    fillTitleAndTime: 'Fill in title and start time',
    noEventsToday: 'No appointments today',
    addEvent: 'Add',
    newEvent: 'New appointment',
    eventTitle: 'Title *',
    eventStart: 'Start *',
    eventEnd: 'End (optional)',
    eventDescription: 'Description (optional)',
    saveEvent: 'Save appointment',
    calendarReminderNote: '📲 You will be notified the day before and 30 min before the appointment',
    eventTitlePlaceholder: 'e.g. doctor visit, vaccination...',
    eventDescPlaceholder: 'Optional address or notes...',
    weekdaysShort: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],

    // AboutUs
    aboutUsSaved: 'Saved',
    aboutUsEditLabel: 'Edit',
    aboutUsSaveBtn: 'Save',
    aboutUsCancel: 'Cancel',
    aboutUsFunFacts: 'fun facts about me',
    aboutUsTitle: 'Meet the family',
    aboutUsClickToEdit: 'Click to edit',
    aboutUsContactUs: 'Contact us',
    aboutUsWriteToUs: 'Write to us',
    aboutUsLoginToMessage: 'Log in to send us a message.',

    // FamilyInvite
    familyInviteFar: 'Dad',
    familyInviteFarmor: 'Grandma (paternal)',
    familyInviteFarfar: 'Grandpa (paternal)',
    familyInviteMormor: 'Grandma (maternal)',
    familyInviteMorfar: 'Grandpa (maternal)',
    familyInviteSoster: 'Sister',
    familyInviteBror: 'Brother',
    familyInviteVeninde: 'Friend (f)',
    familyInviteVen: 'Friend',
    familyInviteKnowledgeArticles: 'Knowledge & articles',
    familyInviteNotifyWonderWeeks: 'Wonder week notifications',
    familyInviteNotifySleep: 'Sleep log notifications',
    familyInviteNotifyCalendar: 'Appointment notifications',
    familyInviteWonderWeeks: 'Wonder weeks',
    familyInviteFillEmailAndTitle: 'Fill in email and choose a title',
    familyInviteValidEmail: 'Enter a valid email',
    familyInviteSentTo: 'Invitation sent to',
    familyInviteSomethingWrong: 'Something went wrong. Please try again.',
    familyInviteDeleted: 'Invitation deleted',
    familyInviteAccepted: 'Accepted',
    familyInviteDeclined: 'Declined',
    familyInvitePending: 'Pending',
    familyInviteTitle: 'Sharing & access',
    familyInviteIntro: "Invite a family member to stay in the loop — they get access to exactly what you choose, and can receive notifications about your child's milestones.",
    familyInviteInviteMember: 'Invite family member',
    familyInviteSentInvites: 'Sent invitations',
    familyInviteNoInvites: 'No invitations yet',
    familyInviteEmailLabel: "Family member's email",
    familyInviteEmailPlaceholder: 'e.g. grandma@gmail.com',
    familyInviteTitleLabel: 'Title',
    familyInviteTitlePlaceholder: 'e.g. Grandma, Auntie Lise...',
    familyInviteWhatToShare: 'What should be shared?',
    familyInviteSending: 'Sending…',
    familyInviteSendInvite: 'Send invitation',

    // MyData
    myDataPdfUploadedFor: 'PDF uploaded for',
    myDataTermsLower: 'terms of service',
    myDataPrivacyLower: 'privacy policy',
    myDataExported: 'Data exported',
    myDataAccountDeleted: 'Account and data deleted',
    myDataChatDeleted: 'Chat history deleted',
    myDataLocationDeleted: 'Location data deleted',
    myDataExportTitle: 'Export my data',
    myDataExportDesc: 'Download all the data we have stored about you',
    myDataExporting: 'Exporting...',
    myDataDownloadJson: 'Download data (JSON)',
    myDataDeleteChatTitle: 'Delete chat history',
    myDataDeleteChatDesc: 'Deletes all the messages you have sent',
    myDataDeleting: 'Deleting...',
    myDataDeleteChatBtn: 'Delete chat history',
    myDataDeleteLocationTitle: 'Delete location data',
    myDataDeleteLocationDesc: 'Removes your stored location and disables the proximity feature',
    myDataDeleteLocationBtn: 'Delete location data',
    myDataDeleteAccountTitle: 'Delete my account',
    myDataDeleteAccountDesc: 'Permanently deletes all your data — cannot be undone',
    myDataDeleteAccountBtn: 'Delete account and all data',
    myDataGdprNote: 'Under GDPR you have the right to access, correct and delete your personal data.',
    myDataLegalDocsAdmin: 'Legal documents (Admin)',
    myDataUploadPdfDesc: 'Upload PDF for terms of service and privacy policy',
    myDataViewCurrentPdf: 'View current PDF',
    myDataReplacePdf: 'Replace PDF',
    myDataUploadPdf: 'Upload PDF',
    myDataAreYouSure: 'Are you sure?',
    myDataConfirmDeleteAccount: 'This permanently deletes your account and all associated data. This action cannot be undone.',
    myDataConfirmDeleteChat: 'This permanently deletes all the messages you have sent.',
    myDataConfirmDeleteLocation: 'This removes your stored location and disables the proximity feature.',
    myDataYesDelete: 'Yes, delete',

    // ExpertDetail
    expertDetailNotFound: 'Expert not found',
    expertDetailProfile: 'Expert profile',
    expertDetailSpecialties: 'Specialties',
    expertDetailAbout: 'About',
    expertDetailAvailability: 'Availability',
    expertDetailNoTimes: 'No times set up',
    expertDetailConsultation: 'Consultation',
    expertDetailPerHour: '/ hour',
    expertDetailBookConsultation: 'Book consultation',

    // Booking
    bookingConfirmedToast: 'Booking confirmed!',
    bookingCreateError: 'Could not create booking',
    bookingStepOf: 'Step',
    bookingOf3: 'of 3',
    bookingSelectDate: 'Select date',
    bookingContinue: 'Continue',
    bookingSelectTime: 'Select time',
    bookingNoSlotsToday: 'No available times this day',
    bookingConfirmTitle: 'Confirm booking',
    bookingNotesLabel: 'Notes for the expert (optional)',
    bookingNotesPlaceholder: 'Describe what you would like to talk about...',
    bookingTotal: 'Total',
    bookingConfirmBtn: 'Confirm booking',

    // AskQuestion
    askQuestionCategoryGeneral: 'General',
    askQuestionCategoryCare: 'Care',
    askQuestionCategoryEquipment: 'Equipment',
    askQuestionCategoryHealth: 'Health',
    askQuestionCategoryTraining: 'Sleep training',
    askQuestionCategoryOther: 'Other',
    askQuestionCreated: 'Question posted',
    askQuestionCreateError: 'Could not post question',
    askQuestionFillAllFields: 'Please fill in all fields',
    askQuestionTitle: 'Ask a question',
    askQuestionCategoryLabel: 'Category',
    askQuestionChooseCategory: 'Choose category',
    askQuestionTitleLabel: 'Title',
    askQuestionTitlePlaceholder: 'What would you like to know?',
    askQuestionContentLabel: 'Elaborate on your question',
    askQuestionContentPlaceholder: 'Describe your question in detail...',
    askQuestionAiDisclaimerBold: "You're chatting with an AI assistant.",
    askQuestionAiDisclaimerRest: 'It can generate incorrect information and does not replace professional advice from a doctor or healthcare provider.',
    askQuestionSendBtn: 'Send question',

    // Landing
    landingOpenApp: 'Open app →',
    landingLogIn: 'Log in',
    landingBecomeMember: 'Become a member',
    landingHero1Title1: 'For you, who are awake,',
    landingHero1Title2: 'when the rest of the world sleeps.',
    landingHero1P1: "There's a very particular kind of loneliness in motherhood. One that creeps in at night, when baby is awake again and the rest of the world is quiet;",
    landingHero1P1Bold: 'Night-time loneliness.',
    landingHero1P2Bold: 'CLUB NO SLEEP',
    landingHero1P2: 'is a Danish app created for exactly these moments. Because no one should feel alone in motherhood.',
    landingAppStoreLabel: 'App Store',
    landingDownloadNow: 'Download now',
    landingIWantToLook: 'I want to take a look →',
    landingFullAccess: 'FULL ACCESS',
    landingMembership: 'Membership',
    landingPerMonth: '/ mo.',
    landingFeature1: 'AI sleep advice',
    landingFeature2: 'Wonder weeks & development guide',
    landingFeature3: 'Chat with other parents',
    landingFeature4: 'Expert booking',
    landingFeature5: '100+ knowledge articles',
    landingFeature6: 'Shared calendar with partner',
    landingFeature7: 'Notifications & milestones',
    landingGetStarted: 'Get started ✨',
    landingKlubTitle: 'Join the club',
    landingKlubP1: "We've been there.",
    landingKlubP1b: "Where the nights are hard, the days are long, and no one quite understands what you're going through. Where dad sleeps on the couch and mom sleeps sitting up. Where the dread of the night already starts in the afternoon.",
    landingKlubP1c: 'CLUB NO SLEEP was created for you, who longs for a place to feel seen and to find others who are awake right alongside you.',
    landingKlubP2: 'Join the club. For your own sake, and for all the mothers who feel alone right now. Together we can ease the loneliness of motherhood.',
    landingKlubSig: 'With love and hugs, Sara & Nicolaj',
    landingFeaturesTitle: "What you'll find in the app",
    landingPartnerTitle1: "You don't have to carry",
    landingPartnerTitle2: 'it all alone',
    landingPartnerP: 'One account always includes a second user for free, so you can choose to share everything from sleep log, calendar and wonder weeks with your partner. Together it often gets easier.',
    landingSharePartner: 'Share with partner',
    landingYou: '(you)',
    landingPartner: '(partner)',
    landingManage: 'Manage',
    landingActive: 'Active',
    landingInvitePartner: 'Invite partner',
    landingSharedCalendar: 'Shared calendar',
    landingOsteopathEvent: 'Osteopath at 10:00 AM',
    landingCafeEvent: 'Postpartum café at 2:00 PM',
    landingFooterTagline: 'Your safe haven as a new parent — sleep, community and knowledge all in one place.',
    landingLegal: 'Legal',
    landingTerms: 'Terms of service',
    landingPrivacy: 'Privacy policy',
    landingGetTheApp: 'Get the app',
    landingCopyright: '© 2025 Club No Sleep · All rights reserved',
    landingPreviewPaymentAlert: 'Payment only works from the published app, not from the preview.',

    // FeaturesList
    featPregnancyTitle: 'Pregnancy week by week',
    featPregnancyDesc: 'Get weekly updates on baby, your body and everything else that comes with pregnancy, including a short note for your partner and loving suggestions for "the next small step".',
    featMilestonesTitle: 'Milestones',
    featMilestonesDesc: "Get reminded of your baby's milestones and capture the big moments with cute stickers and dates, ready to download to your phone.",
    featWonderWeeksTitle: 'Wonder weeks',
    featWonderWeeksDesc: "Get notified when your baby is approaching a developmental leap. Learn more about your child's development and how to best help them as their world grows bigger.",
    featNightLightTitle: 'A light in the dark',
    featNightLightDesc: 'See how many other mothers are awake at night, just like you. It makes the silence feel a little less lonely.',
    featCafesTitle: 'Baby-friendly cafés',
    featCafesDesc: 'Find cosy cafés recommended by other mothers, with room for strollers, baby noises and crumbs on the floor.',
    featCalendarTitle: 'Calendar',
    featCalendarDesc: 'Keep track of midwife appointments, doctor visits, activities and other important dates, and share the calendar (and the responsibility) with a partner.',
    featSleepLogTitle: 'Sleep log',
    featSleepLogDesc: "Log your baby's night sleep, naps and wake-ups and get feedback from the AI sleep advisor.",
    featCommunityTitle: 'Community',
    featCommunityDesc: 'Reach out to a mother who is awake right now, just like you. Maybe a friendship begins right there, where the night otherwise feels quietest.',
    featChoicesTitle: 'Your app, your choices',
    featChoicesDesc: 'Customize your home screen, choose whether to invite a partner (free), share only what you want, and pick the colour theme that feels best for you.',

    // Chat
    chatYesterday: 'Yesterday',
    chatNoAccess: "You don't have access to this conversation.",
    chatBack: 'Back',
    chatReport: 'Report',
    chatNoMessages: 'No messages yet',
    chatSayHi: 'Say hi!',
    chatInputPlaceholder: 'Write a message...',
  },
};

const LanguageContext = createContext({
  lang: 'da',
  t: translations.da,
  setLang: () => {},
});

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    return localStorage.getItem('app-language') || 'da';
  });

  const setLang = (newLang) => {
    localStorage.setItem('app-language', newLang);
    setLangState(newLang);
  };

  const t = translations[lang] || translations.da;

  return (
    <LanguageContext.Provider value={{ lang, t, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}