import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  da: {
    // Nav
    home: 'Hjem',
    menu: 'Menu',
    shop: 'Shop',
    blog: 'Læs & Lær',
    sleepLog: 'Søvnlog',
    knowledge: 'Viden',
    community: 'Community',
    calendar: 'Kalender',
    profile: 'Profil',
    natteensomhed: 'Natteensomhed',

    // Home
    goodDay: 'God dag, mor 🤍',
    dailyWord: 'Dagens ord til dig',
    fromBlog: 'Fra bloggen',
    seeAll: 'Se alle →',
    affirmations: [
      "Du er en vidunderlig mor — selv på dage hvor det ikke føles sådan. 🤍",
      "Det er okay at kaffen er kold. Du er varm og til stede, og det er nok.",
      "Du behøver ikke at gøre alt perfekt. Du behøver bare at gøre dit bedste — og det gør du.",
      "Søvnmangel er hårdt. At du holder ved er bevis på din utrolige styrke.",
      "Dit barn ved ikke hvad 'perfekt' betyder. De ved bare at de elsker dig.",
      "De der siger at moderskab er nemt, har aldrig prøvet det. Du klarer dette!",
      "Ethvert lille smil fra dit barn er bevis på at du gør det rigtigt.",
      "Du er ikke alene. Tusinder af mødre sidder lige nu og føler præcis det samme.",
      "Det er okay at have brug for hjælp. At bede om den er faktisk modig.",
      "I dag er du nok. I morgen er du nok. Altid er du nok.",
      "Dine tårer er ikke svaghed — de er kærlighed der er overløbet.",
      "Ingen håndbok kan forberede dig på den kærlighed du føler. Du er stærk.",
      "Du har gjort noget utroligt. Du har skabt et menneske. Husk det.",
      "Nogle dage er det nok at alle lever og er relativt mætte. 🙌",
      "Du er dit babys yndlingsperson i hele verden. Altid.",
      "Selvom du er træt, er du stadig der. Det er kærlighed i sin reneste form.",
      "Ingen mor er perfekt. Men du er den perfekte mor for dit barn.",
      "En god mor er ikke en der aldrig fejler — men en der altid prøver igen.",
      "Tillykke fordi du overlevede endnu en nat. Du fortjener en medalje (og mere kaffe).",
      "Din kærlighed er det varmeste sted dit barn kender. 🧡",
      "Selv de svære dage formes jer begge til noget stærkere.",
      "Du er meget mere end 'bare en mor'. Du er en hverdagshelt.",
      "Det du giver dit barn i dag, bærer de med sig hele deres liv.",
      "En dag hvor du næppe klarer det, er stadig en dag fuld af kærlighed.",
      "Du håndterer mere end du ved. Det er det smukkeste ved dig.",
      "Ethvert kram, hver amning, hvert søvnforsøg — det tæller.",
      "Moderskab er ikke en præstation. Det er et forhold. Og dit er smukt.",
      "Du har ikke fejlet. Du er midt i det.",
      "I morgen er en ny chance. Og du er allerede klar til det.",
      "Du bærer så meget. Men du bærer det med kærlighed.",
    ],

    // Profile
    profileTitle: 'Profil',
    edit: 'Rediger',
    editProfile: 'Rediger profil',
    username: 'Brugernavn',
    displayName: 'Visningsnavn',
    city: 'By',
    childBirthdate: 'Barnets fødselsdag',
    wonderWeekInfo: 'Bruges til beregning af tigerspring 🐯',
    saveChanges: 'Gem ændringer',
    saving: 'Gemmer…',
    profileUpdated: 'Profil opdateret',
    favorites: 'Favoritter',
    notifications: 'Notifikationer',
    questions: 'Spørgsmål',
    settings: 'Indstillinger',
    help: 'Hjælp',
    shareLocation: 'Del lokation',
    showAsVisible: 'Vis mig som synlig',
    logOut: 'Log ud',
    language: 'Sprog',
    chooseLanguage: 'Vælg sprog',

    // Settings
    settingsTitle: 'Indstillinger',
    password: 'Adgangskode',
    privacy: 'Privatliv',
    theme: 'Tema',
    chooseTheme: 'Vælg dit foretrukne look',
    light: 'Lys',
    dark: 'Mørk',
    faq: 'Ofte stillede spørgsmål',
    contactSupport: 'Kontakt support',
    deleteAccount: 'Slet konto',
    blogAndArticles: 'Blog & Artikler',
    changePassword: 'Skift adgangskode',
    currentPassword: 'Nuværende adgangskode',
    newPassword: 'Ny adgangskode',
    confirmPassword: 'Bekræft ny adgangskode',
    updatePassword: 'Opdater adgangskode',
    passwordMismatch: 'Adgangskoderne matcher ikke',
    passwordUpdated: 'Adgangskode opdateret',
    deleteWarning: 'Er du sikker? Denne handling kan ikke fortrydes — al din data slettes permanent.',
    typeToConfirmDelete: 'Skriv SLET for at bekræfte',
    deleteConfirmWord: 'SLET',
    deletePermanently: 'Slet min konto permanent',
    faqQ1: 'Hvordan ændrer jeg min profil?',
    faqA1: 'Gå til din profil og tryk på "Rediger".',
    faqQ2: 'Hvordan finder jeg en behandler?',
    faqA2: 'Find en behandler under Community-fanen.',

    // Knowledge
    knowledgeTitle: 'Viden & Svar',
    searchPlaceholder: 'Søg i viden...',
    articles: 'Artikler',
    noResults: 'Ingen resultater for',
    noFaq: 'Ingen FAQ endnu',
    noQuestions: 'Ingen spørgsmål endnu',
    askQuestion: 'Stil et spørgsmål',
    answered: 'Besvaret',
    open: 'Åben',
    by: 'af',
    answers: 'svar',

    // Shop
    shopTitle: 'Shop',
    searchProducts: 'Søg produkter...',
    noProducts: 'Ingen produkter fundet',
    sortBy: 'Sorter efter',
    newest: 'Nyeste',
    priceLow: 'Pris: Lav til høj',
    priceHigh: 'Pris: Høj til lav',
    filtersTitle: 'Filtre & Sortering',
    outOfStock: 'Udsolgt',
    catAll: 'Alle',
    catCare: 'Pleje',
    catAccessories: 'Tilbehør',
    catEquipment: 'Udstyr',
    catBooks: 'Bøger',

    // Blog
    blogTitle: 'Læs & Lær',
    searchBlog: 'Søg indlæg...',
    noPosts: 'Ingen indlæg fundet',
    allCategories: 'Alle',

    // Community
    nearMe: 'Nær mig',
    chats: 'Chats',
    practitioners: 'Behandlere',
    aboutUs: 'Om os',
    onlyForMoms: 'Kun for mødre',
    onlyForMomsDesc: 'Natteensomhed-funktionen er forbeholdt mor-profiler. Vores mission er at bekæmpe natteensomhed blandt mødre — et trygt rum kun for dem.',
    switchToMomProfile: 'Skift til din mor-profil for at få adgang.',
    location: 'Lokation',
    findNearby: 'Find folk i nærheden',
    locationActive: 'Aktiv',
    enableLocation: 'Aktiver',
    showMeVisible: 'Vis mig som synlig for andre',
    activeMomsInDenmark: 'Aktive mødre i Danmark',
    activeNow: 'aktive nu',
    visible: 'Synlig',
    hidden: 'Skjult',
    you: 'Dig',
    othersActive: 'Andre aktive',
    enableLocationToSee: 'Aktiver lokation for at se hvem der er i nærheden',
    noUsersNearby: 'Ingen brugere i nærheden (20 km)',
    personWithin: 'person indenfor 20 km',
    personsWithin: 'personer indenfor 20 km',
    noConversations: 'Ingen samtaler endnu',
    startChatNearby: 'Start en chat med nogen i nærheden',
    unknown: 'Ukendt',
    findPractitioner: 'Find behandler',
    showingInArea: 'Viser eksperter i dit område',
    showingRecommended: 'Viser anbefalede behandlere',
    all: 'Alle',
    searchInMyArea: 'Søg i mit område',
    noExpertsInArea: 'Ingen eksperter fundet i dit område',
    noExpertsAvailable: 'Ingen eksperter tilgængelige',
    showAllExperts: 'Vis alle eksperter',
    recommendedPractitioners: 'Anbefalede behandlere',
    locationConsentTitle: 'Brug af lokation',
    locationConsentDesc: 'Aktiver lokation for at opdage mødre i nærheden, der også er vågne. Din præcise lokation deles aldrig med andre brugere — kun en omtrentlig afstand vises (fx "2 km væk").',
    locationConsentNote: 'Lokation bruges udelukkende til at finde brugere i nærheden. Du kan til enhver tid deaktivere det igen under indstillinger.',
    noThanks: 'Nej tak',
    activateLocation: 'Aktiver lokation',
    locationActivated: 'Lokation aktiveret',
    locationError: 'Kunne ikke hente lokation',
    browserNoLocation: 'Din browser understøtter ikke lokation',

    // SleepLog
    sleepLogTitle: 'Søvnlog',
    historyBtn: 'Historik',
    logTodayBtn: 'Log i dag',
    todayLog: 'Dagens log',
    nightSleep: 'Natsøvn',
    nightWakings: 'Natlige opvågninger',
    naps: 'Lure',
    nap: 'Lur',
    howDidBabyFallAsleep: 'Hvordan faldt barnet i søvn?',
    moodBeforeBed: 'Humør før sengetid',
    notes: 'Noter',
    notesPlaceholder: 'Hvad skete der i dag? Urolig aften? Ny tand?',
    addWaking: 'Tilføj opvågning',
    addNap: 'Tilføj lur',
    bedtime: 'Sengetid',
    fellAsleep: 'Faldt i søvn',
    wokeUp: 'Vågnede',
    date: 'Dato',
    ageMonths: 'Alder (måneder)',
    agePlaceholder: 'f.eks. 8',
    saveSleepLog: 'Gem søvnlog',
    saving: 'Gemmer...',
    sleepLogSaved: 'Søvnlog gemt ✓',
    getAiAdvice: 'Få AI-råd til søvnen',
    updateAiAdvice: 'Opdater AI-råd',
    updateAnalysis: 'Opdater analyse',
    aiAnalyzing: 'AI-eksperten analyserer jeres søvndata…',
    aiErrorMsg: 'Kunne ikke hente analyse lige nu. Prøv igen om lidt — du gør det godt!',
    aiErrorTitle: '💛 En kærlig hilsen',
    noLogsYet: 'Ingen logs endnu',
    bedAt: 'Seng',
    wakings: 'opvågning',
    wakingsPlural: 'opvågninger',
    felAsleepIn: 'Sovnet:',
    nightNap: 'natsøvn',
    napTotal: 'lure',
    sleepMethodSelf: 'Selv',
    sleepMethodNursing: 'Amning',
    sleepMethodBottle: 'Flaske',
    sleepMethodRocking: 'Vugning',
    sleepMethodPram: 'Barnevogn',
    sleepMethodParent: 'Med forælder',
    moodFresh: 'Frisk',
    moodLittleTired: 'Lidt træt',
    moodVeryTired: 'Meget træt',
    moodOvertired: 'Overtræt',
    wakingMethodNursing: 'Amning',
    wakingMethodBottle: 'Flaske',
    wakingMethodRocking: 'Vugning',
    wakingMethodSing: 'Sig i søvn',
    wakingMethodPram: 'Barnevogn',
    wakingMethodSelf: 'Sov selv',

    // AIChat
    aiChatTitle: 'Baby & Søvn Ekspert',
    aiOnline: 'AI-assistent · Online',
    aiGreeting: 'Hej! Jeg er her for dig 🤍',
    aiSubtitle: 'Ekspert i babysøvn, amning og barnets udvikling. Spørg mig om alt!',
    aiSuggestion1: 'Hvordan hjælper jeg min baby til at sove bedre?',
    aiSuggestion2: 'Hvad er søvnregression?',
    aiSuggestion3: 'Min baby sover kun 20 min ad gangen — hjælp!',
    aiPlaceholder: 'Skriv dit spørgsmål…',
    aiDisclaimer: 'AI-assistenten kan lave fejl og erstatter ikke lægefaglig rådgivning.',
    backLabel: 'Gå tilbage',
    sendLabel: 'Send besked',

    // Community / shared
    version: 'Version 1.0.0',
    v1: 'v1.0',

    // Profile extra
    momProfileLabel: 'Mor-profil · Adgang til community',
    dadProfileLabel: 'Far-profil · Søvnlog',
    genderLabel: 'Køn',
    female: 'Kvinde',
    male: 'Mand',
    genderLocked: 'Køn kan ikke ændres efter valg',
    myDataPrivacy: 'Mine data & privatliv',
    helpAndContact: 'Hjælp & kontakt',
    aboutApp: 'Om appen',
    writeToUs: 'Skriv til os',
    callUs: 'Ring til os',

    // Settings extra
    loading: 'Indlæser...',
    noFaqAvailable: 'Ingen FAQ tilgængelig endnu.',
    noSupportInfo: 'Ingen supportinfo tilgængelig endnu.',
    noPrivacyPolicy: 'Ingen privatlivspolitik tilgængelig endnu.',

    // Shop extra
    categoryLabel: 'Kategori',
    productsLabel: 'produkter',
    categoriesTitle: 'Kategorier',
    filtersAndSorting: 'Filtre & Sortering',

    // Onboarding
    whoAreYou: 'Hvem er du?',
    chooseRoleSubtitle: 'Vælg din rolle i familien',
    welcomeTitle: 'Velkommen til LALATOTO',
    welcomeSubtitle: 'Opret din profil og acceptér betingelserne',
    whereDoYouLive: 'Hvor bor du?',
    findNearbyMoms: 'Find mødre i nærheden af dig',
    aboutYourChild: 'Om dit barn',
    calculateWonderWeeksSubtitle: 'Så kan vi beregne tigerspring for dig',
    lalatotoBuiltForFamily: 'LALATOTO er bygget til hele familien. Vælg din rolle, så vi kan tilpasse oplevelsen til dig.',
    mom: 'Mor',
    dad: 'Far',
    momDesc: 'Community, søvnlog & mere',
    dadDesc: 'Søvnlog & viden',
    nightLonelinessTitle: '🌙 Natteensomhed',
    nightLonelinessDesc: 'Natteensomhed-rummet er et trygt rum kun for mødre — for dem der er vågne om natten og har brug for at vide, at de ikke er alene.',
    yourName: 'Dit navn',
    namePlaceholder: 'Navn...',
    usernameLabel: 'Brugernavn',
    usernameHint: 'Kun bogstaver, tal og underscore',
    uploadingLabel: 'Uploader...',
    addProfilePic: 'Tilføj profilbillede (valgfrit)',
    iAcceptTerms: 'Jeg accepterer',
    termsLinkLabel: 'handelsbetingelserne',
    privacyLinkLabel: 'privatlivspolitikken',
    termsTitle: 'Handelsbetingelser',
    privacyTitle: 'Privatlivspolitik',
    yourCity: 'Din by',
    cityDesc: 'Vi bruger din by til at vise dig andre mødre i nærheden — helt frivilligt.',
    cityPlaceholder: 'fx København, Aarhus...',
    childBirthdateLabel: 'Barnets fødselsdato',
    orLabel: 'eller',
    dueDateLabel: 'Terminsdato (hvis ikke født endnu)',
    skip: 'Spring over',
    back: 'Tilbage',
    getStarted: 'Kom i gang 🎉',
    next: 'Næste',
    errorChooseRole: 'Vælg om du er mor eller far',
    errorEnterName: 'Indtast dit navn',
    errorChooseUsername: 'Vælg et brugernavn',
    errorUsernameMin: 'Mindst 3 tegn',
    errorAcceptTerms: 'Du skal acceptere handelsbetingelserne',
    errorAcceptPrivacy: 'Du skal acceptere privatlivspolitikken',
    usernameOnlyChars: 'Kun bogstaver, tal og underscore',

    // ChildDevelopmentCard
    dueIn: 'Termin om',
    yourChildIs: 'Dit barn er',
    old: 'gammel',
    untilDue: 'til termin',
    weekSingular: 'uge',
    weekPlural: 'uger',
    daySingular: 'dag',
    dayPlural: 'dage',
    monthsShort: 'mdr',
    hoursShort: 't',
    minutesShort: 'm',

    // SleepSummaryCard
    sleepLastNight: 'Søvn i nat',
    wakingSingular: 'opvågning',
    wakingPlural: 'opvågninger',
    logSleepCta: 'Log søvn →',

    // UpcomingEventCard
    nextAppointment: 'Næste aftale',
    today: 'I dag',
    tomorrow: 'I morgen',
    addAppointmentCta: 'Tilføj aftale →',

    // SleepAdviceCard
    sleepAdviceTitle: 'Søvnråd fra eksperten',
    seeSleepLog: 'Se søvnlog →',
    basedOnLogs: 'Baseret på dine seneste',
    logsLabel: 'logs',

    // AIRelevantPosts
    relevantForYou: 'Relevant for dig',
    seeAll: 'Se alle →',

    // WonderWeekCard
    wonderWeekActiveLabel: 'TIGERSPRING',
    wonderWeekActiveNow: 'AKTIV NU',
    nextLeapIn: 'Næste spring om',
    progress: 'Fremgang',
    weeksLeft: 'uge(r) tilbage',
    almostOver: 'Næsten forbi',
    approx: 'ca.',
    hideDetails: 'Skjul detaljer',
    seeSigns: 'Se tegn & tips',
    typicalSigns: 'Typiske tegn',
    tipsForYou: 'Tips til dig',
    readMoreWonderWeeks: 'Læs mere om tigerspring',
    getReadyLeap: 'Bliv klar – dit barn er snart klar til sit næste store spring 🌱',

    // Calendar
    calendarTitle: 'Kalender',
    eventCreated: 'Aftale oprettet',
    eventDeleted: 'Aftale slettet',
    fillTitleAndTime: 'Udfyld titel og starttidspunkt',
    noEventsToday: 'Ingen aftaler denne dag',
    addEvent: 'Tilføj',
    newEvent: 'Ny aftale',
    eventTitle: 'Titel *',
    eventStart: 'Start *',
    eventEnd: 'Slut (valgfrit)',
    eventDescription: 'Beskrivelse (valgfrit)',
    saveEvent: 'Gem aftale',
    calendarReminderNote: '📲 Du får besked dagen før og 30 min før aftalen',
    eventTitlePlaceholder: 'Fx lægebesøg, vaccination...',
    eventDescPlaceholder: 'Evt. adresse eller noter...',
    weekdaysShort: ['Man', 'Tir', 'Ons', 'Tor', 'Fre', 'Lør', 'Søn'],
  },

  en: {
    // Nav
    home: 'Home',
    menu: 'Menu',
    shop: 'Shop',
    blog: 'Blog',
    sleepLog: 'Sleep log',
    knowledge: 'Knowledge',
    community: 'Community',
    calendar: 'Calendar',
    profile: 'Profile',

    // Home
    goodDay: 'Good day, mom 🤍',
    dailyWord: "Today's word for you",
    fromBlog: 'From the blog',
    seeAll: 'See all →',
    affirmations: [
      "You are a wonderful mom — even on the days it doesn't feel that way. 🤍",
      "It's okay that the coffee is cold. You are warm and present, and that is enough.",
      "You don't need to do everything perfectly. You just need to do your best — and you are.",
      "Sleep deprivation is hard. The fact that you keep going is proof of your incredible strength.",
      "Your baby doesn't know what 'perfect' is. They only know they love you.",
      "Those who say motherhood is easy have never tried it. You've got this!",
      "Every little smile from your child is proof that you're doing it right.",
      "You are not alone. Thousands of moms are sitting right now feeling exactly the same.",
      "It's okay to need help. Asking for it is actually brave.",
      "Today you are enough. Tomorrow you are enough. Always you are enough.",
      "Your tears are not weakness — they are love that has overflowed.",
      "No handbook can prepare you for the love you feel. You are strong.",
      "You have done something incredible. You have created a human being. Remember that.",
      "Some days it's enough that everyone is alive and reasonably fed. 🙌",
      "You are your baby's favourite person in the whole world. Always.",
      "Even though you're tired, you are still there. That is love in its purest form.",
      "No mother is perfect. But you are the perfect mother for your child.",
      "A good mother is not one who never fails — but one who always tries again.",
      "Congratulations on surviving another night. You deserve a medal (and more coffee).",
      "Your love is the warmest place your child knows. 🧡",
      "Even the hard days shape you both into something stronger.",
      "You are more than 'just a mom'. You are an everyday hero.",
      "What you give your child today, they carry with them all their life.",
      "A barely-making-it day is still a day full of love.",
      "You handle more than you know. That is the most beautiful thing about you.",
      "Every hug, every feed, every sleep attempt — it counts.",
      "Motherhood is not a performance. It's a relationship. And yours is beautiful.",
      "You have not failed. You are in the middle of it.",
      "Tomorrow is a new chance. And you are already ready for it.",
      "You carry so much. But you carry it with love.",
    ],

    // Profile
    profileTitle: 'Profile',
    edit: 'Edit',
    editProfile: 'Edit profile',
    username: 'Username',
    displayName: 'Display name',
    city: 'City',
    childBirthdate: "Child's birthday",
    wonderWeekInfo: 'Used to calculate wonder weeks 🐯',
    saveChanges: 'Save changes',
    saving: 'Saving…',
    profileUpdated: 'Profile updated',
    favorites: 'Favorites',
    notifications: 'Notifications',
    questions: 'Questions',
    settings: 'Settings',
    help: 'Help',
    shareLocation: 'Share location',
    showAsVisible: 'Show me as visible',
    logOut: 'Log out',
    language: 'Language',
    chooseLanguage: 'Choose language',

    // Settings
    settingsTitle: 'Settings',
    password: 'Password',
    privacy: 'Privacy',
    theme: 'Theme',
    chooseTheme: 'Choose your preferred look',
    light: 'Light',
    dark: 'Dark',
    faq: 'Frequently asked questions',
    contactSupport: 'Contact support',
    deleteAccount: 'Delete account',
    blogAndArticles: 'Blog & Articles',
    changePassword: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    updatePassword: 'Update password',
    passwordMismatch: 'Passwords do not match',
    passwordUpdated: 'Password updated',
    deleteWarning: 'Are you sure? This action cannot be undone — all your data will be permanently deleted.',
    typeToConfirmDelete: 'Type DELETE to confirm',
    deleteConfirmWord: 'DELETE',
    deletePermanently: 'Delete my account permanently',
    faqQ1: 'How do I edit my profile?',
    faqA1: 'Go to your profile and tap "Edit".',
    faqQ2: 'How do I find a practitioner?',
    faqA2: 'Find a practitioner under the Community tab.',

    // Knowledge
    knowledgeTitle: 'Knowledge & Answers',
    searchPlaceholder: 'Search knowledge...',
    articles: 'Articles',
    noResults: 'No results for',
    noFaq: 'No FAQ yet',
    noQuestions: 'No questions yet',
    askQuestion: 'Ask a question',
    answered: 'Answered',
    open: 'Open',
    by: 'by',
    answers: 'answers',

    // Shop
    shopTitle: 'Shop',
    searchProducts: 'Search products...',
    noProducts: 'No products found',
    sortBy: 'Sort by',
    newest: 'Newest',
    priceLow: 'Price: Low to high',
    priceHigh: 'Price: High to low',
    filtersTitle: 'Filters & Sorting',
    outOfStock: 'Out of stock',
    catAll: 'All',
    catCare: 'Care',
    catAccessories: 'Accessories',
    catEquipment: 'Equipment',
    catBooks: 'Books',

    // Blog
    blogTitle: 'Blog',
    searchBlog: 'Search posts...',
    noPosts: 'No posts found',
    allCategories: 'All',

    // Community
    nearMe: 'Near me',
    chats: 'Chats',
    practitioners: 'Practitioners',
    aboutUs: 'About us',
    onlyForMoms: 'Moms only',
    onlyForMomsDesc: 'The community feature is reserved for mom profiles. Our mission is to fight night loneliness among moms — a safe space just for them.',
    switchToMomProfile: 'Switch to your mom profile to get access.',
    location: 'Location',
    findNearby: 'Find people nearby',
    locationActive: 'Active',
    enableLocation: 'Enable',
    showMeVisible: 'Show me as visible to others',
    activeMomsInDenmark: 'Active moms in Denmark',
    activeNow: 'active now',
    visible: 'Visible',
    hidden: 'Hidden',
    you: 'You',
    othersActive: 'Others active',
    enableLocationToSee: 'Enable location to see who is nearby',
    noUsersNearby: 'No users nearby (20 km)',
    personWithin: 'person within 20 km',
    personsWithin: 'people within 20 km',
    noConversations: 'No conversations yet',
    startChatNearby: 'Start a chat with someone nearby',
    unknown: 'Unknown',
    findPractitioner: 'Find practitioner',
    showingInArea: 'Showing experts in your area',
    showingRecommended: 'Showing recommended practitioners',
    all: 'All',
    searchInMyArea: 'Search my area',
    noExpertsInArea: 'No experts found in your area',
    noExpertsAvailable: 'No experts available',
    showAllExperts: 'Show all experts',
    recommendedPractitioners: 'Recommended practitioners',
    locationConsentTitle: 'Location usage',
    locationConsentDesc: 'Enable location to discover nearby moms who are also awake. Your exact location is never shared with other users — only an approximate distance is shown (e.g. "2 km away").',
    locationConsentNote: 'Location is used solely to find nearby users. You can disable it at any time in settings.',
    noThanks: 'No thanks',
    activateLocation: 'Enable location',
    locationActivated: 'Location enabled',
    locationError: 'Could not get location',
    browserNoLocation: 'Your browser does not support location',

    // SleepLog
    sleepLogTitle: 'Sleep log',
    historyBtn: 'History',
    logTodayBtn: 'Log today',
    todayLog: "Today's log",
    nightSleep: 'Night sleep',
    nightWakings: 'Night wakings',
    naps: 'Naps',
    nap: 'Nap',
    howDidBabyFallAsleep: 'How did the baby fall asleep?',
    moodBeforeBed: 'Mood before bedtime',
    notes: 'Notes',
    notesPlaceholder: 'What happened today? Restless evening? New tooth?',
    addWaking: 'Add waking',
    addNap: 'Add nap',
    bedtime: 'Bedtime',
    fellAsleep: 'Fell asleep',
    wokeUp: 'Woke up',
    date: 'Date',
    ageMonths: 'Age (months)',
    agePlaceholder: 'e.g. 8',
    saveSleepLog: 'Save sleep log',
    saving: 'Saving...',
    sleepLogSaved: 'Sleep log saved ✓',
    getAiAdvice: 'Get AI sleep advice',
    updateAiAdvice: 'Update AI advice',
    updateAnalysis: 'Update analysis',
    aiAnalyzing: 'The AI expert is analysing your sleep data…',
    aiErrorMsg: "Couldn't fetch analysis right now. Try again in a moment — you're doing great!",
    aiErrorTitle: '💛 A loving note',
    noLogsYet: 'No logs yet',
    bedAt: 'Bed',
    wakings: 'waking',
    wakingsPlural: 'wakings',
    felAsleepIn: 'Fell asleep:',
    nightNap: 'night sleep',
    napTotal: 'naps',
    sleepMethodSelf: 'Self',
    sleepMethodNursing: 'Nursing',
    sleepMethodBottle: 'Bottle',
    sleepMethodRocking: 'Rocking',
    sleepMethodPram: 'Pram',
    sleepMethodParent: 'With parent',
    moodFresh: 'Fresh',
    moodLittleTired: 'A little tired',
    moodVeryTired: 'Very tired',
    moodOvertired: 'Overtired',
    wakingMethodNursing: 'Nursing',
    wakingMethodBottle: 'Bottle',
    wakingMethodRocking: 'Rocking',
    wakingMethodSing: 'Sung to sleep',
    wakingMethodPram: 'Pram',
    wakingMethodSelf: 'Self-settled',

    // AIChat
    aiChatTitle: 'Baby & Sleep Expert',
    aiOnline: 'AI assistant · Online',
    aiGreeting: 'Hi! I am here for you 🤍',
    aiSubtitle: 'Expert in baby sleep, breastfeeding and child development. Ask me anything!',
    aiSuggestion1: 'How do I help my baby sleep better?',
    aiSuggestion2: 'What is sleep regression?',
    aiSuggestion3: 'My baby only sleeps 20 min at a time — help!',
    aiPlaceholder: 'Write your question…',
    aiDisclaimer: 'The AI assistant can make mistakes and does not replace medical advice.',
    backLabel: 'Go back',
    sendLabel: 'Send message',

    // Community / shared
    version: 'Version 1.0.0',
    v1: 'v1.0',

    // Profile extra
    momProfileLabel: 'Mom profile · Community access',
    dadProfileLabel: 'Dad profile · Sleep log',
    genderLabel: 'Gender',
    female: 'Female',
    male: 'Male',
    genderLocked: 'Gender cannot be changed after selection',
    myDataPrivacy: 'My data & privacy',
    helpAndContact: 'Help & contact',
    aboutApp: 'About the app',
    writeToUs: 'Contact us',
    callUs: 'Call us',

    // Settings extra
    loading: 'Loading...',
    noFaqAvailable: 'No FAQ available yet.',
    noSupportInfo: 'No support info available yet.',
    noPrivacyPolicy: 'No privacy policy available yet.',

    // Shop extra
    categoryLabel: 'Category',
    productsLabel: 'products',
    categoriesTitle: 'Categories',
    filtersAndSorting: 'Filters & Sorting',

    // Onboarding
    whoAreYou: 'Who are you?',
    chooseRoleSubtitle: 'Choose your role in the family',
    welcomeTitle: 'Welcome to LALATOTO',
    welcomeSubtitle: 'Create your profile and accept the terms',
    whereDoYouLive: 'Where do you live?',
    findNearbyMoms: 'Find moms near you',
    aboutYourChild: 'About your child',
    calculateWonderWeeksSubtitle: 'So we can calculate wonder weeks for you',
    lalatotoBuiltForFamily: 'LALATOTO is built for the whole family. Choose your role so we can tailor the experience for you.',
    mom: 'Mom',
    dad: 'Dad',
    momDesc: 'Community, sleep log & more',
    dadDesc: 'Sleep log & knowledge',
    nightLonelinessTitle: '🌙 Night loneliness',
    nightLonelinessDesc: 'Our night loneliness space is a safe space exclusively for moms — for those awake at night who need to know they are not alone.',
    yourName: 'Your name',
    namePlaceholder: 'Name...',
    usernameLabel: 'Username',
    usernameHint: 'Only letters, numbers and underscores',
    uploadingLabel: 'Uploading...',
    addProfilePic: 'Add profile picture (optional)',
    iAcceptTerms: 'I accept the',
    termsLinkLabel: 'terms of service',
    privacyLinkLabel: 'privacy policy',
    termsTitle: 'Terms of service',
    privacyTitle: 'Privacy policy',
    yourCity: 'Your city',
    cityDesc: 'We use your city to show you other moms nearby — completely optional.',
    cityPlaceholder: 'e.g. Copenhagen, Aarhus...',
    childBirthdateLabel: "Child's birth date",
    orLabel: 'or',
    dueDateLabel: 'Due date (if not born yet)',
    skip: 'Skip',
    back: 'Back',
    getStarted: 'Get started 🎉',
    next: 'Next',
    errorChooseRole: 'Choose whether you are a mom or dad',
    errorEnterName: 'Enter your name',
    errorChooseUsername: 'Choose a username',
    errorUsernameMin: 'At least 3 characters',
    errorAcceptTerms: 'You must accept the terms of service',
    errorAcceptPrivacy: 'You must accept the privacy policy',
    usernameOnlyChars: 'Only letters, numbers and underscores',

    // ChildDevelopmentCard
    dueIn: 'Due in',
    yourChildIs: 'Your child is',
    old: 'old',
    untilDue: 'until due date',
    weekSingular: 'week',
    weekPlural: 'weeks',
    daySingular: 'day',
    dayPlural: 'days',
    monthsShort: 'mo',
    hoursShort: 'h',
    minutesShort: 'm',

    // SleepSummaryCard
    sleepLastNight: 'Sleep last night',
    wakingSingular: 'waking',
    wakingPlural: 'wakings',
    logSleepCta: 'Log sleep →',

    // UpcomingEventCard
    nextAppointment: 'Next appointment',
    today: 'Today',
    tomorrow: 'Tomorrow',
    addAppointmentCta: 'Add appointment →',

    // SleepAdviceCard
    sleepAdviceTitle: 'Sleep advice from the expert',
    seeSleepLog: 'See sleep log →',
    basedOnLogs: 'Based on your last',
    logsLabel: 'logs',

    // AIRelevantPosts
    relevantForYou: 'Relevant for you',
    seeAll: 'See all →',

    // WonderWeekCard
    wonderWeekActiveLabel: 'WONDER WEEK',
    wonderWeekActiveNow: 'ACTIVE NOW',
    nextLeapIn: 'Next leap in',
    progress: 'Progress',
    weeksLeft: 'week(s) left',
    almostOver: 'Almost over',
    approx: 'approx.',
    hideDetails: 'Hide details',
    seeSigns: 'See signs & tips',
    typicalSigns: 'Typical signs',
    tipsForYou: 'Tips for you',
    readMoreWonderWeeks: 'Read more about wonder weeks',
    getReadyLeap: 'Get ready – your child is almost ready for their next big leap 🌱',

    // Calendar
    calendarTitle: 'Calendar',
    eventCreated: 'Appointment created',
    eventDeleted: 'Appointment deleted',
    fillTitleAndTime: 'Fill in title and start time',
    noEventsToday: 'No appointments today',
    addEvent: 'Add',
    newEvent: 'New appointment',
    eventTitle: 'Title *',
    eventStart: 'Start *',
    eventEnd: 'End (optional)',
    eventDescription: 'Description (optional)',
    saveEvent: 'Save appointment',
    calendarReminderNote: '📲 You will be notified the day before and 30 min before the appointment',
    eventTitlePlaceholder: 'e.g. doctor visit, vaccination...',
    eventDescPlaceholder: 'Optional address or notes...',
    weekdaysShort: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  },
};

const LanguageContext = createContext({
  lang: 'da',
  t: translations.da,
  setLang: () => {},
});

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    return localStorage.getItem('app-language') || 'da';
  });

  const setLang = (newLang) => {
    localStorage.setItem('app-language', newLang);
    setLangState(newLang);
  };

  const t = translations[lang] || translations.da;

  return (
    <LanguageContext.Provider value={{ lang, t, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}