import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  da: {
    // Nav
    home: 'Hjem',
    menu: 'Menu',
    shop: 'Shop',
    blog: 'Søg og find svar',
    sleepLog: 'Søvnlog',
    knowledge: 'Viden',
    community: 'Community',
    calendar: 'Kalender',
    profile: 'Profil',
    natteensomhed: 'Et lys i mørket',

    // Home
    goodDay: 'God dag, mor 🤍',
    dailyWord: 'Dagens ord til dig',
    fromBlog: 'Fra bloggen',
    seeAll: 'Se alle →',
    affirmations: [
      "Du er en vidunderlig mor — selv på dage hvor det ikke føles sådan. 🤍",
      "Det er okay at kaffen er kold. Du er varm og til stede, og det er nok.",
      "Du behøver ikke at gøre alt perfekt. Du behøver bare at gøre dit bedste — og det gør du.",
      "Søvnmangel er hårdt. At du holder ved er bevis på din utrolige styrke.",
      "Dit barn ved ikke hvad 'perfekt' betyder. De ved bare at de elsker dig.",
      "De der siger at moderskab er nemt, har aldrig prøvet det. Du klarer dette!",
      "Ethvert lille smil fra dit barn er bevis på at du gør det rigtigt.",
      "Du er ikke alene. Tusinder af mødre sidder lige nu og føler præcis det samme.",
      "Det er okay at have brug for hjælp. At bede om den er faktisk modig.",
      "I dag er du nok. I morgen er du nok. Altid er du nok.",
      "Dine tårer er ikke svaghed — de er kærlighed der er overløbet.",
      "Ingen håndbok kan forberede dig på den kærlighed du føler. Du er stærk.",
      "Du har gjort noget utroligt. Du har skabt et menneske. Husk det.",
      "Nogle dage er det nok at alle lever og er relativt mætte. 🙌",
      "Du er dit babys yndlingsperson i hele verden. Altid.",
      "Selvom du er træt, er du stadig der. Det er kærlighed i sin reneste form.",
      "Ingen mor er perfekt. Men du er den perfekte mor for dit barn.",
      "En god mor er ikke en der aldrig fejler — men en der altid prøver igen.",
      "Tillykke fordi du overlevede endnu en nat. Du fortjener en medalje (og mere kaffe).",
      "Din kærlighed er det varmeste sted dit barn kender. 🧡",
      "Selv de svære dage formes jer begge til noget stærkere.",
      "Du er meget mere end 'bare en mor'. Du er en hverdagshelt.",
      "Det du giver dit barn i dag, bærer de med sig hele deres liv.",
      "En dag hvor du næppe klarer det, er stadig en dag fuld af kærlighed.",
      "Du håndterer mere end du ved. Det er det smukkeste ved dig.",
      "Ethvert kram, hver amning, hvert søvnforsøg — det tæller.",
      "Moderskab er ikke en præstation. Det er et forhold. Og dit er smukt.",
      "Du har ikke fejlet. Du er midt i det.",
      "I morgen er en ny chance. Og du er allerede klar til det.",
      "Du bærer så meget. Men du bærer det med kærlighed.",
    ],

    // Profile
    profileTitle: 'Profil',
    edit: 'Rediger',
    editProfile: 'Rediger profil',
    username: 'Brugernavn',
    displayName: 'Visningsnavn',
    city: 'By',
    childBirthdate: 'Barnets fødselsdag',
    wonderWeekInfo: 'Bruges til beregning af tigerspring 🐯',
    saveChanges: 'Gem ændringer',
    saving: 'Gemmer…',
    profileUpdated: 'Profil opdateret',
    favorites: 'Favoritter',
    notifications: 'Notifikationer',
    questions: 'Spørgsmål',
    settings: 'Indstillinger',
    help: 'Hjælp',
    shareLocation: 'Del lokation',
    showAsVisible: 'Vis mig som synlig',
    logOut: 'Log ud',
    language: 'Sprog',
    chooseLanguage: 'Vælg sprog',

    // Settings
    settingsTitle: 'Indstillinger',
    password: 'Adgangskode',
    privacy: 'Privatliv',
    theme: 'Tema',
    chooseTheme: 'Vælg dit foretrukne look',
    light: 'Lys',
    dark: 'Mørk',
    faq: 'Ofte stillede spørgsmål',
    contactSupport: 'Kontakt support',
    deleteAccount: 'Slet konto',
    blogAndArticles: 'Blog & Artikler',
    changePassword: 'Skift adgangskode',
    currentPassword: 'Nuværende adgangskode',
    newPassword: 'Ny adgangskode',
    confirmPassword: 'Bekræft ny adgangskode',
    updatePassword: 'Opdater adgangskode',
    passwordMismatch: 'Adgangskoderne matcher ikke',
    passwordUpdated: 'Adgangskode opdateret',
    deleteWarning: 'Er du sikker? Denne handling kan ikke fortrydes — al din data slettes permanent.',
    typeToConfirmDelete: 'Skriv SLET for at bekræfte',
    deleteConfirmWord: 'SLET',
    deletePermanently: 'Slet min konto permanent',
    faqQ1: 'Hvordan ændrer jeg min profil?',
    faqA1: 'Gå til din profil og tryk på "Rediger".',
    faqQ2: 'Hvordan finder jeg en behandler?',
    faqA2: 'Find en behandler under Community-fanen.',

    // Knowledge
    knowledgeTitle: 'Viden & Svar',
    searchPlaceholder: 'Søg i viden...',
    articles: 'Artikler',
    noResults: 'Ingen resultater for',
    noFaq: 'Ingen FAQ endnu',
    noQuestions: 'Ingen spørgsmål endnu',
    askQuestion: 'Stil et spørgsmål',
    answered: 'Besvaret',
    open: 'Åben',
    by: 'af',
    answers: 'svar',

    // Shop
    shopTitle: 'Shop',
    searchProducts: 'Søg produkter...',
    noProducts: 'Ingen produkter fundet',
    sortBy: 'Sorter efter',
    newest: 'Nyeste',
    priceLow: 'Pris: Lav til høj',
    priceHigh: 'Pris: Høj til lav',
    filtersTitle: 'Filtre & Sortering',
    outOfStock: 'Udsolgt',
    catAll: 'Alle',
    catCare: 'Pleje',
    catAccessories: 'Tilbehør',
    catEquipment: 'Udstyr',
    catBooks: 'Bøger',

    // Blog
    blogTitle: 'Søg og find svar',
    searchBlog: 'Hvad vil du vide mere om?',
    noPosts: 'Ingen indlæg fundet',
    allCategories: 'Alle',

    // Community
    nearMe: 'Nær mig',
    chats: 'Chats',
    practitioners: 'Behandlere',
    aboutUs: 'Om os',
    onlyForMoms: 'Kun for mødre',
    onlyForMomsDesc: 'Natteensomhed-funktionen er forbeholdt mor-profiler. Vores mission er at bekæmpe natteensomhed blandt mødre — et trygt rum kun for dem.',
    switchToMomProfile: 'Opret profil for at få adgang.',
    location: 'Lokation',
    findNearby: 'Find folk i nærheden',
    locationActive: 'Aktiv',
    enableLocation: 'Aktiver',
    showMeVisible: 'Vis mig som synlig for andre',
    activeMomsInDenmark: 'Vågne mødre nær dig',
    activeNow: 'aktive nu',
    visible: 'Synlig',
    hidden: 'Skjult',
    you: 'Dig',
    othersActive: 'Andre aktive',
    enableLocationToSee: 'Aktiver lokation for at se hvem der er i nærheden',
    noUsersNearby: 'Ingen brugere i nærheden (20 km)',
    personWithin: 'person indenfor 20 km',
    personsWithin: 'personer indenfor 20 km',
    noConversations: 'Ingen samtaler endnu',
    startChatNearby: 'Start en chat med nogen i nærheden',
    unknown: 'Ukendt',
    findPractitioner: 'Find behandler',
    showingInArea: 'Viser eksperter i dit område',
    showingRecommended: 'Viser anbefalede behandlere',
    all: 'Alle',
    searchInMyArea: 'Søg i mit område',
    noExpertsInArea: 'Ingen eksperter fundet i dit område',
    noExpertsAvailable: 'Ingen eksperter tilgængelige',
    showAllExperts: 'Vis alle eksperter',
    recommendedPractitioners: 'Anbefalede behandlere',
    locationConsentTitle: 'Brug af lokation',
    locationConsentDesc: 'Aktiver lokation for at opdage mødre i nærheden, der også er vågne. Din præcise lokation deles aldrig med andre brugere — kun en omtrentlig afstand vises (fx "2 km væk").',
    locationConsentNote: 'Lokation bruges udelukkende til at finde brugere i nærheden. Du kan til enhver tid deaktivere det igen under indstillinger.',
    noThanks: 'Nej tak',
    activateLocation: 'Aktiver lokation',
    locationActivated: 'Lokation aktiveret',
    locationError: 'Kunne ikke hente lokation',
    browserNoLocation: 'Din browser understøtter ikke lokation',

    // SleepLog
    sleepLogTitle: 'Søvnlog',
    historyBtn: 'Historik',
    logTodayBtn: 'Log i dag',
    todayLog: 'Dagens log',
    nightSleep: 'Natsøvn',
    nightWakings: 'Natlige opvågninger',
    naps: 'Lure',
    nap: 'Lur',
    howDidBabyFallAsleep: 'Hvordan faldt barnet i søvn?',
    moodBeforeBed: 'Humør før sengetid',
    notes: 'Noter',
    notesPlaceholder: 'Hvad skete der i dag? Urolig aften? Ny tand?',
    addWaking: 'Tilføj opvågning',
    addNap: 'Tilføj lur',
    bedtime: 'Sengetid',
    fellAsleep: 'Faldt i søvn',
    wokeUp: 'Vågnede',
    date: 'Dato',
    ageMonths: 'Alder (måneder)',
    agePlaceholder: 'f.eks. 8',
    saveSleepLog: 'Gem søvnlog',
    saving: 'Gemmer...',
    sleepLogSaved: 'Søvnlog gemt ✓',
    getAiAdvice: 'Få AI-råd til søvnen',
    updateAiAdvice: 'Opdater AI-råd',
    updateAnalysis: 'Opdater analyse',
    aiAnalyzing: 'AI-eksperten analyserer jeres søvndata…',
    aiErrorMsg: 'Kunne ikke hente analyse lige nu. Prøv igen om lidt — du gør det godt!',
    aiErrorTitle: '💛 En kærlig hilsen',
    noLogsYet: 'Ingen logs endnu',
    bedAt: 'Seng',
    wakings: 'opvågning',
    wakingsPlural: 'opvågninger',
    felAsleepIn: 'Puttetid:',
    nightSleepDuration: 'Nattesøvn:',
    nightNap: 'natsøvn',
    napTotal: 'lure',
    sleepMethodSelf: 'Selv',
    sleepMethodNursing: 'Amning',
    sleepMethodBottle: 'Flaske',
    sleepMethodRocking: 'Vugning',
    sleepMethodPram: 'Barnevogn',
    sleepMethodParent: 'Med forælder',
    moodFresh: 'Frisk',
    moodLittleTired: 'Lidt træt',
    moodVeryTired: 'Meget træt',
    moodOvertired: 'Overtræt',
    wakingMethodNursing: 'Amning',
    wakingMethodBottle: 'Flaske',
    wakingMethodRocking: 'Vugning',
    wakingMethodSing: 'Sig i søvn',
    wakingMethodPram: 'Barnevogn',
    wakingMethodSelf: 'Sov selv',

    // AIChat
    aiChatTitle: 'Baby & Søvn Ekspert',
    aiOnline: 'AI-assistent · Online',
    aiGreeting: 'Hej! Jeg er her for dig 🤍',
    aiSubtitle: 'Ekspert i babysøvn, amning og barnets udvikling. Spørg mig om alt!',
    aiSuggestion1: 'Hvordan hjælper jeg min baby til at sove bedre?',
    aiSuggestion2: 'Hvad er søvnregression?',
    aiSuggestion3: 'Min baby sover kun 20 min ad gangen — hjælp!',
    aiPlaceholder: 'Skriv dit spørgsmål…',
    aiDisclaimer: 'AI-assistenten kan lave fejl og erstatter ikke lægefaglig rådgivning.',
    backLabel: 'Gå tilbage',
    sendLabel: 'Send besked',

    // Community / shared
    version: 'Version 1.0.0',
    v1: 'v1.0',

    // Profile extra
    momProfileLabel: 'Mor-profil · Adgang til community',
    dadProfileLabel: 'Far-profil · Søvnlog',
    genderLabel: 'Køn',
    female: 'Kvinde',
    male: 'Mand',
    genderLocked: 'Køn kan ikke ændres efter valg',
    myDataPrivacy: 'Mine data & privatliv',
    helpAndContact: 'Hjælp & kontakt',
    aboutApp: 'Om appen',
    writeToUs: 'Skriv til os',
    callUs: 'Ring til os',

    // Settings extra
    loading: 'Indlæser...',
    noFaqAvailable: 'Ingen FAQ tilgængelig endnu.',
    noSupportInfo: 'Ingen supportinfo tilgængelig endnu.',
    noPrivacyPolicy: 'Ingen privatlivspolitik tilgængelig endnu.',

    // Shop extra
    categoryLabel: 'Kategori',
    productsLabel: 'produkter',
    categoriesTitle: 'Kategorier',
    filtersAndSorting: 'Filtre & Sortering',

    // Onboarding
    whoAreYou: 'Hvem er du?',
    chooseRoleSubtitle: 'Vælg din rolle i familien',
    welcomeTitle: 'Velkommen til LALATOTO',
    welcomeSubtitle: 'Opret din profil og acceptér betingelserne',
    whereDoYouLive: 'Hvor bor du?',
    findNearbyMoms: 'Find mødre i nærheden af dig',
    aboutYourChild: 'Om dit barn',
    calculateWonderWeeksSubtitle: 'Så kan vi beregne tigerspring for dig',
    lalatotoBuiltForFamily: 'LALATOTO er bygget til hele familien. Vælg din rolle, så vi kan tilpasse oplevelsen til dig.',
    mom: 'Mor',
    dad: 'Far',
    momDesc: 'Community, søvnlog & mere',
    dadDesc: 'Søvnlog & viden',
    nightLonelinessTitle: '🌙 Natteensomhed',
    nightLonelinessDesc: 'Natteensomhed-rummet er et trygt rum kun for mødre — for dem der er vågne om natten og har brug for at vide, at de ikke er alene.',
    yourName: 'Dit navn',
    namePlaceholder: 'Navn...',
    usernameLabel: 'Brugernavn',
    usernameHint: 'Kun bogstaver, tal og underscore',
    uploadingLabel: 'Uploader...',
    addProfilePic: 'Tilføj profilbillede (valgfrit)',
    iAcceptTerms: 'Jeg accepterer',
    termsLinkLabel: 'handelsbetingelserne',
    privacyLinkLabel: 'privatlivspolitikken',
    termsTitle: 'Handelsbetingelser',
    privacyTitle: 'Privatlivspolitik',
    yourCity: 'Din by',
    cityDesc: 'Vi bruger din by til at vise dig andre mødre i nærheden — helt frivilligt.',
    cityPlaceholder: 'fx København, Aarhus...',
    childBirthdateLabel: 'Barnets fødselsdato',
    orLabel: 'eller',
    dueDateLabel: 'Terminsdato (hvis ikke født endnu)',
    skip: 'Spring over',
    back: 'Tilbage',
    getStarted: 'Kom i gang 🎉',
    next: 'Næste',
    errorChooseRole: 'Vælg om du er mor eller far',
    errorEnterName: 'Indtast dit navn',
    errorChooseUsername: 'Vælg et brugernavn',
    errorUsernameMin: 'Mindst 3 tegn',
    errorAcceptTerms: 'Du skal acceptere handelsbetingelserne',
    errorAcceptPrivacy: 'Du skal acceptere privatlivspolitikken',
    usernameOnlyChars: 'Kun bogstaver, tal og underscore',

    // ChildDevelopmentCard
    dueIn: 'Termin om',
    yourChildIs: 'Dit barn er',
    old: 'gammel',
    untilDue: 'til termin',
    weekSingular: 'uge',
    weekPlural: 'uger',
    daySingular: 'dag',
    dayPlural: 'dage',
    monthsShort: 'mdr',
    hoursShort: 't',
    minutesShort: 'm',

    // SleepSummaryCard
    sleepLastNight: 'Søvn i nat',
    wakingSingular: 'opvågning',
    wakingPlural: 'opvågninger',
    logSleepCta: 'Log søvn →',

    // UpcomingEventCard
    nextAppointment: 'Næste aftale',
    today: 'I dag',
    tomorrow: 'I morgen',
    addAppointmentCta: 'Tilføj aftale →',

    // SleepAdviceCard
    sleepAdviceTitle: 'Søvnråd fra eksperten',
    seeSleepLog: 'Se søvnlog →',
    basedOnLogs: 'Baseret på dine seneste',
    logsLabel: 'logs',

    // AIRelevantPosts
    relevantForYou: 'Relevant for dig',
    seeAll: 'Se alle →',

    // WonderWeekCard
    wonderWeekActiveLabel: 'TIGERSPRING',
    wonderWeekActiveNow: 'AKTIV NU',
    nextLeapIn: 'Næste spring om',
    progress: 'Fremgang',
    weeksLeft: 'uge(r) tilbage',
    almostOver: 'Næsten forbi',
    approx: 'ca.',
    hideDetails: 'Skjul detaljer',
    seeSigns: 'Se tegn & tips',
    typicalSigns: 'Typiske tegn',
    tipsForYou: 'Tips til dig',
    readMoreWonderWeeks: 'Læs mere om tigerspring',
    getReadyLeap: 'Bliv klar – dit barn er snart klar til sit næste store spring 🌱',

    // Calendar
    calendarTitle: 'Kalender',
    eventCreated: 'Aftale oprettet',
    eventDeleted: 'Aftale slettet',
    fillTitleAndTime: 'Udfyld titel og starttidspunkt',
    noEventsToday: 'Ingen aftaler denne dag',
    addEvent: 'Tilføj',
    newEvent: 'Ny aftale',
    eventTitle: 'Titel *',
    eventStart: 'Start *',
    eventEnd: 'Slut (valgfrit)',
    eventDescription: 'Beskrivelse (valgfrit)',
    saveEvent: 'Gem aftale',
    calendarReminderNote: '📲 Du får besked dagen før og 30 min før aftalen',
    eventTitlePlaceholder: 'Fx lægebesøg, vaccination...',
    eventDescPlaceholder: 'Evt. adresse eller noter...',
    weekdaysShort: ['Man', 'Tir', 'Ons', 'Tor', 'Fre', 'Lør', 'Søn'],

    // Landing
    landingOpenApp: 'Åbn app →',
    landingLogIn: 'Log ind',
    landingBecomeMember: 'Bliv medlem',
    landingPreviewPaymentAlert: 'Betaling virker kun fra den publicerede app, ikke fra forhåndsvisningen.',
    landingHero1Title1: 'Til dig, der er vågen,',
    landingHero1Title2: 'når resten af verden sover.',
    landingHero1P1: 'Der findes en hel særlig form for ensomhed i moderskabet. En ensomhed som kommer snigende om natten, når baby igen er vågen og resten af verden er stille;',
    landingHero1P1Bold: 'Natteensomhed.',
    landingHero1P2Bold: 'CLUB NO SLEEP',
    landingHero1P2: 'er en dansk app skabt til netop disse øjeblikke. For ingen skal føle sig alene i moderskabet.',
    landingAppStoreLabel: 'App Store',
    landingDownloadNow: 'Download now',
    landingIWantToLook: 'Jeg vil kigge →',
    landingFullAccess: 'FULD ADGANG',
    landingMembership: 'Medlemskab',
    landingPerMonth: '/ md.',
    landingFeature1: 'AI søvnrådgivning',
    landingFeature2: 'Tigerspring & udviklingsguide',
    landingFeature3: 'Chat med andre forældre',
    landingFeature4: 'Ekspert booking',
    landingFeature5: '100+ vidensartikler',
    landingFeature6: 'Fælles kalender med partner',
    landingFeature7: 'Notifikationer & milestene',
    landingGetStarted: 'Kom i Gang ✨',
    landingKlubTitle: 'Kom med i klubben',
    landingKlubP1: 'Vi har været der.',
    landingKlubP1b: 'Der hvor nætterne er svære, dagene er lange og ingen helt forstår, hvad du står i. Hvor far sover på sofaen og mor sover siddende. Hvor frygten for natten allerede starter i løbet af eftermiddagen.',
    landingKlubP1c: 'CLUB NO SLEEP er skabt til dig, som savner et sted at blive spejlet og finde andre, der er vågen sammen med dig.',
    landingKlubP2: 'Kom med i klubben. For din egen skyld, og for alle de mødre som føler sig alene netop nu. Sammen kan vi mindske ensomhed i moderskabet.',
    landingKlubSig: 'Kærligst og kram fra Sara & Nicolaj',
    landingFeaturesTitle: 'Dette finder du i appen',
    landingPartnerTitle1: 'Du skal ikke stå',
    landingPartnerTitle2: 'med det hele alene',
    landingPartnerP: 'Én konto inkluderer altid en gratis bruger mere, så du kan vælge at dele alt fra søvnlog, kalender og tigerspring med din partner. Sammen bliver det ofte lettere.',
    landingSharePartner: 'Del med partner',
    landingYou: '(dig)',
    landingManage: 'Administrer',
    landingPartner: '(partner)',
    landingActive: 'Aktiv',
    landingInvitePartner: 'Invitér partner',
    landingSharedCalendar: 'Fælles kalender',
    landingOsteopathEvent: 'Osteopat kl. 10:00',
    landingCafeEvent: 'Barselscafé kl. 14:00',
    landingFooterTagline: 'Din trygge havn som ny forælder — søvn, fællesskab og viden samlet ét sted.',
    landingLegal: 'Juridisk',
    landingTerms: 'Handelsbetingelser',
    landingPrivacy: 'Privatlivspolitik',
    landingGetTheApp: 'Hent appen',
    landingCopyright: '© 2025 Club No Sleep · Alle rettigheder forbeholdes',
    landingMadeWithLove: 'Skabt med ❤️ i Danmark',

    // AboutUs
    editLabelPrefix: 'Rediger',
    saved: 'Gemt',
    save: 'Gem',
    cancel: 'Annuller',
    funFactsAboutMe: 'fun facts om mig',
    meetTheFamily: 'Mød familien',
    adminEditHint: '✏️ Rediger ved at klikke',
    contactUs: 'Kontakt os',
    writeToUs: 'Skriv til os 💬',
    loginToMessage: 'Log ind for at sende en besked til os.',

    // FamilyInvite
    familySleepLog: 'Søvnlog',
    familyWonderWeeks: 'Tigerspring',
    familyCalendar: 'Kalender',
    familyKnowledge: 'Viden & artikler',
    familyNotifWonderWeeks: 'Notifikationer om tigerspring',
    familyNotifSleepLog: 'Notifikationer om søvnlog',
    familyNotifAppointments: 'Notifikationer om aftaler',
    fillEmailAndTitle: 'Udfyld email og vælg en titel',
    enterValidEmail: 'Indtast en gyldig email',
    invitationDeleted: 'Invitation slettet',
    somethingWentWrongTryAgain: 'Noget gik galt. Prøv igen.',
    statusAccepted: 'Accepteret',
    statusDeclined: 'Afvist',
    statusPending: 'Afventer',
    sharingAndAccess: 'Deling & adgang',
    sentInvitations: 'Sendte invitationer',
    noInvitationsYet: 'Ingen invitationer endnu',
    inviteFamilyMember: 'Invitér familiemedlem',
    whatToShare: 'Hvad skal deles?',
    notifications: 'Notifikationer',
    sending: 'Sender…',
    sendInvitation: 'Send invitation',
    invitationSentToPrefix: 'Invitation sendt til',
    familyInviteIntroDefault: 'Invitér et familiemedlem til at følge med — de får adgang til præcis det, du vælger, og kan modtage notifikationer om barnets milepæle.',
    familyMemberEmailLabel: 'Email på familiemedlem',
    familyMemberEmailPlaceholder: 'fx farmor@gmail.com',
    titleLabel: 'Titel',
    titlePlaceholder: 'fx Farmor, Bedste, Tante Lise...',
    titleFar: 'Far',
    titleFarmor: 'Farmor',
    titleFarfar: 'Farfar',
    titleMormor: 'Mormor',
    titleMorfar: 'Morfar',
    titleSoster: 'Søster',
    titleBror: 'Bror',
    titleVeninde: 'Veninde',
    titleVen: 'Ven',

    // MyData
    myDataPrivacy: 'Mine data & privatliv',
    exportMyData: 'Eksporter mine data',
    exportMyDataDesc: 'Download alt data vi har gemt om dig',
    exporting: 'Eksporterer...',
    downloadDataJson: 'Download data (JSON)',
    deleteChatHistory: 'Slet chathistorik',
    deleteChatHistoryDesc: 'Sletter alle dine sendte beskeder',
    deleting: 'Sletter...',
    deleteLocationData: 'Slet lokationsdata',
    deleteLocationDataDesc: 'Fjerner din gemt lokation og deaktiverer nærheds-funktionen',
    deleteMyAccount: 'Slet min konto',
    deleteMyAccountDesc: 'Sletter al din data permanent — kan ikke fortrydes',
    deleteAccountAndData: 'Slet konto og al data',
    gdprRightsNote: 'I henhold til GDPR har du ret til at tilgå, rette og slette dine personoplysninger.',
    legalDocsAdmin: 'Juridiske dokumenter (Admin)',
    legalDocsAdminDesc: 'Upload PDF for handelsbetingelser og privatlivspolitik',
    termsLabel: 'Handelsbetingelser',
    privacyLabel: 'Privatlivspolitik',
    viewCurrentPdf: 'Se nuværende PDF',
    uploading: 'Uploader...',
    replacePdf: 'Udskift PDF',
    uploadPdf: 'Upload PDF',
    areYouSure: 'Er du sikker?',
    confirmDeleteAllData: 'Dette sletter din konto og al tilknyttet data permanent. Handlingen kan ikke fortrydes.',
    confirmDeleteChat: 'Dette sletter alle dine sendte beskeder permanent.',
    confirmDeleteLocation: 'Dette fjerner din gemte lokation og deaktiverer nærheds-funktionen.',
    yesDelete: 'Ja, slet',
    pdfUploadedFor: 'PDF uploadet for',
    dataExported: 'Data eksporteret',
    accountAndDataDeleted: 'Konto og data slettet',
    chatHistoryDeleted: 'Chathistorik slettet',
    locationDataDeleted: 'Lokationsdata slettet',

    // ExpertDetail
    expertNotFound: 'Ekspert ikke fundet',
    expertProfile: 'Ekspert profil',
    specialties: 'Specialer',
    about: 'Om',
    availability: 'Tilgængelighed',
    noTimesSetUp: 'Ingen tider sat op',
    consultation: 'Konsultation',
    perHour: '/ time',
    bookConsultation: 'Book konsultation',
    daySun: 'Søn',

    // Booking
    chooseDate: 'Vælg dato',
    chooseTime: 'Vælg tidspunkt',
    confirmBooking: 'Bekræft booking',
    continueLabel: 'Fortsæt',
    noAvailableTimesThisDay: 'Ingen ledige tider denne dag',
    notesToExpert: 'Noter til eksperten (valgfrit)',
    notesToExpertPlaceholder: 'Skriv eventuelle noter eller spørgsmål...',
    total: 'Total',
    bookingConfirmed: 'Booking bekræftet!',
    bookingFailed: 'Kunne ikke oprette booking',
    stepOfThree: 'Trin {n} af 3',

    // AskQuestion
    categoryGeneral: 'Generelt',
    categoryCare: 'Pleje',
    categoryEquipment: 'Udstyr',
    categoryHealth: 'Sundhed',
    categoryTraining: 'Træning',
    categoryOther: 'Andet',
    sendQuestion: 'Send spørgsmål',
    chooseCategory: 'Vælg kategori',

    // SleepAdviceFeedback
    sleepLogBack: 'Søvnlog',
    suggestionNotFound: 'Forslaget blev ikke fundet.',
    yourSleepAdvice: 'Dit søvnråd',
    basedOn: 'Baseret på',
    feedbackHelpful: '👍 Det hjalp mig!',
    feedbackHelpfulDesc: 'Godt råd, vil prøve det',
    feedbackAlreadyTried: '🔄 Har allerede prøvet',
    feedbackAlreadyTriedDesc: 'Kender rådet, virker ikke for os',
    feedbackNotRelevant: '🤔 Ikke relevant for mig',
    feedbackNotRelevantDesc: 'Passer ikke til vores situation',
    feedbackNotHelpful: '👎 Hjalp ikke',
    feedbackNotHelpfulDesc: 'Prøvede det, ingen effekt',
    didThisAdviceHelp: 'Hjalp dette råd dig? 🙏',
    feedbackNotePlaceholder: 'Valgfrit: skriv gerne mere om hvad der virker eller ikke virker for jer...',
    sendFeedback: 'Send feedback',
    thanksForFeedback: 'Tak for din feedback!',
    feedbackHelpsUsImprove: 'Din tilbagemelding hjælper os med at give bedre og mere personlige råd næste gang. 💛',
    backToSleepLog: 'Tilbage til søvnlog',
    thanksForFeedbackToast: 'Tak for din feedback! 💛',
    somethingWentWrongTryAgainShort: 'Noget gik galt, prøv igen',

    // PregnancyWeeks
    nowBadge: 'Nu ✦',
    weekLabel: 'Uge',
    babySection: 'Babyen',
    yourBodySection: 'Din krop',
    tipSection: 'Tip',
    readMoreAboutWeek: 'Læs mere om uge',
    pregnancyWeekByWeek: 'Graviditet uge for uge',
    allWeeks: 'Alle uger',

    // Chat
    yesterdayPrefix: 'I går',
    noAccessToConversation: 'Ingen adgang til denne samtale.',
    reportLabel: 'Indberetning',
    noMessagesYet: 'Ingen beskeder endnu',
    sayHi: 'Sig hej!',
    writeMessagePlaceholder: 'Skriv en besked...',

    // MyQuestions
    closed: 'Lukket',
    myQuestions: 'Mine spørgsmål',
    askNewQuestion: 'Stil et nyt spørgsmål',
    noQuestionsYet: 'Du har ikke stillet nogen spørgsmål endnu',
    answerSingular: 'svar',
    answersPlural: 'svar',

    // PageNotFound
    pageNotFoundTitle: 'Siden findes ikke',
    pageNotFoundMessagePrefix: 'Siden',
    pageNotFoundMessageSuffix: 'kunne ikke findes i denne applikation.',
    adminNote: 'Admin-bemærkning',
    adminNoteBody: 'Dette kan betyde, at AI\'en endnu ikke har implementeret denne side. Bed den om at implementere den i chatten.',
    goHome: 'Gå til forsiden',

    // AddProfileSheet
    addProfileError: 'Kunne ikke oprette profil. Prøv igen.',
    createMomProfile: 'Opret 🤍 Mor-profil',
    createDadProfile: 'Opret 💙 Far-profil',
    addProfileSubtitle: 'Tilføj den anden forælder så I begge kan bruge appen',
    namePlaceholder: 'Navn',
    createProfile: 'Opret profil',
    creatingProfile: 'Opretter…',

    // AddChildSheet
    editChild: 'Rediger barn',
    addChild: 'Tilføj barn',
    childNameRequired: 'Barnets navn er påkrævet',
    childNamePlaceholder: 'Barnets navn',
    addChildError: 'Kunne ikke gemme barn. Prøv igen.',

    // NativeAuthScreen
    welcomeBack: 'Velkommen tilbage',
    createAccount: 'Opret konto',
    resetPassword: 'Nulstil adgangskode',
    forgotPasswordTitle: 'Glemt adgangskode?',
    verifyEmailTitle: 'Bekræft din email',
    loginSubtitle: 'Log ind for at fortsætte',
    signupSubtitle: 'Opret en konto for at komme i gang',
    emailLabel: 'Email',
    emailPlaceholder: 'din@email.dk',
    passwordPlaceholder: 'Din adgangskode',
    newPasswordPlaceholder: 'Ny adgangskode',
    forgotPasswordLink: 'Glemt adgangskode?',
    logIn: 'Log ind',
    signUp: 'Opret konto',
    noAccountYet: 'Har du ikke en konto?',
    alreadyHaveAccount: 'Har du allerede en konto?',
    continueWithGoogle: 'Fortsæt med Google',
    invalidCredentials: 'Forkert email eller adgangskode',
    accountCreatedCheckEmail: 'Konto oprettet! Tjek din email for at bekræfte.',
    enterValidEmailShort: 'Indtast en gyldig email',
    passwordTooShort: 'Adgangskoden skal være mindst 6 tegn',
    passwordsDoNotMatch: 'Adgangskoderne matcher ikke',
    sendResetLink: 'Send link til nulstilling',
    resetLinkSent: 'Link til nulstilling af adgangskode er sendt til din email',
    backToLogin: 'Tilbage til login',
    verifyEmailMessage: 'Vi har sendt en bekræftelseslink til din email. Klik på linket for at fortsætte.',
    resendEmail: 'Send email igen',
    emailResent: 'Email sendt igen',

    // DarkModeNudge
    dimmedLightMessage: 'Vi har skruet lyset ned',
    tapToSwitchDarkMode: 'Tryk her for at skifte til mørk tilstand 🌙',

    // PregnancyTab
    inspiredBy: 'Inspireret af',
    currentWeekLabel: 'Uge',

    // Footer
    footerContact: 'Kontakt',
    footerTerms: 'Handelsbetingelser',
    footerPrivacy: 'Privatlivspolitik',
    footerCookies: 'Cookiepolitik',
    comingSoon: 'Kommer snart',

    // WonderWeeksTab
    wonderWeekDefaultTitle: 'Tigerspring',
    wonderWeekDefaultBody: 'Tigerspring er perioder hvor dit barns hjerne udvikler sig hurtigt, hvilket kan medføre uro, gråd og søvnproblemer.',
    wonderWeekDefaultFootnote: 'Baseret på den anerkendte teori om tigerspring i babyers udvikling.',
    addDueDateInProfile: 'Tilføj terminsdato i profil',
    nowActive: 'Nu',
    inWeeksPrefix: 'om',
    inWeeksSuffix: 'uger',

    // DailyPersonalMessage
    dailyAffirmation: 'Daglig affirmation',

    // UserNotRegisteredError
    accessRestricted: 'Adgang begrænset',
    accessRestrictedDesc: 'Du er ikke registreret til at bruge denne applikation. Kontakt venligst app-administratoren for at anmode om adgang.',
    ifErrorYouCan: 'Hvis du mener dette er en fejl, kan du:',
    accessOptionVerifyAccount: 'Bekræfte at du er logget ind med den korrekte konto',
    accessOptionContactSupport: 'Kontakte app-administratoren for at få adgang',
    accessOptionTryDifferentAccount: 'Logge ud og ind igen',

    // NotificationBell
    notificationsHeading: 'Notifikationer',
    messagesCountSuffix: 'beskeder',
    noNotificationsYet: 'Ingen notifikationer endnu',

    // PregnancyWeekDetail
    pwdNoDataForWeek: 'Ingen data for uge',
    pwdHeaderLabel: 'Graviditet',
    pwdBabyThisWeek: 'Babyen denne uge',
    pwdSize: 'Størrelse',
    pwdWeight: 'Vægt',
    pwdMilestones: 'Milepæle',
    pwdBodyAndSymptoms: 'Din krop & dine symptomer',
    pwdTypicalSymptoms: 'Typiske symptomer',
    pwdNutritionHeading: 'Kost & ernæring',
    pwdTipsHeading: 'Tips til ugen',
    pwdEmotionalHeading: 'Følelser & velvære',
    pwdContactMidwifeIf: 'Kontakt jordemoder hvis...',
    pwdPrevious: 'Forrige',
    pwdNext: 'Næste',
    pwdWeekShort: 'Uge',
    pwdPackingListTitle: '📋 Den Ultimative Pakkeliste',
    pwdPackingListSub: 'Hent gratis PDF fra Lalatoto of Denmark',
    pwdDownload: 'Download',

    // PlanChooser
    choosePaymentMethod: 'Vælg betalingsmetode',
    pricingSubtitle: '59 kr. / måned · Ingen binding · Opsig når som helst',
    storeSubApple: 'Betal via din App Store-konto · Bedst til iPhone',
    storeSubGoogle: 'Betal via din Google-konto · Bedst til Android',
    subscriptionViaStore: 'Abonnement via',
    purchaseOnlyInApp: 'køb virker kun i appen. Platform:',
    noPackagesFound: 'Ingen tilgængelige pakker fundet. Prøv igen.',
    purchaseFailed: 'Købet mislykkedes. Prøv igen.',
    processingPurchase: 'Behandler køb…',
    selectPaymentMethod: 'Vælg en betalingsmetode',
    buyVia: 'Køb via',
    securePaymentNote: '🔒 Sikker betaling · Ingen binding · Annuller når som helst',
    oneMoment: 'Et øjeblik…',
    skipLimitedAccess: 'Spring over — fortsæt med begrænset adgang',
    openingPayment: 'Åbner betaling…',
    haveDiscountCode: 'Har du en rabatkode? (beta-test)',
    startPaymentFailed: 'Kunne ikke starte betaling. Prøv igen.',

    // AcceptInvite
    acceptInviteInvalidLink: 'Ugyldigt invitationslink.',
    acceptInviteChecking: 'Tjekker invitation…',
    acceptInviteConnecting: 'Forbinder dig…',
    acceptInviteWaiting: 'Vent venligst et øjeblik…',
    acceptInviteDone: 'Du er med i familien!',
    acceptInviteRedirecting: 'Du sendes videre til appen nu…',
    acceptInviteError: 'Noget gik galt',
    acceptInviteErrorMsg: 'Noget gik galt. Prøv igen eller kontakt support på hej@clubnosleep.com',

    // AdminEditor
    adminEditorTitle: 'Admin Editor',
    adminEditorSaved: 'Gemt!',
    adminEditorDeleted: 'Slettet',
    adminEditorNewPost: 'Nyt indlæg',
    adminEditorEditPrefix: 'Rediger',
    adminEditorBlog: 'Blog',
    adminEditorLegal: 'Juridisk indhold',
    adminEditorArticle: 'Artikel',
    adminEditorSaving: 'Gemmer...',
    adminEditorTitleField: 'Titel',
    adminEditorExcerpt: 'Uddrag (excerpt)',
    adminEditorAuthor: 'Forfatter',
    adminEditorImage: 'Billede',
    adminEditorUploading: 'Uploader...',
    adminEditorSelectImage: 'Vælg billede',
    adminEditorPublishDate: 'Publiceringsdato',
    adminEditorPublished: 'Publiceret',
    adminEditorHidden: 'Skjult',
    adminEditorCategory: 'Kategori',
    adminEditorTags: 'Tags (kommasepareret — fx tigerspring-1, tigerspring-2)',
    adminEditorExcerptArticle: 'Uddrag (vises i listen)',
    adminEditorOrder: 'Sorteringsrækkefølge',
    adminEditorType: 'Type',
    adminEditorContent: 'Indhold',
    adminEditorSavePost: 'Gem indlæg',
    adminEditorSupportBtn: 'Support',
    adminEditorNotificationsBtn: 'Notifikationer',
    adminEditorNewBtn: 'Ny',
    adminEditorBlogTab: 'Blog',
    adminEditorArticlesTab: 'Artikler',
    adminEditorLegalTab: 'Juridisk',
    adminEditorHelpTab: 'Hjælp',
    adminEditorSharingTab: 'Deling',
    adminEditorColorTab: 'Farvetema',
    adminEditorMilestonesTab: 'Milepæle',
    adminEditorDemoTab: 'Demo',
    adminEditorWonderWeeksTab: 'Tigerspring intro',
    adminEditorSharingIntro: 'Introtekst på "Deling & adgang"-siden',
    adminEditorSharingButton: 'Tekst på invitationsknap',
    adminEditorHelpAboutDa: 'Om appen (dansk)',
    adminEditorHelpAboutEn: 'Om appen (engelsk)',
    adminEditorHelpContact: 'Kontakt e-mail',
    adminEditorHelpPhone: 'Telefonnummer',
    adminEditorWwTitle: 'Overskrift',
    adminEditorWwBody: 'Brødtekst (stor tekst)',
    adminEditorWwFootnote: 'Fodnotetekst (lille tekst)',
    adminEditorDemoMode: 'Demo-tilstand',
    adminEditorDemoWarning: '⚠️ Demo-tilstand er aktiv — alle brugere har fuld adgang. Husk at slå det fra efter App Store-review.',
    adminEditorDemoDesc: 'Alle brugere får fuld adgang uden abonnement',
    adminEditorDemoUsedFor: 'Bruges typisk til App Store / Google Play review, hvor reviewere ikke har abonnement.',
    adminEditorLoading: 'Indlæser...',
    adminEditorNoPostsYet: 'Ingen indlæg endyu',

    // AdminLanding
    adminLandingTitle: 'Landing page admin',
    adminLandingPhones: '📱 iPhone mockup billeder',
    adminLandingPhonesDesc: 'Rediger billede-URLer for de to iPhone mockups på forsiden',
    adminLandingPhoneA: 'Telefon A (venstre):',
    adminLandingPhoneB: 'Telefon B (højre):',
    adminLandingButtonSavePhones: 'Gem telefoner',
    adminLandingIcons: '🖼️ Feature ikoner',
    adminLandingIconsDesc: 'Upload et billede (PNG/SVG) for hvert feature. Hvis intet billede er valgt vises standard-ikonet.',
    adminLandingButtonSaveIcons: 'Gem ikoner',
    adminLandingShopify: '🛍️ Shopify-synkronisering',
    adminLandingShopifyDesc: 'Henter produkter og blogindlæg fra Shopify ind i appen. Kør denne efter du har sat Shopify-credentials op, eller når du vil opdatere data manuelt.',
    adminLandingSyncNow: 'Synkroniser nu',
    adminLandingSyncing: 'Synkroniserer...',
    adminLandingSyncResult: 'Synkroniseret: {products} produkter, {blogs} blogindlæg',
    adminLandingSyncFailed: 'Synkronisering fejlede',
    adminLandingSleepAgent: '🌙 Søvnrådgiver AI — prompt',
    adminLandingSleepAgentDesc: 'Dette er instrukserne til den AI søvnrådgiver der vises i Søvnlog. Ændr prompten for at tilpasse rådgivningens tone og fokus.',
    adminLandingPromptPlaceholder: 'Skriv instrukser til søvnrådgiveren her...',
    adminLandingButtonSavePrompt: 'Gem søvnrådgiver prompt',
    adminLandingLoading: 'Loading...',
    adminLandingError: 'Fejl ved loading',
    adminLandingAdminRequired: 'Du skal være admin',

    // Checkout
    checkoutBelongMember: 'Bliv medlem',
    checkoutPricing: '59 kr. / måned · Ingen binding · Opsig når som helst',
    checkoutFeature1: 'Fuld adgang til alle tigerspring og milepæle',
    checkoutFeature2: 'Personlig AI-søvnrådgiver',
    checkoutFeature3: 'Kalender med påmindelser',
    checkoutFeature4: 'Mødregruppe og fællesskab',
    checkoutFeature5: 'Babyvenlige caféer i dit område',
    checkoutAlreadySubscribed: 'Du har allerede abonnement',
    checkoutFullAccess: 'Du har fuld adgang til alle funktioner.',
    checkoutBackButton: 'Tilbage til appen',
    checkoutBack: 'Tilbage',
    checkoutPreparing: 'Forbereder {store}…',
    checkoutProcessing: 'Behandler…',
    checkoutSubscribe: 'Abonner — 59 kr./md. →',
    checkoutSecurePayment: '🔒 Sikker betaling via {store} · Ingen binding · Annuller når som helst',
    checkoutHasDiscountCode: 'Har du en rabatkode? (beta-test)',
    checkoutOpeningPayment: 'Åbner betaling…',
    checkoutLoadError: 'Abonnementet kunne ikke indlæses fra {store}. Tjek din internetforbindelse og prøv igen.',

    // CheckoutSuccess
    checkoutSuccessTitle: 'Velkommen i klubben! 🌙',
    checkoutSuccessMessage: 'Din betaling er gennemført. For at aktivere din konto skal du oprette en bruger med den samme email du brugte ved betalingen.',
    checkoutSuccessStep1: 'Klik på "Opret konto" nedenfor',
    checkoutSuccessStep2: 'Brug den samme email som ved betalingen',
    checkoutSuccessStep3: 'Dit abonnement aktiveres automatisk',
    checkoutSuccessCreateAccount: 'Opret konto',
    checkoutSuccessOpenApp: 'Åbn appen',
    checkoutSuccessAlreadyHaveAccount: 'Har du allerede en konto?',
    checkoutSuccessLoginHere: 'Log ind her',
    checkoutSuccessBackToApp: 'Tilbage til appen',

    // Favorites
    favoritesTitle: 'Favoritter',
    favoritesEmpty: 'Ingen favoritter endnu',
    favoritesEmptyDesc: 'Gem produkter og artikler du kan lide ved at trykke på hjerte-ikonet',
    favoritesAll: 'Alle ({count})',
    favoritesProducts: 'Produkter ({count})',
    favoritesBlog: 'Blog ({count})',
    favoritesNoProducts: 'Ingen produkter gemt',
    favoritesNoBlog: 'Ingen blogindlæg gemt',
    favoritesRemoved: 'Fjernet fra favoritter',
    favoritesError: 'Noget gik galt',
    favoritesProduct: 'Produkt',
    favoritesBlogPost: 'Blogindlæg',
    favoritesArticle: 'Artikel',

    // Knowledge
    knowledgeTitle: 'Tigerspring',

    // Milestones
    milestonesTitle: 'Milepæle',

    // MyQuestions
    myQuestionsTitle: 'Mine spørgsmål',
    myQuestionsEmpty: 'Ingen spørgsmål endnu',
    myQuestionsEmptyDesc: 'Stil dit første spørgsmål til fællesskabet',
    myQuestionsAskNew: 'Stil et spørgsmål',
    myQuestionsOpen: 'Åben',
    myQuestionsAnswered: 'Besvaret',
    myQuestionsClosed: 'Lukket',

    // Privacy
    privacyBack: 'Tilbage',
    privacyTitle: 'Privatlivspolitik',
    privacyContent: 'Indhold ikke tilgængeligt endnu.',
    privacyLastUpdated: 'Senest opdateret:',

    // Terms
    termsBack: 'Tilbage',
    termsTitle: 'Handelsbetingelser',
    termsContent: 'Indhold ikke tilgængeligt endnu.',
    termsLastUpdated: 'Senest opdateret:',

    // AdminNotifications
    adminNotificationsTitle: 'Notifikationsregel',
    adminNotificationsNew: 'Ny notifikationsregel',
    adminNotificationsEdit: 'Rediger regel',
    adminNotificationsManual: 'Manuelt',
    adminNotificationsManualDesc: 'Send kun ved at klikke "Send nu"',
    adminNotificationsScheduled: 'Planlagt tid',
    adminNotificationsScheduledDesc: 'Send automatisk på et bestemt tidspunkt',
    adminNotificationsCalendar: 'Ny kalenderaftale',
    adminNotificationsCalendarDesc: 'Send når der oprettes en ny aftale i kalenderen',
    adminNotificationsBlog: 'Nyt blogindlæg',
    adminNotificationsBlogDesc: 'Send når der publiceres et nyt blogindlæg',
    adminNotificationsSleep: 'Søvnlog gemt',
    adminNotificationsSleepDesc: 'Send når en søvnlog er gemt',
    adminNotificationsQuestion: 'Nyt spørgsmål',
    adminNotificationsQuestionDesc: 'Send når en bruger stiller et nyt spørgsmål',
    adminNotificationsName: 'Navn (intern)',
    adminNotificationsNamePlaceholder: 'fx Morgenopdatering',
    adminNotificationsTrigger: 'Trigger — hvornår sendes den?',

    // AdminSupport
    adminSupportTitle: 'Support',
    adminSupportNoMessages: 'Ingen supportbeskeder endyu 🌙',
    adminSupportReplyLabel: 'Svar sendt!',
    adminSupportError: 'Fejl ved afsendelse',

    // AdminTermsPrivacy
    adminTermsPrivacyTitle: 'Juridisk indhold',
    adminTermsPrivacyTerms: 'Handelsbetingelser',
    adminTermsPrivacyPrivacy: 'Privatlivspolitik',
    adminTermsPrivacyLoading: 'Indlæser...',
    adminTermsPrivacyAccess: 'Adgang nægtet',
    adminTermsPrivacyAdminOnly: 'Kun admin kan få adgang',
    adminTermsPrivacyTitleField: 'Titel',
    adminTermsPrivacyContent: 'Indhold',
    adminTermsPrivacySaved: 'Gemt!',
    adminTermsPrivacyError: 'Fejl ved gemning',
    adminTermsPrivacySaving: 'Gemmer...',

    // AdminUsers
    adminUsersTitle: 'Brugere',
    adminUsersSearch: 'Søg på email eller navn...',
    adminUsersLoading: 'Indlæser...',
    adminUsersNoResults: 'Ingen brugere fundet',
    adminUsersTrial: 'Trial',
    adminUsersActive: 'Aktiv',
    adminUsersExpired: 'Udløbet',

    // AdminWonderWeeks
    adminWonderWeeksTitle: 'Tigerspring emojis',
    adminWonderWeeksDesc: 'Vælg emoji for hvert tigerspring. De vises på forsiden og i Knowledge-fanen.',
    adminWonderWeeksWonder: 'Tigerspring',
    adminWonderWeeksSave: 'Gem alle emojis',
    adminWonderWeeksSaved: 'Emojis gemt ✓',
    adminWonderWeeksAdminOnly: 'Kun for admins',

    // ColorThemeEditor
    colorThemeEditorName: 'Navn *',
    colorThemeEditorNamePlaceholder: 'fx Sand & Chokolade',
    colorThemeEditorDescription: 'Beskrivelse',
    colorThemeEditorDescPlaceholder: 'fx Klassisk og lunt',
    colorThemeEditorCoreColors: '🎨 6 kernefarver',
    colorThemeBg: 'Baggrund',
    colorThemeBgHint: 'Sidens baggrund (lys)',
    colorThemeCard: 'Kort',
    colorThemeCardHint: 'Kortbaggrund (lys)',
    colorThemePrimary: 'Primær',
    colorThemePrimaryHint: 'Knapper & fremhævning',
    colorThemeAccent: 'Accent',
    colorThemeAccentHint: 'Sekundær fremhævning',
    colorThemeText: 'Tekst',
    colorThemeTextHint: 'Primær tekstfarve (lys)',
    colorThemeDarkBg: 'Mørk baggrund',
    colorThemeDarkBgHint: 'Sidens baggrund (mørk)',
    colorThemePreview: '👁 Preview',
    colorThemeActive: 'Aktiv for brugere',
    colorThemeOrder: 'Rækkefølge',
    colorThemeCancel: 'Annuller',
    colorThemeSaveTheme: 'Gem tema',
    colorThemeSaving: 'Gemmer...',
    colorThemeSaved: 'Farvetema gemt! Brugerne vil se det nye tema ved næste åbning.',
    colorThemeChoose: 'Vælg appens farvetema',
    colorThemeChooseDesc: 'Temaet gælder for alle brugere af appen',

    // ColorThemePicker
    colorThemePickerTitle: 'Vælg appens farvetema',
    colorThemePickerDesc: 'Temaet gælder for alle brugere af appen',

    // MilestoneFrameEditor
    milestoneFrameEditorNew: 'Ny milepæl',
    milestoneFrameEditorEdit: 'Rediger milepæl',
    milestoneFrameEditorDeleted: 'Slettet',
    milestoneFrameEditorSaved: 'Gemt!',
    milestoneFrameEditorID: 'ID (unik nøgle)',
    milestoneFrameEditorIDPlaceholder: 'fx preg-12',
    milestoneFrameEditorCategory: 'Kategori',
    milestoneFrameEditorLabel: 'Label (kort)',
    milestoneFrameEditorLabelPlaceholder: 'fx 1 år',
    milestoneFrameEditorEmoji: 'Emoji',
    milestoneFrameEditorEmojiPlaceholder: '🎂',
    milestoneFrameEditorHeadline: 'Headline (stor tekst på sticker)',
    milestoneFrameEditorHeadlinePlaceholder: 'fx 1 år 🎉',
    milestoneFrameEditorSubline: 'Subline (lille tekst)',
    milestoneFrameEditorSublinePlaceholder: 'fx Tillykke med fødselsdagen!',
    milestoneFrameEditorBackground: 'Baggrund',
    milestoneFrameEditorAccent: 'Accent',
    milestoneFrameEditorTextColor: 'Tekst',
    milestoneFrameEditorSticker: 'Sticker-billede (erstatter emoji)',
    milestoneFrameEditorRemoveImage: 'Fjern billede',
    milestoneFrameEditorUploadSticker: 'Upload sticker-billede',
    milestoneFrameEditorOrder: 'Sorteringsrækkefølge',
    milestoneFrameEditorActive: 'Aktiv',
    milestoneFrameSaving: 'Gemmer...',
    milestoneFrameHeadlinePreview: 'Headline',
    milestoneFrameSublinePreview: 'Subline',

    // PushNotificationSender
    pushNotificationSenderTitle: 'Send push-notifikation',
    pushNotificationSenderTitleLabel: 'Titel',
    pushNotificationSenderTitlePlaceholder: 'fx. Nyt produkt i shoppen 🎉',
    pushNotificationSenderMessage: 'Besked',
    pushNotificationSenderMessagePlaceholder: 'fx. Vi har netop tilføjet en ny babypleje-pakke med 20% rabat...',
    pushNotificationSenderLink: 'Link (valgfrit)',
    pushNotificationSenderLinkPlaceholder: 'fx. /Shop',
    pushNotificationSenderButton: 'Send til alle brugere',
    pushNotificationSenderSending: 'Sender...',
    pushNotificationSenderError: 'Udfyld titel og besked',
    pushNotificationSenderSuccess: 'Notifikation sendt til {recipients} brugere!',
    pushNotificationSenderFailed: 'Noget gik galt – prøv igen',
  },

  en: {
    // Nav
    home: 'Home',
    menu: 'Menu',
    shop: 'Shop',
    blog: 'Blog',
    sleepLog: 'Sleep log',
    knowledge: 'Knowledge',
    community: 'Community',
    calendar: 'Calendar',
    profile: 'Profile',

    // Home
    goodDay: 'Good day, mom 🤍',
    dailyWord: "Today's word for you",
    fromBlog: 'From the blog',
    seeAll: 'See all →',
    affirmations: [
      "You are a wonderful mom — even on the days it doesn't feel that way. 🤍",
      "It's okay that the coffee is cold. You are warm and present, and that is enough.",
      "You don't need to do everything perfectly. You just need to do your best — and you are.",
      "Sleep deprivation is hard. The fact that you keep going is proof of your incredible strength.",
      "Your baby doesn't know what 'perfect' is. They only know they love you.",
      "Those who say motherhood is easy have never tried it. You've got this!",
      "Every little smile from your child is proof that you're doing it right.",
      "You are not alone. Thousands of moms are sitting right now feeling exactly the same.",
      "It's okay to need help. Asking for it is actually brave.",
      "Today you are enough. Tomorrow you are enough. Always you are enough.",
      "Your tears are not weakness — they are love that has overflowed.",
      "No handbook can prepare you for the love you feel. You are strong.",
      "You have done something incredible. You have created a human being. Remember that.",
      "Some days it's enough that everyone is alive and reasonably fed. 🙌",
      "You are your baby's favourite person in the whole world. Always.",
      "Even though you're tired, you are still there. That is love in its purest form.",
      "No mother is perfect. But you are the perfect mother for your child.",
      "A good mother is not one who never fails — but one who always tries again.",
      "Congratulations on surviving another night. You deserve a medal (and more coffee).",
      "Your love is the warmest place your child knows. 🧡",
      "Even the hard days shape you both into something stronger.",
      "You are more than 'just a mom'. You are an everyday hero.",
      "What you give your child today, they carry with them all their life.",
      "A barely-making-it day is still a day full of love.",
      "You handle more than you know. That is the most beautiful thing about you.",
      "Every hug, every feed, every sleep attempt — it counts.",
      "Motherhood is not a performance. It's a relationship. And yours is beautiful.",
      "You have not failed. You are in the middle of it.",
      "Tomorrow is a new chance. And you are already ready for it.",
      "You carry so much. But you carry it with love.",
    ],

    // Profile
    profileTitle: 'Profile',
    edit: 'Edit',
    editProfile: 'Edit profile',
    username: 'Username',
    displayName: 'Display name',
    city: 'City',
    childBirthdate: "Child's birthday",
    wonderWeekInfo: 'Used to calculate wonder weeks 🐯',
    saveChanges: 'Save changes',
    saving: 'Saving…',
    profileUpdated: 'Profile updated',
    favorites: 'Favorites',
    notifications: 'Notifications',
    questions: 'Questions',
    settings: 'Settings',
    help: 'Help',
    shareLocation: 'Share location',
    showAsVisible: 'Show me as visible',
    logOut: 'Log out',
    language: 'Language',
    chooseLanguage: 'Choose language',

    // Settings
    settingsTitle: 'Settings',
    password: 'Password',
    privacy: 'Privacy',
    theme: 'Theme',
    chooseTheme: 'Choose your preferred look',
    light: 'Light',
    dark: 'Dark',
    faq: 'Frequently asked questions',
    contactSupport: 'Contact support',
    deleteAccount: 'Delete account',
    blogAndArticles: 'Blog & Articles',
    changePassword: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    updatePassword: 'Update password',
    passwordMismatch: 'Passwords do not match',
    passwordUpdated: 'Password updated',
    deleteWarning: 'Are you sure? This action cannot be undone — all your data will be permanently deleted.',
    typeToConfirmDelete: 'Type DELETE to confirm',
    deleteConfirmWord: 'DELETE',
    deletePermanently: 'Delete my account permanently',
    faqQ1: 'How do I edit my profile?',
    faqA1: 'Go to your profile and tap "Edit".',
    faqQ2: 'How do I find a practitioner?',
    faqA2: 'Find a practitioner under the Community tab.',

    // Knowledge
    knowledgeTitle: 'Knowledge & Answers',
    searchPlaceholder: 'Search knowledge...',
    articles: 'Articles',
    noResults: 'No results for',
    noFaq: 'No FAQ yet',
    noQuestions: 'No questions yet',
    askQuestion: 'Ask a question',
    answered: 'Answered',
    open: 'Open',
    by: 'by',
    answers: 'answers',

    // Shop
    shopTitle: 'Shop',
    searchProducts: 'Search products...',
    noProducts: 'No products found',
    sortBy: 'Sort by',
    newest: 'Newest',
    priceLow: 'Price: Low to high',
    priceHigh: 'Price: High to low',
    filtersTitle: 'Filters & Sorting',
    outOfStock: 'Out of stock',
    catAll: 'All',
    catCare: 'Care',
    catAccessories: 'Accessories',
    catEquipment: 'Equipment',
    catBooks: 'Books',

    // Blog
    blogTitle: 'Search and find answers',
    searchBlog: 'What would you like to know more about?',
    noPosts: 'No posts found',
    allCategories: 'All',

    // Community
    nearMe: 'Near me',
    chats: 'Chats',
    practitioners: 'Practitioners',
    aboutUs: 'About us',
    onlyForMoms: 'Moms only',
    onlyForMomsDesc: 'The community feature is reserved for mom profiles. Our mission is to fight night loneliness among moms — a safe space just for them.',
    switchToMomProfile: 'Create a profile to get access.',
    location: 'Location',
    findNearby: 'Find people nearby',
    locationActive: 'Active',
    enableLocation: 'Enable',
    showMeVisible: 'Show me as visible to others',
    activeMomsInDenmark: 'Awake moms near you',
    activeNow: 'active now',
    visible: 'Visible',
    hidden: 'Hidden',
    you: 'You',
    othersActive: 'Others active',
    enableLocationToSee: 'Enable location to see who is nearby',
    noUsersNearby: 'No users nearby (20 km)',
    personWithin: 'person within 20 km',
    personsWithin: 'people within 20 km',
    noConversations: 'No conversations yet',
    startChatNearby: 'Start a chat with someone nearby',
    unknown: 'Unknown',
    findPractitioner: 'Find practitioner',
    showingInArea: 'Showing experts in your area',
    showingRecommended: 'Showing recommended practitioners',
    all: 'All',
    searchInMyArea: 'Search my area',
    noExpertsInArea: 'No experts found in your area',
    noExpertsAvailable: 'No experts available',
    showAllExperts: 'Show all experts',
    recommendedPractitioners: 'Recommended practitioners',
    locationConsentTitle: 'Location usage',
    locationConsentDesc: 'Enable location to discover nearby moms who are also awake. Your exact location is never shared with other users — only an approximate distance is shown (e.g. "2 km away").',
    locationConsentNote: 'Location is used solely to find nearby users. You can disable it at any time in settings.',
    noThanks: 'No thanks',
    activateLocation: 'Enable location',
    locationActivated: 'Location enabled',
    locationError: 'Could not get location',
    browserNoLocation: 'Your browser does not support location',

    // SleepLog
    sleepLogTitle: 'Sleep log',
    historyBtn: 'History',
    logTodayBtn: 'Log today',
    todayLog: "Today's log",
    nightSleep: 'Night sleep',
    nightWakings: 'Night wakings',
    naps: 'Naps',
    nap: 'Nap',
    howDidBabyFallAsleep: 'How did the baby fall asleep?',
    moodBeforeBed: 'Mood before bedtime',
    notes: 'Notes',
    notesPlaceholder: 'What happened today? Restless evening? New tooth?',
    addWaking: 'Add waking',
    addNap: 'Add nap',
    bedtime: 'Bedtime',
    fellAsleep: 'Fell asleep',
    wokeUp: 'Woke up',
    date: 'Date',
    ageMonths: 'Age (months)',
    agePlaceholder: 'e.g. 8',
    saveSleepLog: 'Save sleep log',
    saving: 'Saving...',
    sleepLogSaved: 'Sleep log saved ✓',
    getAiAdvice: 'Get AI sleep advice',
    updateAiAdvice: 'Update AI advice',
    updateAnalysis: 'Update analysis',
    aiAnalyzing: 'The AI expert is analysing your sleep data…',
    aiErrorMsg: "Couldn't fetch analysis right now. Try again in a moment — you're doing great!",
    aiErrorTitle: '💛 A loving note',
    noLogsYet: 'No logs yet',
    bedAt: 'Bed',
    wakings: 'waking',
    wakingsPlural: 'wakings',
    felAsleepIn: 'Settling time:',
    nightSleepDuration: 'Night sleep:',
    nightNap: 'night sleep',
    napTotal: 'naps',
    sleepMethodSelf: 'Self',
    sleepMethodNursing: 'Nursing',
    sleepMethodBottle: 'Bottle',
    sleepMethodRocking: 'Rocking',
    sleepMethodPram: 'Pram',
    sleepMethodParent: 'With parent',
    moodFresh: 'Fresh',
    moodLittleTired: 'A little tired',
    moodVeryTired: 'Very tired',
    moodOvertired: 'Overtired',
    wakingMethodNursing: 'Nursing',
    wakingMethodBottle: 'Bottle',
    wakingMethodRocking: 'Rocking',
    wakingMethodSing: 'Sung to sleep',
    wakingMethodPram: 'Pram',
    wakingMethodSelf: 'Self-settled',

    // AIChat
    aiChatTitle: 'Baby & Sleep Expert',
    aiOnline: 'AI assistant · Online',
    aiGreeting: 'Hi! I am here for you 🤍',
    aiSubtitle: 'Expert in baby sleep, breastfeeding and child development. Ask me anything!',
    aiSuggestion1: 'How do I help my baby sleep better?',
    aiSuggestion2: 'What is sleep regression?',
    aiSuggestion3: 'My baby only sleeps 20 min at a time — help!',
    aiPlaceholder: 'Write your question…',
    aiDisclaimer: 'The AI assistant can make mistakes and does not replace medical advice.',
    backLabel: 'Go back',
    sendLabel: 'Send message',

    // Community / shared
    version: 'Version 1.0.0',
    v1: 'v1.0',

    // Profile extra
    momProfileLabel: 'Mom profile · Community access',
    dadProfileLabel: 'Dad profile · Sleep log',
    genderLabel: 'Gender',
    female: 'Female',
    male: 'Male',
    genderLocked: 'Gender cannot be changed after selection',
    myDataPrivacy: 'My data & privacy',
    helpAndContact: 'Help & contact',
    aboutApp: 'About the app',
    writeToUs: 'Contact us',
    callUs: 'Call us',

    // Settings extra
    loading: 'Loading...',
    noFaqAvailable: 'No FAQ available yet.',
    noSupportInfo: 'No support info available yet.',
    noPrivacyPolicy: 'No privacy policy available yet.',

    // Shop extra
    categoryLabel: 'Category',
    productsLabel: 'products',
    categoriesTitle: 'Categories',
    filtersAndSorting: 'Filters & Sorting',

    // Onboarding
    whoAreYou: 'Who are you?',
    chooseRoleSubtitle: 'Choose your role in the family',
    welcomeTitle: 'Welcome to LALATOTO',
    welcomeSubtitle: 'Create your profile and accept the terms',
    whereDoYouLive: 'Where do you live?',
    findNearbyMoms: 'Find moms near you',
    aboutYourChild: 'About your child',
    calculateWonderWeeksSubtitle: 'So we can calculate wonder weeks for you',
    lalatotoBuiltForFamily: 'LALATOTO is built for the whole family. Choose your role so we can tailor the experience for you.',
    mom: 'Mom',
    dad: 'Dad',
    momDesc: 'Community, sleep log & more',
    dadDesc: 'Sleep log & knowledge',
    nightLonelinessTitle: '🌙 Night loneliness',
    nightLonelinessDesc: 'Our night loneliness space is a safe space exclusively for moms — for those awake at night who need to know they are not alone.',
    yourName: 'Your name',
    namePlaceholder: 'Name...',
    usernameLabel: 'Username',
    usernameHint: 'Only letters, numbers and underscores',
    uploadingLabel: 'Uploading...',
    addProfilePic: 'Add profile picture (optional)',
    iAcceptTerms: 'I accept the',
    termsLinkLabel: 'terms of service',
    privacyLinkLabel: 'privacy policy',
    termsTitle: 'Terms of service',
    privacyTitle: 'Privacy policy',
    yourCity: 'Your city',
    cityDesc: 'We use your city to show you other moms nearby — completely optional.',
    cityPlaceholder: 'e.g. Copenhagen, Aarhus...',
    childBirthdateLabel: "Child's birth date",
    orLabel: 'or',
    dueDateLabel: 'Due date (if not born yet)',
    skip: 'Skip',
    back: 'Back',
    getStarted: 'Get started 🎉',
    next: 'Next',
    errorChooseRole: 'Choose whether you are a mom or dad',
    errorEnterName: 'Enter your name',
    errorChooseUsername: 'Choose a username',
    errorUsernameMin: 'At least 3 characters',
    errorAcceptTerms: 'You must accept the terms of service',
    errorAcceptPrivacy: 'You must accept the privacy policy',
    usernameOnlyChars: 'Only letters, numbers and underscores',

    // ChildDevelopmentCard
    dueIn: 'Due in',
    yourChildIs: 'Your child is',
    old: 'old',
    untilDue: 'until due date',
    weekSingular: 'week',
    weekPlural: 'weeks',
    daySingular: 'day',
    dayPlural: 'days',
    monthsShort: 'mo',
    hoursShort: 'h',
    minutesShort: 'm',

    // SleepSummaryCard
    sleepLastNight: 'Sleep last night',
    wakingSingular: 'waking',
    wakingPlural: 'wakings',
    logSleepCta: 'Log sleep →',

    // UpcomingEventCard
    nextAppointment: 'Next appointment',
    today: 'Today',
    tomorrow: 'Tomorrow',
    addAppointmentCta: 'Add appointment →',

    // SleepAdviceCard
    sleepAdviceTitle: 'Sleep advice from the expert',
    seeSleepLog: 'See sleep log →',
    basedOnLogs: 'Based on your last',
    logsLabel: 'logs',

    // AIRelevantPosts
    relevantForYou: 'Relevant for you',
    seeAll: 'See all →',

    // WonderWeekCard
    wonderWeekActiveLabel: 'WONDER WEEK',
    wonderWeekActiveNow: 'ACTIVE NOW',
    nextLeapIn: 'Next leap in',
    progress: 'Progress',
    weeksLeft: 'week(s) left',
    almostOver: 'Almost over',
    approx: 'approx.',
    hideDetails: 'Hide details',
    seeSigns: 'See signs & tips',
    typicalSigns: 'Typical signs',
    tipsForYou: 'Tips for you',
    readMoreWonderWeeks: 'Read more about wonder weeks',
    getReadyLeap: 'Get ready – your child is almost ready for their next big leap 🌱',

    // Calendar
    calendarTitle: 'Calendar',
    eventCreated: 'Appointment created',
    eventDeleted: 'Appointment deleted',
    fillTitleAndTime: 'Fill in title and start time',
    noEventsToday: 'No appointments today',
    addEvent: 'Add',
    newEvent: 'New appointment',
    eventTitle: 'Title *',
    eventStart: 'Start *',
    eventEnd: 'End (optional)',
    eventDescription: 'Description (optional)',
    saveEvent: 'Save appointment',
    calendarReminderNote: '📲 You will be notified the day before and 30 min before the appointment',
    eventTitlePlaceholder: 'e.g. doctor visit, vaccination...',
    eventDescPlaceholder: 'Optional address or notes...',
    weekdaysShort: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],

    // Landing
    landingOpenApp: 'Open app →',
    landingLogIn: 'Log in',
    landingBecomeMember: 'Become a member',
    landingPreviewPaymentAlert: 'Payment only works from the published app, not from the preview.',
    landingHero1Title1: 'For you who are awake,',
    landingHero1Title2: 'when the rest of the world sleeps.',
    landingHero1P1: 'There is a very special form of loneliness in motherhood. A loneliness that creeps in at night, when your baby is awake again and the rest of the world is quiet;',
    landingHero1P1Bold: 'Night loneliness.',
    landingHero1P2Bold: 'CLUB NO SLEEP',
    landingHero1P2: 'is a Danish app created for exactly these moments. Because no one should feel alone in motherhood.',
    landingAppStoreLabel: 'App Store',
    landingDownloadNow: 'Download now',
    landingIWantToLook: 'I want to look →',
    landingFullAccess: 'FULL ACCESS',
    landingMembership: 'Membership',
    landingPerMonth: '/ month',
    landingFeature1: 'AI sleep advice',
    landingFeature2: 'Wonder weeks & development guide',
    landingFeature3: 'Chat with other parents',
    landingFeature4: 'Expert booking',
    landingFeature5: '100+ knowledge articles',
    landingFeature6: 'Shared calendar with partner',
    landingFeature7: 'Notifications & milestones',
    landingGetStarted: 'Get Started ✨',
    landingKlubTitle: 'Join the club',
    landingKlubP1: 'We have been there.',
    landingKlubP1b: 'Where the nights are hard, the days are long, and nobody completely understands what you\'re going through. Where Dad sleeps on the couch and Mom sleeps sitting up. Where the fear of night already starts in the afternoon.',
    landingKlubP1c: 'CLUB NO SLEEP was created for you, who are looking for a place to be reflected in and find others who are awake with you.',
    landingKlubP2: 'Join the club. For your own sake, and for all the mothers who feel alone right now. Together we can reduce loneliness in motherhood.',
    landingKlubSig: 'With warmth and hugs from Sara & Nicolaj',
    landingFeaturesTitle: 'What you\'ll find in the app',
    landingPartnerTitle1: 'You don\'t have to',
    landingPartnerTitle2: 'do it all alone',
    landingPartnerP: 'One account always includes one free additional user, so you can choose to share everything from sleep log, calendar and wonder weeks with your partner. Together it\'s often easier.',
    landingSharePartner: 'Share with partner',
    landingYou: '(you)',
    landingManage: 'Manage',
    landingPartner: '(partner)',
    landingActive: 'Active',
    landingInvitePartner: 'Invite partner',
    landingSharedCalendar: 'Shared calendar',
    landingOsteopathEvent: 'Osteopath at 10:00',
    landingCafeEvent: 'Maternity café at 2:00 PM',
    landingFooterTagline: 'Your safe harbor as a new parent — sleep, community and knowledge all in one place.',
    landingLegal: 'Legal',
    landingTerms: 'Terms of service',
    landingPrivacy: 'Privacy policy',
    landingGetTheApp: 'Get the app',
    landingCopyright: '© 2025 Club No Sleep · All rights reserved',
    landingMadeWithLove: 'Made with ❤️ in Denmark',

    // AboutUs
    editLabelPrefix: 'Edit',
    saved: 'Saved',
    save: 'Save',
    cancel: 'Cancel',
    funFactsAboutMe: 'fun facts about me',
    meetTheFamily: 'Meet the family',
    adminEditHint: '✏️ Click to edit',
    contactUs: 'Contact us',
    writeToUs: 'Write to us 💬',
    loginToMessage: 'Log in to send us a message.',

    // FamilyInvite
    familySleepLog: 'Sleep log',
    familyWonderWeeks: 'Wonder weeks',
    familyCalendar: 'Calendar',
    familyKnowledge: 'Knowledge & articles',
    familyNotifWonderWeeks: 'Notifications about wonder weeks',
    familyNotifSleepLog: 'Notifications about the sleep log',
    familyNotifAppointments: 'Notifications about appointments',
    fillEmailAndTitle: 'Fill in the email and choose a title',
    enterValidEmail: 'Enter a valid email',
    invitationDeleted: 'Invitation deleted',
    somethingWentWrongTryAgain: 'Something went wrong. Please try again.',
    statusAccepted: 'Accepted',
    statusDeclined: 'Declined',
    statusPending: 'Pending',
    sharingAndAccess: 'Sharing & access',
    sentInvitations: 'Sent invitations',
    noInvitationsYet: 'No invitations yet',
    inviteFamilyMember: 'Invite family member',
    whatToShare: 'What should be shared?',
    notifications: 'Notifications',
    sending: 'Sending…',
    sendInvitation: 'Send invitation',
    invitationSentToPrefix: 'Invitation sent to',
    familyInviteIntroDefault: 'Invite a family member to stay in the loop — they get access to exactly what you choose, and can receive notifications about your child\'s milestones.',
    familyMemberEmailLabel: 'Family member\'s email',
    familyMemberEmailPlaceholder: 'e.g. grandma@gmail.com',
    titleLabel: 'Title',
    titlePlaceholder: 'e.g. Grandma, Auntie Lise...',
    titleFar: 'Dad',
    titleFarmor: 'Grandma (paternal)',
    titleFarfar: 'Grandpa (paternal)',
    titleMormor: 'Grandma (maternal)',
    titleMorfar: 'Grandpa (maternal)',
    titleSoster: 'Sister',
    titleBror: 'Brother',
    titleVeninde: 'Friend (f)',
    titleVen: 'Friend',

    // MyData
    myDataPrivacy: 'My data & privacy',
    exportMyData: 'Export my data',
    exportMyDataDesc: 'Download all the data we have stored about you',
    exporting: 'Exporting...',
    downloadDataJson: 'Download data (JSON)',
    deleteChatHistory: 'Delete chat history',
    deleteChatHistoryDesc: 'Deletes all your sent messages',
    deleting: 'Deleting...',
    deleteLocationData: 'Delete location data',
    deleteLocationDataDesc: 'Removes your saved location and disables the proximity feature',
    deleteMyAccount: 'Delete my account',
    deleteMyAccountDesc: 'Permanently deletes all your data — this cannot be undone',
    deleteAccountAndData: 'Delete account and all data',
    gdprRightsNote: 'Under GDPR, you have the right to access, correct, and delete your personal data.',
    legalDocsAdmin: 'Legal documents (Admin)',
    legalDocsAdminDesc: 'Upload a PDF for the terms of service and privacy policy',
    termsLabel: 'Terms of service',
    privacyLabel: 'Privacy policy',
    viewCurrentPdf: 'View current PDF',
    uploading: 'Uploading...',
    replacePdf: 'Replace PDF',
    uploadPdf: 'Upload PDF',
    areYouSure: 'Are you sure?',
    confirmDeleteAllData: 'This will permanently delete your account and all associated data. This action cannot be undone.',
    confirmDeleteChat: 'This will permanently delete all your sent messages.',
    confirmDeleteLocation: 'This will remove your saved location and disable the proximity feature.',
    yesDelete: 'Yes, delete',
    pdfUploadedFor: 'PDF uploaded for',
    dataExported: 'Data exported',
    accountAndDataDeleted: 'Account and data deleted',
    chatHistoryDeleted: 'Chat history deleted',
    locationDataDeleted: 'Location data deleted',

    // ExpertDetail
    expertNotFound: 'Expert not found',
    expertProfile: 'Expert profile',
    specialties: 'Specialties',
    about: 'About',
    availability: 'Availability',
    noTimesSetUp: 'No times set up',
    consultation: 'Consultation',
    perHour: '/ hour',
    bookConsultation: 'Book consultation',
    daySun: 'Sun',

    // Booking
    chooseDate: 'Choose a date',
    chooseTime: 'Choose a time',
    confirmBooking: 'Confirm booking',
    continueLabel: 'Continue',
    noAvailableTimesThisDay: 'No available times this day',
    notesToExpert: 'Notes for the expert (optional)',
    notesToExpertPlaceholder: 'Write any notes or questions...',
    total: 'Total',
    bookingConfirmed: 'Booking confirmed!',
    bookingFailed: 'Could not create the booking',
    stepOfThree: 'Step {n} of 3',

    // AskQuestion
    categoryGeneral: 'General',
    categoryCare: 'Care',
    categoryEquipment: 'Equipment',
    categoryHealth: 'Health',
    categoryTraining: 'Training',
    categoryOther: 'Other',
    sendQuestion: 'Send question',
    chooseCategory: 'Choose category',

    // SleepAdviceFeedback
    sleepLogBack: 'Sleep log',
    suggestionNotFound: 'The suggestion could not be found.',
    yourSleepAdvice: 'Your sleep advice',
    basedOn: 'Based on',
    feedbackHelpful: '👍 It helped me!',
    feedbackHelpfulDesc: 'Good advice, will try it',
    feedbackAlreadyTried: '🔄 Already tried this',
    feedbackAlreadyTriedDesc: "Know the advice, doesn't work for us",
    feedbackNotRelevant: '🤔 Not relevant for me',
    feedbackNotRelevantDesc: "Doesn't fit our situation",
    feedbackNotHelpful: "👎 Didn't help",
    feedbackNotHelpfulDesc: 'Tried it, no effect',
    didThisAdviceHelp: 'Did this advice help you? 🙏',
    feedbackNotePlaceholder: 'Optional: feel free to write more about what works or doesn\'t work for you...',
    sendFeedback: 'Send feedback',
    thanksForFeedback: 'Thanks for your feedback!',
    feedbackHelpsUsImprove: 'Your feedback helps us give better, more personalized advice next time. 💛',
    backToSleepLog: 'Back to sleep log',
    thanksForFeedbackToast: 'Thanks for your feedback! 💛',
    somethingWentWrongTryAgainShort: 'Something went wrong, please try again',

    // PregnancyWeeks
    nowBadge: 'Now ✦',
    weekLabel: 'Week',
    babySection: 'Baby',
    yourBodySection: 'Your body',
    tipSection: 'Tip',
    readMoreAboutWeek: 'Read more about week',
    pregnancyWeekByWeek: 'Pregnancy week by week',
    allWeeks: 'All weeks',

    // Chat
    yesterdayPrefix: 'Yesterday',
    noAccessToConversation: 'No access to this conversation.',
    reportLabel: 'Report',
    noMessagesYet: 'No messages yet',
    sayHi: 'Say hi!',
    writeMessagePlaceholder: 'Write a message...',

    // MyQuestions
    closed: 'Closed',
    myQuestions: 'My questions',
    askNewQuestion: 'Ask a new question',
    noQuestionsYet: "You haven't asked any questions yet",
    answerSingular: 'answer',
    answersPlural: 'answers',

    // PageNotFound
    pageNotFoundTitle: 'Page Not Found',
    pageNotFoundMessagePrefix: 'The page',
    pageNotFoundMessageSuffix: 'could not be found in this application.',
    adminNote: 'Admin Note',
    adminNoteBody: "This could mean that the AI hasn't implemented this page yet. Ask it to implement it in the chat.",
    goHome: 'Go Home',

    // AddProfileSheet
    addProfileError: 'Could not create profile. Please try again.',
    createMomProfile: 'Create 🤍 Mom profile',
    createDadProfile: 'Create 💙 Dad profile',
    addProfileSubtitle: 'Add the other parent so you can both use the app',
    namePlaceholder: 'Name',
    createProfile: 'Create profile',
    creatingProfile: 'Creating…',

    // AddChildSheet
    editChild: 'Edit child',
    addChild: 'Add child',
    childNameRequired: "Child's name is required",
    childNamePlaceholder: "Child's name",
    addChildError: 'Could not save the child. Please try again.',

    // NativeAuthScreen
    welcomeBack: 'Welcome back',
    createAccount: 'Create account',
    resetPassword: 'Reset password',
    forgotPasswordTitle: 'Forgot password?',
    verifyEmailTitle: 'Verify your email',
    loginSubtitle: 'Log in to continue',
    signupSubtitle: 'Create an account to get started',
    emailLabel: 'Email',
    emailPlaceholder: 'you@email.com',
    passwordPlaceholder: 'Your password',
    newPasswordPlaceholder: 'New password',
    forgotPasswordLink: 'Forgot password?',
    logIn: 'Log in',
    signUp: 'Sign up',
    noAccountYet: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    continueWithGoogle: 'Continue with Google',
    invalidCredentials: 'Incorrect email or password',
    accountCreatedCheckEmail: 'Account created! Check your email to confirm.',
    enterValidEmailShort: 'Enter a valid email',
    passwordTooShort: 'The password must be at least 6 characters',
    passwordsDoNotMatch: 'Passwords do not match',
    sendResetLink: 'Send reset link',
    resetLinkSent: 'A password reset link has been sent to your email',
    backToLogin: 'Back to login',
    verifyEmailMessage: 'We have sent a verification link to your email. Click the link to continue.',
    resendEmail: 'Resend email',
    emailResent: 'Email resent',

    // DarkModeNudge
    dimmedLightMessage: "We've turned down the lights",
    tapToSwitchDarkMode: 'Tap here to switch to dark mode 🌙',

    // PregnancyTab
    inspiredBy: 'Inspired by',
    currentWeekLabel: 'Week',

    // Footer
    footerContact: 'Contact',
    footerTerms: 'Terms of trade',
    footerPrivacy: 'Privacy policy',
    footerCookies: 'Cookie policy',
    comingSoon: 'Coming soon',

    // WonderWeeksTab
    wonderWeekDefaultTitle: 'Wonder weeks',
    wonderWeekDefaultBody: "Wonder weeks are periods when your child's brain develops rapidly, which can cause fussiness, crying and sleep problems.",
    wonderWeekDefaultFootnote: "Based on the well-known theory of wonder weeks in babies' development.",
    addDueDateInProfile: 'Add due date in profile',
    nowActive: 'Now',
    inWeeksPrefix: 'in',
    inWeeksSuffix: 'weeks',

    // DailyPersonalMessage
    dailyAffirmation: 'Daily affirmation',

    // UserNotRegisteredError
    accessRestricted: 'Access Restricted',
    accessRestrictedDesc: 'You are not registered to use this application. Please contact the app administrator to request access.',
    ifErrorYouCan: 'If you believe this is an error, you can:',
    accessOptionVerifyAccount: 'Verify you are logged in with the correct account',
    accessOptionContactSupport: 'Contact the app administrator for access',
    accessOptionTryDifferentAccount: 'Try logging out and back in again',

    // NotificationBell
    notificationsHeading: 'Notifications',
    messagesCountSuffix: 'messages',
    noNotificationsYet: 'No notifications yet',

    // PregnancyWeekDetail
    pwdNoDataForWeek: 'No data for week',
    pwdHeaderLabel: 'Pregnancy',
    pwdBabyThisWeek: 'Baby this week',
    pwdSize: 'Size',
    pwdWeight: 'Weight',
    pwdMilestones: 'Milestones',
    pwdBodyAndSymptoms: 'Your body & symptoms',
    pwdTypicalSymptoms: 'Typical symptoms',
    pwdNutritionHeading: 'Diet & nutrition',
    pwdTipsHeading: 'Tips for the week',
    pwdEmotionalHeading: 'Emotions & wellbeing',
    pwdContactMidwifeIf: 'Contact your midwife if...',
    pwdPrevious: 'Previous',
    pwdNext: 'Next',
    pwdWeekShort: 'Week',
    pwdPackingListTitle: '📋 The Ultimate Packing List',
    pwdPackingListSub: 'Get the free PDF from Lalatoto of Denmark',
    pwdDownload: 'Download',

    // PlanChooser
    choosePaymentMethod: 'Choose payment method',
    pricingSubtitle: 'DKK 59 / month · No commitment · Cancel anytime',
    storeSubApple: 'Pay via your App Store account · Best for iPhone',
    storeSubGoogle: 'Pay via your Google account · Best for Android',
    subscriptionViaStore: 'Subscription via',
    purchaseOnlyInApp: 'purchases only work in the app. Platform:',
    noPackagesFound: 'No available packages found. Please try again.',
    purchaseFailed: 'The purchase failed. Please try again.',
    processingPurchase: 'Processing purchase…',
    selectPaymentMethod: 'Select a payment method',
    buyVia: 'Buy via',
    securePaymentNote: '🔒 Secure payment · No commitment · Cancel anytime',
    oneMoment: 'One moment…',
    skipLimitedAccess: 'Skip — continue with limited access',
    openingPayment: 'Opening payment…',
    haveDiscountCode: 'Have a discount code? (beta testers)',
    startPaymentFailed: 'Could not start payment. Please try again.',

    // AcceptInvite
    acceptInviteInvalidLink: 'Invalid invitation link.',
    acceptInviteChecking: 'Checking invitation…',
    acceptInviteConnecting: 'Connecting you…',
    acceptInviteWaiting: 'Please wait a moment…',
    acceptInviteDone: 'You\'re part of the family!',
    acceptInviteRedirecting: 'You\'re being redirected to the app now…',
    acceptInviteError: 'Something went wrong',
    acceptInviteErrorMsg: 'Something went wrong. Try again or contact support at hej@clubnosleep.com',

    // AdminEditor
    adminEditorTitle: 'Admin Editor',
    adminEditorSaved: 'Saved!',
    adminEditorDeleted: 'Deleted',
    adminEditorNewPost: 'New post',
    adminEditorEditPrefix: 'Edit',
    adminEditorBlog: 'Blog',
    adminEditorLegal: 'Legal content',
    adminEditorArticle: 'Article',
    adminEditorSaving: 'Saving...',
    adminEditorTitleField: 'Title',
    adminEditorExcerpt: 'Excerpt',
    adminEditorAuthor: 'Author',
    adminEditorImage: 'Image',
    adminEditorUploading: 'Uploading...',
    adminEditorSelectImage: 'Select image',
    adminEditorPublishDate: 'Publication date',
    adminEditorPublished: 'Published',
    adminEditorHidden: 'Hidden',
    adminEditorCategory: 'Category',
    adminEditorTags: 'Tags (comma-separated — e.g. tigerspring-1, tigerspring-2)',
    adminEditorExcerptArticle: 'Excerpt (shown in list)',
    adminEditorOrder: 'Sort order',
    adminEditorType: 'Type',
    adminEditorContent: 'Content',
    adminEditorSavePost: 'Save post',
    adminEditorSupportBtn: 'Support',
    adminEditorNotificationsBtn: 'Notifications',
    adminEditorNewBtn: 'New',
    adminEditorBlogTab: 'Blog',
    adminEditorArticlesTab: 'Articles',
    adminEditorLegalTab: 'Legal',
    adminEditorHelpTab: 'Help',
    adminEditorSharingTab: 'Sharing',
    adminEditorColorTab: 'Color theme',
    adminEditorMilestonesTab: 'Milestones',
    adminEditorDemoTab: 'Demo',
    adminEditorWonderWeeksTab: 'Wonder weeks intro',
    adminEditorSharingIntro: 'Intro text on "Sharing & access" page',
    adminEditorSharingButton: 'Invitation button text',
    adminEditorHelpAboutDa: 'About the app (Danish)',
    adminEditorHelpAboutEn: 'About the app (English)',
    adminEditorHelpContact: 'Contact email',
    adminEditorHelpPhone: 'Phone number',
    adminEditorWwTitle: 'Title',
    adminEditorWwBody: 'Body text (large text)',
    adminEditorWwFootnote: 'Footnote text (small text)',
    adminEditorDemoMode: 'Demo mode',
    adminEditorDemoWarning: '⚠️ Demo mode is active — all users have full access. Remember to disable it after App Store review.',
    adminEditorDemoDesc: 'All users get full access without subscription',
    adminEditorDemoUsedFor: 'Typically used for App Store / Google Play review, where reviewers don\'t have a subscription.',
    adminEditorLoading: 'Loading...',
    adminEditorNoPostsYet: 'No posts yet',

    // AdminLanding
    adminLandingTitle: 'Landing page admin',
    adminLandingPhones: '📱 iPhone mockup images',
    adminLandingPhonesDesc: 'Edit image URLs for the two iPhone mockups on the landing page',
    adminLandingPhoneA: 'Phone A (left):',
    adminLandingPhoneB: 'Phone B (right):',
    adminLandingButtonSavePhones: 'Save phones',
    adminLandingIcons: '🖼️ Feature icons',
    adminLandingIconsDesc: 'Upload an image (PNG/SVG) for each feature. If no image is selected, the default icon is shown.',
    adminLandingButtonSaveIcons: 'Save icons',
    adminLandingShopify: '🛍️ Shopify synchronization',
    adminLandingShopifyDesc: 'Import products and blog posts from Shopify into the app. Run this after setting up Shopify credentials, or when you want to manually update data.',
    adminLandingSyncNow: 'Sync now',
    adminLandingSyncing: 'Syncing...',
    adminLandingSyncResult: 'Synced: {products} products, {blogs} blog posts',
    adminLandingSyncFailed: 'Sync failed',
    adminLandingSleepAgent: '🌙 Sleep Advisor AI — prompt',
    adminLandingSleepAgentDesc: 'These are the instructions for the AI sleep advisor shown in Sleep Log. Modify the prompt to tailor the advice tone and focus.',
    adminLandingPromptPlaceholder: 'Write instructions for the sleep advisor here...',
    adminLandingButtonSavePrompt: 'Save sleep advisor prompt',
    adminLandingLoading: 'Loading...',
    adminLandingError: 'Error loading',
    adminLandingAdminRequired: 'You must be an admin',

    // Checkout
    checkoutBelongMember: 'Become a member',
    checkoutPricing: 'DKK 59 / month · No commitment · Cancel anytime',
    checkoutFeature1: 'Full access to all wonder weeks and milestones',
    checkoutFeature2: 'Personal AI sleep advisor',
    checkoutFeature3: 'Calendar with reminders',
    checkoutFeature4: 'Mom community',
    checkoutFeature5: 'Baby-friendly cafes in your area',
    checkoutAlreadySubscribed: 'You already have a subscription',
    checkoutFullAccess: 'You have full access to all features.',
    checkoutBackButton: 'Back to app',
    checkoutBack: 'Back',
    checkoutPreparing: 'Preparing {store}…',
    checkoutProcessing: 'Processing…',
    checkoutSubscribe: 'Subscribe — DKK 59/mo. →',
    checkoutSecurePayment: '🔒 Secure payment via {store} · No commitment · Cancel anytime',
    checkoutHasDiscountCode: 'Have a discount code? (beta test)',
    checkoutOpeningPayment: 'Opening payment…',
    checkoutLoadError: 'Could not load the subscription from {store}. Check your internet connection and try again.',

    // CheckoutSuccess
    checkoutSuccessTitle: 'Welcome to the club! 🌙',
    checkoutSuccessMessage: 'Your payment has been processed. To activate your account, you need to create a user with the same email you used for payment.',
    checkoutSuccessStep1: 'Click "Create account" below',
    checkoutSuccessStep2: 'Use the same email as during payment',
    checkoutSuccessStep3: 'Your subscription will be activated automatically',
    checkoutSuccessCreateAccount: 'Create account',
    checkoutSuccessOpenApp: 'Open app',
    checkoutSuccessAlreadyHaveAccount: 'Already have an account?',
    checkoutSuccessLoginHere: 'Log in here',
    checkoutSuccessBackToApp: 'Back to app',

    // Favorites
    favoritesTitle: 'Favorites',
    favoritesEmpty: 'No favorites yet',
    favoritesEmptyDesc: 'Save products and articles you like by tapping the heart icon',
    favoritesAll: 'All ({count})',
    favoritesProducts: 'Products ({count})',
    favoritesBlog: 'Blog ({count})',
    favoritesNoProducts: 'No products saved',
    favoritesNoBlog: 'No blog posts saved',
    favoritesRemoved: 'Removed from favorites',
    favoritesError: 'Something went wrong',
    favoritesProduct: 'Product',
    favoritesBlogPost: 'Blog post',
    favoritesArticle: 'Article',

    // Knowledge
    knowledgeTitle: 'Wonder weeks',

    // Milestones
    milestonesTitle: 'Milestones',

    // MyQuestions
    myQuestionsTitle: 'My questions',
    myQuestionsEmpty: 'No questions yet',
    myQuestionsEmptyDesc: 'Ask your first question to the community',
    myQuestionsAskNew: 'Ask a question',
    myQuestionsOpen: 'Open',
    myQuestionsAnswered: 'Answered',
    myQuestionsClosed: 'Closed',

    // Privacy
    privacyBack: 'Back',
    privacyTitle: 'Privacy Policy',
    privacyContent: 'Content not available yet.',
    privacyLastUpdated: 'Last updated:',

    // Terms
    termsBack: 'Back',
    termsTitle: 'Terms of Service',
    termsContent: 'Content not available yet.',
    termsLastUpdated: 'Last updated:',

    // AdminNotifications
    adminNotificationsTitle: 'Notification rule',
    adminNotificationsNew: 'New notification rule',
    adminNotificationsEdit: 'Edit rule',
    adminNotificationsManual: 'Manual',
    adminNotificationsManualDesc: 'Send only by clicking "Send now"',
    adminNotificationsScheduled: 'Scheduled time',
    adminNotificationsScheduledDesc: 'Send automatically at a specific time',
    adminNotificationsCalendar: 'New calendar appointment',
    adminNotificationsCalendarDesc: 'Send when a new appointment is created in the calendar',
    adminNotificationsBlog: 'New blog post',
    adminNotificationsBlogDesc: 'Send when a new blog post is published',
    adminNotificationsSleep: 'Sleep log saved',
    adminNotificationsSleepDesc: 'Send when a sleep log is saved',
    adminNotificationsQuestion: 'New question',
    adminNotificationsQuestionDesc: 'Send when a user asks a new question',
    adminNotificationsName: 'Name (internal)',
    adminNotificationsNamePlaceholder: 'e.g. Morning update',
    adminNotificationsTrigger: 'Trigger — when should it be sent?',

    // AdminSupport
    adminSupportTitle: 'Support',
    adminSupportNoMessages: 'No support messages yet 🌙',
    adminSupportReplyLabel: 'Reply sent!',
    adminSupportError: 'Error sending',

    // AdminTermsPrivacy
    adminTermsPrivacyTitle: 'Legal content',
    adminTermsPrivacyTerms: 'Terms of Service',
    adminTermsPrivacyPrivacy: 'Privacy Policy',
    adminTermsPrivacyLoading: 'Loading...',
    adminTermsPrivacyAccess: 'Access denied',
    adminTermsPrivacyAdminOnly: 'Only admins can access',
    adminTermsPrivacyTitleField: 'Title',
    adminTermsPrivacyContent: 'Content',
    adminTermsPrivacySaved: 'Saved!',
    adminTermsPrivacyError: 'Error saving',
    adminTermsPrivacySaving: 'Saving...',

    // AdminUsers
    adminUsersTitle: 'Users',
    adminUsersSearch: 'Search by email or name...',
    adminUsersLoading: 'Loading...',
    adminUsersNoResults: 'No users found',
    adminUsersTrial: 'Trial',
    adminUsersActive: 'Active',
    adminUsersExpired: 'Expired',

    // AdminWonderWeeks
    adminWonderWeeksTitle: 'Wonder weeks emojis',
    adminWonderWeeksDesc: 'Choose emoji for each wonder week. They will be shown on the landing page and in the Knowledge tab.',
    adminWonderWeeksWonder: 'Wonder week',
    adminWonderWeeksSave: 'Save all emojis',
    adminWonderWeeksSaved: 'Emojis saved ✓',
    adminWonderWeeksAdminOnly: 'Admins only',

    // ColorThemeEditor
    colorThemeEditorName: 'Name *',
    colorThemeEditorNamePlaceholder: 'e.g. Sand & Chocolate',
    colorThemeEditorDescription: 'Description',
    colorThemeEditorDescPlaceholder: 'e.g. Classic and warm',
    colorThemeEditorCoreColors: '🎨 6 core colors',
    colorThemeBg: 'Background',
    colorThemeBgHint: 'Page background (light)',
    colorThemeCard: 'Card',
    colorThemeCardHint: 'Card background (light)',
    colorThemePrimary: 'Primary',
    colorThemePrimaryHint: 'Buttons & highlights',
    colorThemeAccent: 'Accent',
    colorThemeAccentHint: 'Secondary highlight',
    colorThemeText: 'Text',
    colorThemeTextHint: 'Primary text color (light)',
    colorThemeDarkBg: 'Dark background',
    colorThemeDarkBgHint: 'Page background (dark)',
    colorThemePreview: '👁 Preview',
    colorThemeActive: 'Active for users',
    colorThemeOrder: 'Order',
    colorThemeCancel: 'Cancel',
    colorThemeSaveTheme: 'Save theme',
    colorThemeSaving: 'Saving...',
    colorThemeSaved: 'Color theme saved! Users will see the new theme on next app open.',
    colorThemeChoose: 'Choose app color theme',
    colorThemeChooseDesc: 'This theme applies to all app users',

    // ColorThemePicker
    colorThemePickerTitle: 'Choose app color theme',
    colorThemePickerDesc: 'This theme applies to all app users',

    // MilestoneFrameEditor
    milestoneFrameEditorNew: 'New milestone',
    milestoneFrameEditorEdit: 'Edit milestone',
    milestoneFrameEditorDeleted: 'Deleted',
    milestoneFrameEditorSaved: 'Saved!',
    milestoneFrameEditorID: 'ID (unique key)',
    milestoneFrameEditorIDPlaceholder: 'e.g. preg-12',
    milestoneFrameEditorCategory: 'Category',
    milestoneFrameEditorLabel: 'Label (short)',
    milestoneFrameEditorLabelPlaceholder: 'e.g. 1 year',
    milestoneFrameEditorEmoji: 'Emoji',
    milestoneFrameEditorEmojiPlaceholder: '🎂',
    milestoneFrameEditorHeadline: 'Headline (large text on sticker)',
    milestoneFrameEditorHeadlinePlaceholder: 'e.g. 1 year 🎉',
    milestoneFrameEditorSubline: 'Subline (small text)',
    milestoneFrameEditorSublinePlaceholder: 'e.g. Happy birthday!',
    milestoneFrameEditorBackground: 'Background',
    milestoneFrameEditorAccent: 'Accent',
    milestoneFrameEditorTextColor: 'Text',
    milestoneFrameEditorSticker: 'Sticker image (replaces emoji)',
    milestoneFrameEditorRemoveImage: 'Remove image',
    milestoneFrameEditorUploadSticker: 'Upload sticker image',
    milestoneFrameEditorOrder: 'Sort order',
    milestoneFrameEditorActive: 'Active',
    milestoneFrameSaving: 'Saving...',
    milestoneFrameHeadlinePreview: 'Headline',
    milestoneFrameSublinePreview: 'Subline',

    // PushNotificationSender
    pushNotificationSenderTitle: 'Send push notification',
    pushNotificationSenderTitleLabel: 'Title',
    pushNotificationSenderTitlePlaceholder: 'e.g. New product in the shop 🎉',
    pushNotificationSenderMessage: 'Message',
    pushNotificationSenderMessagePlaceholder: 'e.g. We\'ve just added a new baby care package with 20% off...',
    pushNotificationSenderLink: 'Link (optional)',
    pushNotificationSenderLinkPlaceholder: 'e.g. /Shop',
    pushNotificationSenderButton: 'Send to all users',
    pushNotificationSenderSending: 'Sending...',
    pushNotificationSenderError: 'Fill in title and message',
    pushNotificationSenderSuccess: 'Notification sent to {recipients} users!',
    pushNotificationSenderFailed: 'Something went wrong – please try again',
  },
};

const LanguageContext = createContext({
  lang: 'da',
  t: translations.da,
  setLang: () => {},
});

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    return localStorage.getItem('app-language') || 'da';
  });

  const setLang = (newLang) => {
    localStorage.setItem('app-language', newLang);
    setLangState(newLang);
  };

  const t = translations[lang] || translations.da;

  return (
    <LanguageContext.Provider value={{ lang, t, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}